** BITNAMES **
GPWUF=0X07
PA0=0X05
NOT_TO=0X04
NOT_PD=0X03
Z=0X02
DC=0X01
C=0X00
NOT_GPWU=0X07
NOT_GPPU=0X06
T0CS=0X05
T0SE=0X04
PSA=0X03
PS2=0X02
PS1=0X01
PS0=0X00
CMPOUT=0X07
COUTEN=0X06
POL=0X05
CMPT0CS=0X04
CMPON=0X03
CNREF=0X01
CWU=0X00
CAL6=0X07
CAL5=0X06
CAL4=0X05
CAL3=0X04
CAL2=0X03
CAL1=0X02
CAL0=0X01
FOSC4=0X00
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
TMR0="Timer0 module's register"
PCL="Program counter's (PC) least significant byte"
GPWUF=STATUS.7,"GPIO reset"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"
FSR="Indirect data memory address pointer" 
NOT_GPWU=OPTION_REG.7,"Enable Wake-up on Pin Change (GP0, GP1, GP3)"
NOT_GPPU=OPTION_REG.6,"Enable Weak Pull-ups (GP0, GP1, GP3)"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select"
PSA=OPTION_REG.3,"Prescaler Assignment"
PS2=OPTION_REG.2,"Prescaler Rate Select"
PS1=OPTION_REG.1,"Prescaler Rate Select"
PS0=OPTION_REG.0,"Prescaler Rate Select"
OSCCAL="Oscillator Calibration bits",[1..7]
FOSC4=OSCCAL.0,"INTOSC/4 Output Enable"
GP3=GPIO.3,"Input only pin (with interrupt on change)<br>Internal software programmable weak pull-up<br>MCLR"
GP2=GPIO.2,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
GP1=GPIO.1,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up<br>CIN-"
GP0=GPIO.0,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up<br>CIN+"
RB3=PORTB.3,"Input only pin(with interrupt on change)<br>Internal software programmable weak pull-up<br>MCLR"
RB2=PORTB.2,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB1=PORTB.1,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up<br>CIN-"
RB0=PORTB.0,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up<br>CIN+"
TRISIO="I/O Control Register",[0..3]
TRISB="I/O Control Register",[0..3]
CMPOUT=CMCON0.7,"Comparator Output"
NOT_COUTEN=CMCON0.6,"Comparator Output Enable"
POL=CMCON0.5,"Comparator Output Polarity"
NOT_CMPT0CS=CMCON0.4,"Comparator TMR0 Clock Source"
CMPON=CMCON0.3,"Comparator Enable"
CNREF=CMCON0.2,"Comparator Negative Reference Select"
CPREF=CMCON0.1,"Comparator Positive Reference Select"
CWU=CMCON0.0,"Comparator Wake-up on Change Enable"
