** BITNAMES **
GPWUF=0X07
PA0=0X05
NOT_TO=0X04
NOT_PD=0X03
Z=0X02
DC=0X01
C=0X00
NOT_GPWU=0X07
NOT_GPPU=0X06
T0CS=0X05
T0SE=0X04
PSA=0X03
PS2=0X02
PS1=0X01
PS0=0X00
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
TMR0="Timer0 module's register"
PCL="Program counter's (PC) least significant byte"
GPWUF=STATUS.7,"GPIO reset flag"
PA0=STATUS.5,"Program page preselect"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"
FSR="Indirect data memory address pointer"
NOT_GPWU=OPTION_REG.7,"Enable Wake-up on Pin Change (GP0, GP1, GP3)"
NOT_GPPU=OPTION_REG.6,"Enable Weak Pull-ups (GP0, GP1, GP3)"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select"
PSA=OPTION_REG.3,"Prescaler Assignment"
PS2=OPTION_REG.2,"Prescaler Rate Select"
PS1=OPTION_REG.1,"Prescaler Rate Select"
PS0=OPTION_REG.0,"Prescaler Rate Select"
OSCCAL="Oscillator Calibration register CAL5-0",[0..5]
GB5=GPIO.5,"Bi-directional I/O pin"
GP4=GPIO.4,"Bi-directional I/O pin<br>NOT_MCLR"
GP3=GPIO.3,"Input only pin(with wake up on change)<br>Internal software programmable weak pull-up"
GP2=GPIO.2,"Bi-directional I/O pin"
GP1=GPIO.1,"Bi-directional I/O pin (with wake up on change)<br>Internal software programmable weak pull-up<br>CIN-"
GP0=GPIO.0,"Bi-directional I/O pin (with wake up on change)<br>Internal software programmable weak pull-up"
RB5=PORTB.5,"Bi-directional I/O pin"
RB4=PORTB.4 ,"Bi-directional I/O pin<br>NOT_MCLR"
RB3=PORTB.3,"Input only pin(with wake up on change)<br>Internal software programmable weak pull-up"
RB2=PORTB.2,"Bi-directional I/O pin"
RB1=PORTB.1,"Bi-directional I/O pin (with wake up on change)<br>Internal software programmable weak pull-up<br>CIN-"
RB0=PORTB.0,"Bi-directional I/O pin (with wake up on change)<br>Internal software programmable weak pull-up"
TRISIO="I/O Control Registers",[0..5]
TRISB="I/O Control Registers",[0..5]
