** BITNAMES **
IRP=0X07
RP1=0X06
RP0=0X05
NOT_TO=0X04
NOT_PD=0X03
Z=0X02
DC=0X01
C=0X00
ADCS1=0X07
ADCS0=0X06
CHS1=0X04
CHS0=0X03
GO=0X02
NOT_DONE=0X02
GO_DONE=0X02
ADON=0X00
GIE=0X07
PEIE=0X06
T0IE=0X05
INTE=0X04
GPIE=0X03
T0IF=0X02
INTF=0X01
GPIF=0X00
ADIF=0X06
NOT_GPPU=0X07
INTEDG=0X06
T0CS=0X05
T0SE=0X04
PSA=0X03
PS2=0X02
PS1=0X01
PS0=0X00
ADIE=0X06
NOT_POR=0X01
CAL3=0X07
CAL2=0X06
CAL1=0X05
CAL0=0X04
CALFST=0X03
CALSLW=0X02
PCFG2=0X02
PCFG1=0X01
PCFG0=0X00
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
TMR0="Timer0 module's register"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero"
DC=STATUS.1,[protect], "Digit Carry"
C=STATUS.0,"Carry"
FSR="Indirect data memory address pointer"
GP5=GPIO.5,"Bi-directional I/O pin"
GP4=GPIO.4,"Bi-directional I/O pin<br>NOT_MCLR"
GP3=GPIO.3,"Input only pin(with wake up on change)<br>Internal software programmable weak pull-up"
GP2=GPIO.2,"Bi-directional I/O pin"
GP1=GPIO.1,"Bi-directional I/O pin (with wake up on change)<br>Internal software programmable weak pull-up<br>CIN-"
GP0=GPIO.0,"Bi-directional I/O pin (with wake up on change)<br>Internal software programmable weak pull-up"
RB5=PORTB.5,"Bi-directional I/O pin"
RB4=PORTB.4 ,"Bi-directional I/O pin<br>NOT_MCLR"
RB3=PORTB.3,"Input only pin(with wake up on change)<br>Internal software programmable weak pull-up"
RB2=PORTB.2,"Bi-directional I/O pin"
RB1=PORTB.1,"Bi-directional I/O pin (with wake up on change)<br>Internal software programmable weak pull-up<br>CIN-"
RB0=PORTB.0,"Bi-directional I/O pin (with wake up on change)<br>Internal software programmable weak pull-up"
TRISIO="I/O Control Registers",[0..5]
TRISB="I/O Control Registers",[0..5]
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4]
GIE=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
T0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INTE=INTCON.4,"External Interrupt Enable"
GPIE=INTCON.3,"GPIO Port Change Interrupt Enable"
T0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INTF=INTCON.1,"External Interrupt Flag"
GPIF=INTCON.0,"GPIO Port Interrupt Flag"
ADIE=PIE1.6,"A/D Converter Interrupt Enable"
ADIF=PIR1.6,"A/D Converter Interrupt Flag"
CAL3=OSCCAL.7,"Fine Calibration"
CAL2=OSCCAL.6,"Fine Calibration"
CAL1=OSCCAL.5,"Fine Calibration"
CAL0=OSCCAL.4,"Fine Calibration"
CALFST=OSCCAL.3,"Calibration Fast"
CALSLW=OSCCAL.2,"Calibration Slow"
POR=PCON.1,"Power-on Reset Status flag"
ADRES="A/D result Register",[0..7]
ADCS1=ADCON0.7,"A/D Conversion Clock Select"
ADCS0=ADCON0.6,"A/D Conversion Clock Select"
CHS1=ADCON0.4,"Analog Channel Select"
CHS0=ADCON0.3,"Analog Channel Select"
NOT_DONE=ADCON0.2,"A/D Conversion Status flag"
GO_DONE=ADCON0.2,"A/D Conversion Enable"
ADON=ADCON0.0,"A/D ON bit"
PCFG2=ADCON1.2,"A/D Port Configuration Control bits"
PCFG1=ADCON1.1,"A/D Port Configuration Control bits"
PCFG0=ADCON1.0,"A/D Port Configuration Control bits"
NOT_GPWU=OPTION_REG.7,"Enable Wake-up on Pin Change (GP0, GP1, GP3)"
INTEDG=OPTION_REG.6,"Interrupt Edge"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select"
PSA=OPTION_REG.3,"Prescaler Assignment"
PS2=OPTION_REG.2,"Prescaler Rate Select"
PS1=OPTION_REG.1,"Prescaler Rate Select"
PS0=OPTION_REG.0,"Prescaler Rate Select"

