** BITNAMES **

INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
TMR0="Timer0 module's register"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"
FSR="Indirect data memory address pointer"
GP5=GPIO.5,"General purpose I/O.<br> Individually controlled interrupt-on-change.<br> Individually enabled pull-up/pull-down."
T1CK1=GPIO.5,"TMR1 clock"
OSC1=GPIO.5,"XTAL connection"
CLKIN=GPIO.5,"Tosc reference clock."
GP4=GPIO.4,"General purpose I/O.<br> Individually controlled interrupt-on-change.<br> Individually enabled pull-up/pull-down."
NOT_T1G=GPIO.4,"TMR1 gate"
OSC2=GPIO.4,"XTAL connection"
CLKOUT=GPIO.4,"FOSC/4 reference clock."
GP3=GPIO.3,"General purpose input.<br> Individually controlled interrupt-on-change."
NOT_MCLR=GPIO.3,"Master Clear Reset.<br> Pull-up enabled when configured as MCLR."
VPP=GPIO.3,"Programming voltage"
GP2=GPIO.2,"General purpose I/O.<br> Individually controlled interrupt-on-change.<br> Individually enabled pull-up/pull-down."
T0CKI=GPIO.2,"External clock for Timer0."
INT=GPIO.2,"External interrupt"
COUT=GPIO.2,"Comparator 1 output"
GP1=GPIO.1,"General purpose I/O.<br> Individually controlled interrupt-on-change.<br> Individually enabled pull-up/pull-down."
C1IN_MINUS=GPIO.1,"Comparator 1 input - negative"
ICSPCLK=GPIO.1,"Serial programming clock"
GP0=GPIO.0,"General purpose I/O.<br> Individually controlled interrupt-on-change.<br> Individually enabled pull-up/pull-down.<br> Selectable Ultra Low-Power Wake-up pin."
C1IN_PLUS=GPIO.0,"Comparator 1 input - positive."
ICSPDAT=GPIO.0,"Serial programming data I/O"
ULPWU=GPIO.0,"Ultra Low-Power Wake-up input."
PORTB="See GPIO"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4] 
GIE=INTCON.7,"Global Interrupt Enable bit"
PEIE=INTCON.6,"Peripheral Interrupt Enable bit"
T0IE=INTCON.5,"TMR0 Overflow Interrupt Enable bit"
INTE=INTCON.4,"GP2/INT External Interrupt Enable"
RAIE=INTCON.3,"Port Change Interrupt Enable bit"
T0IF=INTCON.2,"TMR0 Overflow Interrupt Flag bit"
INTF=INTCON.1,"GP2/INT External Interrupt Flag"
RAIF=INTCON.0,"Port Change Interrupt Flag"
EEIF=PIR1.7,"EEPROM Write Operation Interrupt Flag bit."
LVDIF=PIR1.6,"Low-Voltage Detect Interrupt Flag bit."
CRIF=PIR1.5,"Cryptographic Interrupt Flag bit."
C1IF=PIR1.3,"Comparator 1 Interrupt Flag bit."
OSFIF=PIR1.2,"Oscillator Fail Interrupt Flag bit."
TMR1IF=PIR1.0,"Timer1 Interrupt Flag bit."
TMR1L="Holding register for the Least Significant Byte of the 16 bit TMR1 register"
TMR1H="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
T1GINV=T1CON.7,"Timer1 Gate Invert bit."
TMR1GE=T1CON.6,"Timer1 Gate Enable bit."
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"LP Oscillator Enable Control bit."
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control bit."
TMR1CS=T1CON.1,"Timer1 Clock Source Select bit."
TMR1ON=T1CON.0,"Timer1 On bit."
WDTPS3=WDTCON.4,"Watchdog Timer Period Select bits"
WDTPS2=WDTCON.3,"Watchdog Timer Period Select bits"
WDTPS1=WDTCON.2,"Watchdog Timer Period Select bits"
WDTPS0=WDTCON.1,"Watchdog Timer Period Select bits"
SWDTEN=WDTCON.0,"Software Enable/Disable for Watchdof Timer bit"
COUT=CMCON0.6,"Comparator 1 Output bit"
CINV=CMCON0.4,"Comparator 1 Output Inversion bit"
CIS=CMCON0.3,"Comparator Input Switch bit"
CM2=CMCON0.2,"Comparator Mode bits"
CM1=CMCON0.1,"Comparator Mode bits"
CM0=CMCON0.0,"Comparator Mode bits"
T1GSS=CMCON1.1,"Timer1 Gate Source Select bit"
C1SYNC=CMCON1.0,"Comparator 1 Synchronize bit"
NOT_RAPU=OPTION_REG.7,"PORTA Pull-up/Pull-down Enable bit"
INTEDG=OPTION_REG.6,"Interrupt Edge Select bit"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select bit"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select bit"
PSA=OPTION_REG.3,"Prescaler Assignment bit"
PS2=OPTION_REG.2,"Prescaler Rate Select bits"
PS1=OPTION_REG.1,"Prescaler Rate Select bits"
PS0=OPTION_REG.0,"Prescaler Rate Select bits"
TRISIO5=TRISIO.5,"Direction Control bit for pin GPIO.5"
TRISIO4=TRISIO.4,"Direction Control bit for pin GPIO.4"
TRISIO3=TRISIO.3,"GPIO3 is input only"
TRISIO2=TRISIO.2,"Direction Control bit for pin GPIO.2"
TRISIO1=TRISIO.1,"Direction Control bit for pin GPIO.1"
TRISIO0=TRISIO.0,"Direction Control bit for pin GPIO.0"
TRISB="See TRISIO"
EEIE=PIE1.7,"EE Write Complete Interrupt Enable bit"
LVDIE=PIE1.6,"Low-Voltage Detect Interrupt Enable bit"
CRIE=PIE1.5,"Cryptographic Interrupt Enable bit"
C1IE=PIE1.3,"Comparator 1 Interrupt Enable bit"
OSFIE=PIE1.2,"Oscillator Fail Interrupt Enable bit"
TMR1IE=PIE1.0,"Timer1 Interrupt Enable bit"
ULPWUE=PCON.5,"Ultra Low-Power Wake-up Enable bit"
SBODEN=PCON.4,"Software BOD Enable bit"
NOT_WUR=PCON.3,"Wake-up Reset Status bit"
NOT_POR=PCON.1,"Power-on Reset Status bit"
NOT_BOD=PCON.0,"Brown-out Detect Status bit"
IRCF2=OSCCON.6,"Nominal Internal Oscillator Frequency Select bits"
IRCF1=OSCCON.5,"Nominal Internal Oscillator Frequency Select bits"
IRCF0=OSCCON.4,"Nominal Internal Oscillator Frequency Select bits"
OSTS=OSCCON.3,"Oscillator Start-up Time-out Status bit"
HTS=OSCCON.2,"HFINTOSC (High Frequency – 8 MHz to 125 kHz) Status bit"
LTS=OSCCON.1,"LFINTOSC (Low Frequency – 31 kHz) Stable bit"
SCS=OSCCON.0,"System Clock Select bit"
TUN4=OSCTUNE.4,"Frequency Tunning bits"
TUN3=OSCTUNE.3,"Frequency Tunning bits"
TUN2=OSCTUNE.2,"Frequency Tunning bits"
TUN1=OSCTUNE.1,"Frequency Tunning bits"
TUN0=OSCTUNE.0,"Frequency Tunning bits"
IRVST=LVDCON.5,"Internal Reference Voltage Stable Status Flag bit"
LVDEN=LVDCON.4,"Low-Voltage Detect Power Enable bit"
LVDL2=LVDCON.2,"Low-Voltage Detection Limit bits (nominal values)"
LVDL1=LVDCON.1,"Low-Voltage Detection Limit bits (nominal values)"
LVDL0=LVDCON.0,"Low-Voltage Detection Limit bits (nominal values)"
WPUDA5=WPUDA.5,"Pull-up/Pull-down Direction Selection bits"
WPUDA4=WPUDA.4,"Pull-up/Pull-down Direction Selection bits"
WPUDA2=WPUDA.2,"Pull-up/Pull-down Direction Selection bits"
WPUDA1=WPUDA.1,"Pull-up/Pull-down Direction Selection bits"
WPUDA0=WPUDA.0,"Pull-up/Pull-down Direction Selection bits"
IOCA5=IOCA.5,"Interrupt-on-change PORTA Control bits"
IOCA4=IOCA.4,"Interrupt-on-change PORTA Control bits"
IOCA3=IOCA.3,"Interrupt-on-change PORTA Control bits"
IOCA2=IOCA.2,"Interrupt-on-change PORTA Control bits"
IOCA1=IOCA.1,"Interrupt-on-change PORTA Control bits"
IOCA0=IOCA.0,"Interrupt-on-change PORTA Control bits"
WDA5=WDA.5,"Pull-up/Pull-down Selection bits"
WDA4=WDA.4,"Pull-up/Pull-down Selection bits"
WDA2=WDA.2,"Pull-up/Pull-down Selection bits"
WDA1=WDA.1,"Pull-up/Pull-down Selection bits"
WDA0=WDA.0,"Pull-up/Pull-down Selection bits"
VREN=VRCON.7,"CVref Enable bit"
VRR=VRCON.5,"CVref Range Selection bit"
VR3=VRCON.3,"CVREF Value Selection bits 0 = VR<3:0> = 15"
VR2=VRCON.2,"CVREF Value Selection bits 0 = VR<3:0> = 15"
VR1=VRCON.1,"CVREF Value Selection bits 0 = VR<3:0> = 15"
VR0=VRCON.0,"CVREF Value Selection bits 0 = VR<3:0> = 15"
EEDAT="Byte Value to Write to or Read From Data EEPROM bits"
EEADR="Specifies 1 of 128 Locations for EEPROM Read/Write Operation bits",[0..6]
EEADR7=EEADR.7,"Read as ‘0’ on PIC12F635"
WRERR=EECON1.3,"EEPROM Error Flag bit"
WREN=EECON1.2,"EEPROM Write Enable bit"
WR=EECON1.1,"Write Control bit"
RD=EECON1.0,"Read Control bit"
EECON2="EEPROM Control Register 2 (not a physical register)"
GO=CRCON.7,"_ "
NOT_DONE=CRCON.7,"_ "
ENC=CRCON.6,"_ "
NOT_DEC=CRCON.6,"_ "
CRREG1=CRCON.1,"_ "
CRREG0=CRCON.0,"_ "
CRDAT0="Cryptographic Data Register 0"
CRDAT1="Cryptographic Data Register 1"
CRDAT2="Cryptographic Data Register 2"
CRDAT3="Cryptographic Data Register 3"






