** BITNAMES **

TMR0="Timer0 module's register"
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
PCL="Program counter's (PC) least significant byte"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"
FSR="Indirect data memory address pointer"
RA0=PORTA.0,"Bi-directional I/O pin"
AN0=PORTA.0,"Analog input pin"
RA1=PORTA.1,"Bi-directional I/O pin"
AN1=PORTA.1,"Analog input pin"
RA2=PORTA.2,"Bi-directional I/O pin"
AN2=PORTA.2,"Analog input pin"
RA3=PORTA.3,"Bi-directional I/O pin"
AN3=PORTA.3,"Analog input pin"
VREF=PORTA.3,"Voltage reference pin"
RA4=PORTA.4,"Bi-directional I/O<br>Output is open drain type"
T0CK1=PORTA.4,"External clock input for Timer0"
RA5=PORTA.5,"Bi-directional I/O pin"
NOT_SS=PORTA.5,"Slave select input for synchronous serial port"
AN4=PORTA.5,"Analog input pin"
RB0=PORTB.0,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
INT=PORTB.0,"External interrupt input"
RB1=PORTB.1,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB2=PORTB.2,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB3=PORTB.3,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB4=PORTB.4,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
RB5=PORTB.5,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
RB6=PORTB.6,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
PGC=PORTB.6,"Serial programming clock"
RB7=PORTB.7,"Input/output pin (with interrupt on change)<br>Internal software programmable weak pull-up"
PGD=PORTB.7,"Serial programming data"
RC0=PORTC.0,"Bi-directional I/O pin"
T1OSO=PORTC.0,"Timer1 oscillator output"
T1CKI=PORTC.0,"Timer1 clock input"
RC1=PORTC.1,"Bi-directional I/O pin"
T1OSI=PORTC.1,"Timer1 oscillator input<br>Capture2 input"
RC2=PORTC.2,"Bi-directional I/O pin"
CCP1=PORTC.2,"Capture1 input<br>Compare1 output<br>PWM1 output"
RC3=PORTC.3,"Bi-directional I/O pin"
SCK=PORTC.3,"Synchronous serial clock (SPI mode)"
SCL=PORTC.3,"Synchronous serial clock (I2C mode)"
RC4=PORTC.4,"Bi-directional I/O pin"
SDI=PORTC.4,"Data In (SPI mode)"
SDA=PORTC.4,"Data Input/output (I2C mode)"
RC5=PORTC.5,"Bi-directional I/O pin"
SDO=PORTC.5,"Sychronous Serial Port Output"
RC6=PORTC.6,"Bi-directional I/O pin"
RC7=PORTC.7,"Bi-directional I/O pin" 
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4] 
GIE=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
T0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INTE=INTCON.4,"RB0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
T0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INTF=INTCON.1,"RB0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"
ADIF=PIR1.6,"A/D Converter Interrupt Flag"
RCIF=PIR1.5,"USART Receive Interrupt Flag"
TXIF=PIR1.4,"USART Transmit Interrupt Flag"
SSPIF=PIR1.3,"Synchronous Serial Port (SSP) Interrupt Flag"
CCP1IF=PIR1.2,"CCP1 Interrupt Flag"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag"
CCP2IF=PIR2.0,"CCP2 Interrupt Flag"
TMR1L="Holding register for the Least Significant Byte of the 16 bit TMR1 register"
TMR1H="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"
TMR2="Timer2 module's register"
TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 ON"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"
SSPBUF="Synchonous serial port receive buffer or transmit register"
WCOL=SSPCON.7,"Write Collision Detect flag"
SSPOV=SSPCON.6,"Receive Overflow Indicator flag"
SSPEN=SSPCON.5,"Synchronous Serial Port Enable flag"
CKP=SSPCON.4,"Clock Polarity Select bit"
SSPM3=SSPCON.3,"Synchronous Serial Port Mode Select bits"
SSPM2=SSPCON.2,"Synchronous Serial Port Mode Select bits"
SSPM1=SSPCON.1,"Synchronous Serial Port Mode Select bits"
SSPM0=SSPCON.0,"Synchronous Serial Port Mode Select bits"
CCPR1L="Capture or Compare or PWM register1 (LSB)"
CCPR1H="Capture or Compare or PWM register1 (MSB)"
CCP1X=CCP1CON.5,"PWM1 Least Significant bits"
CCP1Y=CCP1CON.4,"PWM1 Least Significant bits"
CCP1M3=CCP1CON.3,"CCP1 Mode Select"
CCP1M2=CCP1CON.2,"CCP1 Mode Select"
CCP1M1=CCP1CON.1,"CCP1 Mode Select"
CCP1M0=CCP1CON.0,"CCP1 Mode Select"
ADRES="A/D result as a 8 bit value",[0..7]
SPEN=RCSTA.7,"Serial Port Enable"
RX9=RCSTA.6,"9-bit Receive Enable"
SREN=RCSTA.5,"Single Receive Enable"
CREN=RCSTA.4,"Continuous Receive Enable"
FERR=RCSTA.2,"Framing Error"
OERR=RCSTA.1,"Overrun Error"
RX9D=RCSTA.0,"9th bit of received data (Can be parity bit)" 
TXREG="USART transmit data register"
RCREG="USART receive data register"
CCPR2L="Capture or Compare or PWM register2 (LSB)"
CCPR2H="Capture or Compare or PWM register2 (MSB)"
CCP2X=CCP2CON.5,"PWM2 Least Significant bits"
CCP2Y=CCP2CON.4,"PWM2 Least Significant bits"
CCP2M3=CCP2CON.3,"CCP2 Mode Select"
CCP2M2=CCP2CON.2,"CCP2 Mode Select"
CCP2M1=CCP2CON.1,"CCP2 Mode Select"
CCP2M0=CCP2CON.0,"CCP2 Mode Select"
ADRESH="A/D result register high byte"
ADCS1=ADCON0.7,"A/D Conversion Clock Select bits"
ADCS0=ADCON0.6,"A/D Conversion Clock Select bits"
CHS2=ADCON0.5,"Analog Channel Select bits"
CHS1=ADCON0.4,"Analog Channel Select bits"
CHS0=ADCON0.3,"Analog Channel Select bits"
NOT_DONE=ADCON0.2,"A/D Conversion Status flag"
GO_DONE=ADCON0.2,"A/D Conversion Enable"
ADON=ADCON0.0,"A/D ON bit"
NOT_RBPU=OPTION_REG.07,"PORTB Pull-up Enable"
INTEDG=OPTION_REG.6,"Interrupt Edge Select"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select"
PSA=OPTION_REG.3,"Prescaler Assignment"
PS2=OPTION_REG.2,"Prescaler Rate Select"
PS1=OPTION_REG.1,"Prescaler Rate Select"
PS0=OPTION_REG.0,"Prescaler Rate Select"
TRISA="PORTA data direction register",[0..5]
TRISB="PORTB data direction register"
TRISC="PORTC data direction register"
ADIE=PIE1.6,"A/D Converter Interrupt Enable"
RCIE=PIE1.5,"USART Receive Interrupt Enable"
TXIE=PIE1.4,"USART Transmit Interrupt Enable"
SSPIE=PIE1.3,"Synchronous Serial Port Interrupt Enable"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable"
TMR1IE=PIE1.0,"TMR1 Overflow Interrupt Enable"
CCP2IE=PIE2.0,"CCP2 Interrupt Enable"
NOT_POR=PCON.1,"Power-on Reset Status flag"
NOT_BOR=PCON.0,"Brown-out Reset Status flag"
PR2="Timer2 period register"
SSPADD="Synchronous serial port (I2C mode) address register"
D_A=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
DATA_ADDR=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
P=SSPSTAT.4,"I2C Stop"
I2C_STP=SSPSTAT.4,"I2C Stop"
S=SSPSTAT.3,"I2C Start"
I2C_STR=SSPSTAT.3,"I2C Start"
R_W=SSPSTAT.2,"Read/Write bit information (I2C mode only)"
UA=SSPSTAT.1,"Update Address (10-bit I2C mode only)"
BF=SSPSTAT.0,"Buffer Full Status flag"
CSRC=TXSTA.7,"Clock Source Select flag"
TX9=TXSTA.6,"9-bit Transmit Enable"
NOT_TX8=TXSTA.6,"9-bit Transmit Enable" 
TX8_9=TXSTA.6,"9-bit Transmit Enable" 
TXEN=TXSTA.5,"Transmit Enable"
SYNC=TXSTA.4,"USART Mode Select flag"
BRGH=TXSTA.2,"High Baud Rate Select flag"
TRMT=TXSTA.1,"Transmit Shift Register Status flag"
TX9D=TXSTA.0,"9th bit of transmit data. Can be parity bit."
TXD8=TXSTA.0,"9th bit of transmit data. Can be parity bit."
SPBRG="Baud rate generator"
PCFG3=ADCON1.3,"A/D Port Configuration Control bits"
PCFG2=ADCON1.2,"A/D Port Configuration Control bits"
PCFG1=ADCON1.1,"A/D Port Configuration Control bits"
PCFG0=ADCON1.0,"A/D Port Configuration Control bits"
