** BITNAMES **

INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
TMR0="Timer0 module's register"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out bit"
PD=STATUS.3,"Power Down bit"
Z=STATUS.2,"Zero bit"
DC=STATUS.1,[protect], "Digit Carry bit"
C=STATUS.0,"Carry bit"
FSR="Indirect data memory address pointer"
RA5=PORTA.5,"PORTA I/O w/prog pull-up and interrupt-on-change"
T1CKI=PORTA.5,"Timer1 clock"
OSC1=PORTA.5,"Crystal/Resonator"
CLKIN=PORTA.5,"External clock input/RC oscillator connection"
RA4=PORTA.4,"PORTA I/O w/prog pull-up and interrupt-on-change"
AN3=PORTA.4,"A/D Channel 3 input"
NOT_T1G=PORTA.4,"Timer1 gate"
OSC2=PORTA.4,"Crystal/Resonator"
CLKOUT=PORTA.4,"FOSC/4 output"
RA3=PORTA.3,"PORTA input with interrupt-on-change"
NOT_MCLR=PORTA.3,"Master Clear w/internal pull-up"
VPP=PORTA.3,"Programming voltage"
RA2=PORTA.2,"PORTA I/O w/prog pull-up and interrupt-on-change"
AN2=PORTA.2,"A/D Channel 2 input"
T0CKI=PORTA.2,"Timer0 clock input"
INT=PORTA.2,"External Interrupt"
C1OUT=PORTA.2,"Comparator 1 output"
RA1=PORTA.1,"PORTA I/O w/prog pull-up and interrupt-on-change"
AN1=PORTA.1,"A/D Channel 1 input"
C1IN_MINUS=PORTA.1,"Comparator 1 input"
VREF=PORTA.1,"External Voltage Reference for A/D"
ICSPCLK=PORTA.1,"Serial Programming Clock"
RA0=PORTA.0,"PORTA I/O w/prog pull-up and interrupt-on-change"
AN0=PORTA.0,"A/D Channel 0 input"
C1IN_PLUS=PORTA.0,"Comparator 1 input"
ICSPDAT=PORTA.0,"Serial Programming Data I/O"
ULPWU=PORTA.0,"Ultra Low-Power Wake-up input"
RC0=PORTC.0,"PORTC I/O"
AN4=PORTC.0,"A/D Channel 4 input"
C2IN_PLUS=PORTC.0,"Comparator 2 input"
RC1=PORTC.1,"PORTC I/O"
AN5=PORTC.1,"A/D Channel 5 input"
C2IN_MINUS=PORTC.1,"Comparator 2 input"
RC2=PORTC.2,"PORTC I/O"
AN6=PORTC.2,"A/D Channel 6 input"
RC3=PORTC.3,"PORTC I/O"
AN7=PORTC.3,"A/D Channel 7 input"
RC4=PORTC.4,"PORTC I/O"
C2OUT=PORTC.4,"Comparator 2 output"
TX=PORTC.4,"USART asynchronous output"
CK=PORTC.4,"USART asynchronous clock"
RC5=PORTC.5,"PORTC I/O"
RX=PORTC.5,"USART asynchronous input"
DT=PORTC.5,"USART asynchronous data"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4]
GIE=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
T0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INTE=INTCON.4,"RA2/INT External Interrupt Enable"
RAIE=INTCON.3,"PORTA Change Interrupt Enable"
T0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INTF=INTCON.1,"RA2/INT External Interrupt Flag"
RAIF=INTCON.0,"PORTA Change Interrupt Flag"
EEIF=PIR1.7,"EEPROM Write Operation Interrupt Flag"
ADIF=PIR1.6,"A/D Interrupt Flag"
RCIF=PIR1.5,"USART Receive Interrupt Flag"
C2IF=PIR1.4,"Comparator 2 Interrupt Flag"
C1IF=PIR1.3,"Comparator 1 Interrupt Flag"
OSFIF=PIR1.2"Oscillator Fail Interrupt Flag"
TXIF=PIR1.1,"USART Transmit Interrupt Flag"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag bit"
TMR1L="Holding register for the Least Significant Byte of the 16 bit TMR1 register"
TMR1H="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
T1GINV=T1CON.7,"Timer1 Gate Invert bit"
TMR1GE=T1CON.6,"Timer1 Gate Enable bit"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"LP Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"
ABDOVF=BAUDCTL.7,"Auto Baud Detect Overflow bit"
RCIDL=BAUDCTL.6,"Receive IDLE Flag bit"
SCKP=BAUDCTL.4,"Synchronous Clock Polarity Select bit"
BRG16=BAUDCTL.3,"16-bit Baud Rate Generator bit"
WUE=BAUDCTL.1,"Wake-up Enable bit"
ABDEN=BAUDCTL.0,"Auto Baud Detect Enable bit"
SPBRGH="Baud Rate Generator register, high byte"
SPBRG="Baud Rate Generator register, low byte"
TXREG="USART transmit data register"
RCREG="USART receive data register"
CSRC=TXSTA.7,"Clock Source Select bit"
TX9=TXSTA.6,"9-bit Transmit Enable bit" 
TXEN=TXSTA.5,"Transmit Enable bit"
SYNC=TXSTA.4,"USART Mode Select bit"
SENDB=TXSTA.3,"Send Break Character bit"
BRGH=TXSTA.2,"High Baud Rate Select bit"
TRMT=TXSTA.1,"Transmit Shift Register Status bit"
TX9D=TXSTA.0,"9th bit of Transmit Data. Can be parity bit."
SPEN=RCSTA.7,"Serial Port Enable"
RX9=RCSTA.6,"9-bit Receive Enable""   
SREN=RCSTA.5,"Single Receive Enable"
CREN=RCSTA.4,"Continuous Receive Enable"
ADDEN=RCSTA.3,"Address Detect Enable"
FERR=RCSTA.2,"Framing Error bit"
OERR=RCSTA.1,"Overrun Error bit"
RX9D=RCSTA.0,"9th bit of received data (Can be parity bit)"
WDTPS3=WDTCON.4,"Watchdog Timer Period Select bits"
WDTPS2=WDTCON.3,"Watchdog Timer Period Select bits"
WDTPS1=WDTCON.2,"Watchdog Timer Period Select bits"
WDTPS0=WDTCON.1,"Watchdog Timer Period Select bits"
SWWDTEN=WDTCON.0,"Software Enable or Disable the Watchdog Timer"
C2OUT=CMCON0.7,"Comparator 2 output"
C1OUT=CMCON0.6,"Comparator 1 output"
C2INV=CMCON0.5,"Comparator 2 output inversion"
C1INV=CMCON0.4,"Comparator 1 output inversion"
CIS=CMCON0.3,"Comparator Input Switch"
CM2=CMCON0.2,"Comparator mode bits"
CM1=CMCON0.1,"Comparator mode bits"
CM0=CMCON0.0,"Comparator mode bits"
T1GSS=CMCON1.1,"Timer1 Gate Source Select bit"
C2SYNC=CMCON1.0,"Comparator 2 Synchronize bit"
ADRESH="Most Significant 8 bits of the left shifted A/D result or 2 bits of the right shifted result"
ADFM=ADCON0.7,"A/D Result Formed Select bit"
VCFG=ADCON0.6,"Voltage Reference bit"
CHS2=ADCON0.4,"Analog Channel Select bits"
CHS1=ADCON0.3,"Analog Channel Select bits"
CHS0=ADCON0.2,"Analog Channel Select bits"
GO=ADCON0.1,"A/D Conversion Status bit"
NOT_DONE=ADCON0.1,"A/D Conversion Status bit"
ADON=ADCON0.0,"A/D Conversion Status bit"
ADCS2=ADCON1.6,"A/D Conversion Clock Select bits"
ADCS1=ADCON1.5,"A/D Conversion Clock Select bits"
ADCS0=ADCON1.4,"A/D Conversion Clock Select bits"
NOT_RAPU=OPTION_REG.07,"PORTA Pull-up Enable bit"
INTEDG=OPTION_REG.6,"Interrupt Edge Select bit"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select bit"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select bit"
PSA=OPTION_REG.3,"Prescaler Assignment bit"
PS2=OPTION_REG.2,"Prescaler Rate Select bits"
PS1=OPTION_REG.1,"Prescaler Rate Select bits"
PS0=OPTION_REG.0,"Prescaler Rate Select bits"
TRISA="PORTA data direction register"
TRISB="<b>See TRISC</>"
TRISC="PORTC data direction register"
EEIE=PIE1.7,"EE Write Complete Interrupt Enable"
ADIE=PIE1.6,"A/D Converter Interrupt Enable"
RCIE=PIE1.5,"USART Receive Interrupt Enable"
C2IE=PIE1.4,"Comparator 2 Interrupt Enable"
C1IE=PIE1.3,"Comparator 1 Interrupt Enable"
OSFIE=PIE1.2,"Oscillator Fail Interrupt Enable"
TXIE=PIE1.1,"USART Transmit Interrupt Enable"
TMR1IE=PIE1.0,"Timer1 Overflow Interrupt Enable"
ULPWUE=PCON.5,"Ultra Low-Power Wake-up Enable bit"
SBODEN=PCON.4,"Software BOD Enable bit"
NOT_POR=PCON.1,"Power-on Reset Status bit"
NOT_BOD=PCON.0,"Brown-out Reset Status bit"
IRCF2=OSCCON.6,"Internal Oscillator Frequency Select bits"
IRCF1=OSCCON.5,"Internal Oscillator Frequency Select bits"
IRCF0=OSCCON.4,"Internal Oscillator Frequency Select bits"
OSTS=OSCCON.3,"Oscillator Start-up Time-out Status bit"
HTS=OSCCON.2,"HFINTOSC (High Frequency – 8 MHz to 125 kHz) Status bit"
LTS=OSCCON.1,"LFINTOSC (Low Frequency – 31 kHz) Stable bit"
SCS=OSCCON.0,"System Clock Select bit"
TUN4=OSCTUNE.4,"Frequency Tuning bits"
TUN3=OSCTUNE.3,"Frequency Tuning bits"
TUN2=OSCTUNE.2,"Frequency Tuning bits"
TUN1=OSCTUNE.1,"Frequency Tuning bits"
TUN0=OSCTUNE.0,"Frequency Tuning bits"
ANSEL="Analog select bits.<br>Select between analog or digital function <br>on pins AN<7:0>, respectively."
WPUA5=WPUA.5,"Weak Pull-up Register bits"
WPUA4=WPUA.4,"Weak Pull-up Register bits"
WPUA2=WPUA.2,"Weak Pull-up Register bits"
WPUA1=WPUA.1,"Weak Pull-up Register bits"
WPUA0=WPUA.0,"Weak Pull-up Register bits"
IOCA5=IOCA.5,"Interrupt-on-change PORTA Control bits"
IOCA4=IOCA.4,"Interrupt-on-change PORTA Control bits"
IOCA3=IOCA.3,"Interrupt-on-change PORTA Control bits"
IOCA2=IOCA.2,"Interrupt-on-change PORTA Control bits"
IOCA1=IOCA.1,"Interrupt-on-change PORTA Control bits"
IOCA0=IOCA.0,"Interrupt-on-change PORTA Control bits"
EEDATH="EEPROM Data Register, high byte."
EEADRH="EEPROM Address Register, high byte."
VREN=VRCON.7,"CVref Enable bit"
VRR=VRCON.5,"CVref Range selection bit"
VR3=VRCON.3,"VREF value selection"
VR2=VRCON.2,"CVref value selection 0 = VR<3:0> = 15"
VR1=VRCON.1,"CVref value selection 0 = VR<3:0> = 15"
VR0=VRCON.0,"CVref value selection 0 = VR<3:0> = 15"
EEDAT="EEPROM data register"
EEADR="EEPROM address register.<br>Specifies one of 256 locations of EEPROM Read/Write Operation"
EEPGD=EECON1.7,"Program/Data EEPROM Select bit"
WRERR=EECON1.3,"EEPROM Error Flag bit"
WREN=EECON1.2,"EEPROM Write Enable bit"
WR=EECON1.1,"Write Control bit"
RD=EECON1.0,"Read Control bit"
EECON2="EEPROM Control 2 Register (not a physical register)"
ADRESH="Most Significant 8 bits of the left shifted A/D result or 2 bits of the right shifted result"
ADRESL="Least Significant 2 bits of the left shifted result or 8 bits of the right shifted result"












