** BITNAMES **
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
TMR0="Timer0 module's register"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out bit"
NOT_PD=STATUS.3,"Power Down bit"
Z=STATUS.2,"Zero bit"
DC=STATUS.1,[protect], "Digit Carry bit"
C=STATUS.0,"Carry bit"
FSR="Indirect data memory address pointer"
RA0=PORTA.0,"Bidirectional I/O pin"
AN0=PORTA.0,"Analog Input Channel 0"
RA1=PORTA.1,"Bidirectional I/O pin"
AN1=PORTA.1,"Analog Input Channel 1"
RA2=PORTA.2,"Bidirectional I/O pin"
AN2=PORTA.2,"Analog Input Channel 2"
VREF_MINUS=PORTA.2,"A/D reference voltage (low) input"
RA3=PORTA.3,"Bidirectional I/O pin"
AN3=PORTA.3,"Analog Input Channel 3"
VREF_PLUS=PORTA.3,"A/D reference voltage (high) input"
RA4=PORTA.4,"Bidirectional I/O pin"
AN4=PORTA.4,"Analog Input Channel 4"
T0CKI=PORTA.4,"Clock input to the TMR0 timer/counter"
RA5=PORTA.5,"Bidirectional I/O pin"
NOT_MCLR=PORTA.5,"Master Clear (Reset).<br> Input/programming voltage input.<br> This pin is an active-low Reset to the device."
VPP=PORTA.5,"Programming threshold voltage"
RA6=PORTA.6,"Bidirectional I/O pin" 
OSC2=PORTA.6,"Oscillator crystal output.<br>Connects to crystal or resonator in Crystal Oscillator mode."
CLK0=PORTA.6,"In RC mode, this pin outputs CLKO signal<br> which has 1/4 the frequency of OSC1 And denotes the instruction cycle rate"
RA7=PORTA.7,"Bidirectional I/O pin" 
OSC1=PORTA.7,"Oscillator crystal input"
CLKI=PORTA.7,"External clock source input"
RB0=PORTB.0,"Bidirectional I/O pin" 
INT=PORTB.0,"External Interrupt pin"
RB1=PORTB.1,"Bidirectional I/O pin"
SDI=PORTB.1,"SPI data in"
SDA=PORTB.1,"I2C data"
RB2=PORTB.2,"Bidirectional I/O pin"
SDO=PORTB.2,"SPI data out"
CCP1=PORTB.2,"Capture input, Compare output, PWM output."
RB3=PORTB.3,"Bidirectional I/O pin"
CCP1=PORTB.3,"Capture input, Compare output, PWM output."
PGM=PORTB.3,"Low-Voltage ICSP™ Programming enable pin"
RB4=PORTB.4,"Bidirectional I/O pin"
SCK=PORTB.4,"Synchronous serial clock input/output for SPI"
SCL=PORTB.4,"Synchronous serial clock input for I2C"
RB5=PORTB.5,"Bidirectional I/O pin"
NOT_SS=PORTB.5,"Slave select for SPI in Slave mode"
RB6=PORTB.6,"Bidirectional I/O pin<br>Interrupt-on-change pin"
T1OSO=PORTB.6,"Timer1 Oscillator output"
T1CKI=PORTB.6,"Timer1 clock input"
PGC=PORTB.6,"In-circuit debugger and ICSP programming clock pin"
RB7=PORTB.7,"Bidirectional I/O pin<br>Interrupt-on-change pin"
T1OSI=PORTB.7,"Timer1 oscillator input."
PGD=PORTB.7,"In-circuit debugger and ICSP programming data pin."
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4]
GIE=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
TMR0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INTE=INTCON.4,"RB0/INT External Interrupt Enable"
RBIE=INTCON.3,"PORTB Change Interrupt Enable"
TMR0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INTF=INTCON.1,"RB0/INT External Interrupt Flag"
RBIF=INTCON.0,"PORTB Change Interrupt Flag"
ADIF=PIR1.6,"A/D Converter Interrupt Flag"
SSPIF=PIR1.3,"Synchronous Serial Port (SSP) Interrupt Flag bit"
CCP1IF=PIR1.2"CCP1 Interrupt Flag"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag bit"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag bit"
EEIF=PIR2.4,"EEPROM Write Operation Interrupt Enable bit"
TMR1L="Holding register for the Least Significant Byte of the 16 bit TMR1 register"
TMR1H="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"
TMR2="Timer2 Module Register"
TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 On bit"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"
SSPBUF="Synchronous Serial Port Receive Buffer/Transmit Register"
WCOL=SSPCON.7,"Write Collision Detect bit"
SSPOV=SSPCON.6,"Receive Overflow Indicator bit"
SSPEN=SSPCON.5,"Synchronous Serial Port Enable bit"
CKP=SSPCON.4,"Clock Polarity Select bit"
SSPM3=SSPCON.3,"Synchronous Serial Port Mode Select bits"
SSPM2=SSPCON.2,"Synchronous Serial Port Mode Select bits"
SSPM1=SSPCON.1,"Synchronous Serial Port Mode Select bits"
SSPM0=SSPCON.0,"Synchronous Serial Port Mode Select bits"
CCPR1L="Capture/Compare/PWM Register (LSB)"
CCPR1H="Capture/Compare/PWM Register (MSB)"
CCP1X=CCP1CON.5,"PWM Least Significant bits"
CCP1Y=CCP1CON.4,"PWM Least Significant bits"
CCP1M3=CCP1CON.3,"CCPx Mode Select bits"
CCP1M2=CCP1CON.2,"CCPx Mode Select bits"
CCP1M1=CCP1CON.1,"CCPx Mode Select bits"
CCP1M0=CCP1CON.0,"CCPx Mode Select bits"
ADRESH="A/D Result High Register"
ADCS1=ADCON0.7,"A/D Conversion clock Select bits"
ADCS0=ADCON0.6,"A/D Conversion clock Select bits"
CHS2=ADCON0.5,"Analog Channel Select bits"
CHS1=ADCON0.4,"Analog Channel Select bits"
CHS0=ADCON0.3,"Analog Channel Select bits"
GO=ADCON0.2,"A/D Conversion Status bit"
NOT_DONE=ADCON0.2,"A/D Conversion Status bit"
ADON=ADCON0.0,"A/D On bit"
NOT_RBPU=OPTION_REG.07,"PORTB Pull-up Enable bit"
INTEDG=OPTION_REG.6,"Interrupt Edge Select bit"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select bit"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select bit"
PSA=OPTION_REG.3,"Prescaler Assignment bit"
PS2=OPTION_REG.2,"Prescaler Rate Select bits"
PS1=OPTION_REG.1,"Prescaler Rate Select bits"
PS0=OPTION_REG.0,"Prescaler Rate Select bits"
TRISA="PORTA data direction register"
TRISB="PORTB Data direction register"
ADIE=PIE1.6,"A/D Converter Interrupt Enable"
SSPIE=PIE1.3,"Synchronous Serial Port Interrupt Enable bit"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable bit"
TMR1IE=PIE1.0,"Timer1 Overflow Interrupt Enable"
EEIE=PIE2.4,"EEPROM Write Operation Interrupt Enable bit"
NOT_POR=PCON.1,"Power-on Reset Status bit"
NOT_BOR=PCON.0,"Brown-out Reset Status bit"
IRCF2=OSCON.6,"Internal Oscillator Frequency Select bits"
IRCF1=OSCON.5,"Internal Oscillator Frequency Select bits"
IRCF0=OSCON.4,"Internal Oscillator Frequency Select bits"
IOFS=OSCON.2,"INTOSC Frequency Stable bit"
TUN5=OSCTUNE.5,"Frequency Tuning bits"
TUN4=OSCTUNE.4,"Frequency Tuning bits"
TUN3=OSCTUNE.3,"Frequency Tuning bits"
TUN2=OSCTUNE.2,"Frequency Tuning bits"
TUN1=OSCTUNE.1,"Frequency Tuning bits"
TUN0=OSCTUNE.0,"Frequency Tuning bits"
PR2="Timer2 Period Register"
SSPADD="Synchronous Serial Port (I2C mode) Address Register"
SMP=SSPSTAT.7,"SPI Data Input Sample Phase bits"
CKE=SSPSTAT.6,"SPI Clock Edge Select bits "
NOT_DA=SSPSTAT.5,"Data/Address bit (I2C mode only)"
P=SSPSTAT.4,"STOP bit (I C mode only)<br>This bit is cleared when the SSP module is disabled,<br> or when the START bit is detected last.<br> SSPEN is cleared."
S=SSPSTAT.3,"START bit (I C mode only)<br>This bit is cleared when the SSP module is disabled<br> or when the STOP bit is detected last.<br> SSPEN is cleared."
NOT_RW=SSPSTAT.2,"Read/Write Information bit<br> (I2C mode only)<br>This bit holds the R/W bit information following the last address match.<br> This bit is only valid from the address match to the next START bit,STOP bit, or ACK bit."
UA=SSPSTAT.1,"Update Address bit (10-bit I2C mode only)"
BF=SSPSTAT.0,"Buffer Full Status bit"
ADRES="A/D Result Register"
ADRESL="A/D Result Register Low Byte"
ADFM=ADCON1.7,"A/D Result Format Select bit"
ADCS2=ADCON1.6,"A/D Clock Divide by 2 Select bit"
PCFG3=ADCON1.3,"A/D Port Configuration Control bits"
PCFG2=ADCON1.2,"A/D Port Configuration Control bits"
PCFG1=ADCON1.1,"A/D Port Configuration Control bits"
PCFG0=ADCON1.0,"A/D Port Configuration Control bits"
EEDATA="EEPROM/Flash Data Register Low Byte"
EEADR="EEPROM/Flash Address Register Low Byte"
EEDATH="EEPROM/Flash Data Register High Byte"
EEADRH="EEPROM/Flash Address Register High Byte"
EEPGD=EECON1.7,"Program/Data EEPROM Select bit"
FREE=EECON1.4,"EEPROM Forced Row Erase bit"
WRERR=EECON1.3,"EEPROM Error Flag bit"
WREN=EECON1.2,"EEPROM Write Enable bit"
WR=EECON1.1,"Write Control bit"
RD=EECON1.0,"Read Control bit"
EECON2="EEPROM Control 2 Register (not a physical register)"
IRCF2=OSCCON.6," Internal Oscillator Frequency Select bits"
IRCF1=OSCCON.5," Internal Oscillator Frequency Select bits"
IRCF0=OSCCON.4," Internal Oscillator Frequency Select bits"
IOFS=OSCCON.2," INTOSC Frequency Stable bit"
TMR1="16-bit Timer 1 Module Register"



