** BITNAMES **
TMR0="Timer0 module's register"
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"
FSR="Indirect data memory address pointer"
RA0=PORTA.0,"Bi-directional I/O pin"
AN0=PORTA.0,"Analog input 0 pin"
RA1=PORTA.1,"Bi-directional I/O pin"
AN1=PORTA.1,"Analog input 1 pin"
RA2=PORTA.2,"Bi-directional I/O pin"
AN2=PORTA.2,"Analog input 2 pin"
VREF_MINUS=PORTA.2,"Negative Analog reference voltage"
RA3=PORTA.3,"Bi-directional I/O pin"
AN3=PORTA.3,"Analog input 3 pin"
VREF_PLUS=PORTA.3,"Positive Analog reference voltage reference pin"
RA4=PORTA.4,"Bi-directional I/O<br>Output is open drain type"
T0CK1=PORTA.4,"External clock input for Timer0"
RA5=PORTA.5,"Bi-directional I/O pin"
AN4=PORTA.5,"Analog input 4 pin"
NOT_SS=PORTA.5,"Slave Select for the Synchronous Serial Port."
RB0=PORTB.0,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
INT=PORTB.0,"External interrupt input"
RB1=PORTB.1,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB2=PORTB.2,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB3=PORTB.3,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
PGM=PORTB.3,"Low voltage ICSP programming enable pin"
RB4=PORTB.4,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
RB5=PORTB.5,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
RB6=PORTB.6,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
PGC=PORTB.6,"In-Circuit Debugger and ICSP programming clock."
RB7=PORTB.7,"Input/output pin (with interrupt on change)<br>Internal software programmable weak pull-up"
PGD=PORTB.7,"In-Circuit Debugger and ICSP programming data"
RC0=PORTC.0,"Bi-directional I/O pin"
T1OSO=PORTC.0,"Timer1 oscillator output"
T1CKI=PORTC.0,"Timer1 clock input"
RC1=PORTC.1,"Bi-directional I/O pin"
T1OSI=PORTC.1,"Timer1 oscillator input<br>Capture2 input"
RC2=PORTC.2,"Bi-directional I/O pin"
CCP1=PORTC.2,"Capture1 input<br>Compare1 output<br>PWM1 output"
RC3=PORTC.3,"Bi-directional I/O pin"
SCK=PORTC.3,"Synchronous serial clock input/output for SPI mode"
SCL=PORTC.3,"Synchronous serial clock input/output for I2C mode"
RC4=PORTC.4,"Bi-directional I/O pin"
SDI=PORTC.4,"SPI Data In pin (SPI mode)"
SDA=PORTC.4,"SPI Data I/O pin (I C mode)"
RC5=PORTC.5,"Bi-directional I/O pin"
SDO=PORTC.5,"SPI Data Out pin (SPI mode)"
RC6=PORTC.6,"Bi-directional I/O pin"
RC7=PORTC.7,"Bi-directional I/O pin"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4] 
GIE=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
TMR0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INTE=INTCON.4,"RB0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
TMR0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INTF=INTCON.1,"RB0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"
reserved=PIR1.7,"Always maintain these bit clear"
ADIF=PIR1.6,"A/D Converter Interrupt Flag"
reserved=PIR1.5,"Always maintain these Bit Clear"
reserved=PIR1.4,"Always maintain these Bit Clear"
SSPIF=PIR1.3,"Synchronous Serial Port (SSP) Interrupt Flag"
CCP1IF=PIR1.2,"CCP1 Interrupt Flag"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag"
reserved=PIR2.6,"Always maintain this Bit Clear"
EEIF=PIR2.4,"EEPROM Write Operation Interrupt Flag bit"
BCLIF=PIR2.3,"Bus Collision Interrupt Flag bit"
reserved=PIR2.0,"Always maintain this Bit Clear"
TMR1L="Holding register for the Least Significant Byte of the 16 bit TMR1 register"
TMR1LH="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
TMR1H="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"
TMR2="Timer2 module's register"
TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 ON"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"
SSPBUF="Synchronous Serial Port Receive Buffer/Transmit Register"
WCOL=SSPCON.7,"Write Collision Detect bit"
SSPOV=SSPCON.6,"Receive Overflow Indicator bit"
SSPEN=SSPCON.5,"Synchronous Serial Port Enable bit"
CKP=SSPCON.4,"Clock Polarity Select bit"
SSPM3=SSPCON.3,"Synchronous Serial Port Mode Select bits"
SSPM2=SSPCON.2,"Synchronous Serial Port Mode Select bits"
SSPM1=SSPCON.1,"Synchronous Serial Port Mode Select bits"
SSPM0=SSPCON.0,"Synchronous Serial Port Mode Select bits"
CCPR1L="Capture/Compare/PWM Register (LSB)"
CCPR1H="Capture/Compare/PWM Register (MSB)"
CCP1X=CCP1CON.5,"PWM Least Significant bits"
CCP1Y=CCP1CON.4,"PWM Least Significant bits"
CCP1M3=CCP1CON.3,"CCPx Mode Select bits"
CCP1M2=CCP1CON.2,"CCPx Mode Select bits"
CCP1M1=CCP1CON.1,"CCPx Mode Select bits"
CCP1M0=CCP1CON.0,"CCPx Mode Select bits"
ADRESH="A/D Result High Register"
ADCS1=ADCON0.7,"A/D Conversion clock Select bits"
ADCS0=ADCON0.6,"A/D Conversion clock Select bits"
CHS2=ADCON0.5,"Analog Channel Select bits"
CHS1=ADCON0.4,"Analog Channel Select bits"
CHS0=ADCON0.3,"Analog Channel Select bits"
GO=ADCON0.2,"A/D Conversion Status bit"
NOT_DONE=ADCON0.2,"A/D Conversion Status bit"
ADON=ADCON0.0,"A/D On bit"
NOT_RBPU=OPTION_REG.07,"PORTB Pull-up Enable bit"
INTEDG=OPTION_REG.6,"Interrupt Edge Select bit"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select bit"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select bit"
PSA=OPTION_REG.3,"Prescaler Assignment bit"
PS2=OPTION_REG.2,"Prescaler Rate Select bits"
PS1=OPTION_REG.1,"Prescaler Rate Select bits"
PS0=OPTION_REG.0,"Prescaler Rate Select bits"
TRISA="PORTA data direction register"
TRISB="PORTB data direction register"
TRISC="PORTC data direction register"
reserved=PIE1.7,"Always maintain this Bit Clear"
ADIE=PIE1.6,"A/D Converter Interrupt Enable"
reserved=PIE1.5,"Always maintain this Bit Clear"
reserved=PIE1.4,"Always maintain this Bit Clear"
SSPIE=PIE1.3,"Synchronous Serial Port Interrupt Enable bit"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable bit"
TMR1IE=PIE1.0,"Timer1 Overflow Interrupt Enable"
reserved=PIE2.6,"Always maintain this Bit Clear"
EEIE=PIE2.4,"EEPROM Write Operation Interrupt Enable bit"
BCLIE=PIE2.3,"Bus Collision Interrupt Enable bit"
reserved=PIE2.0,"Always maintain this Bit Clear"
NOT_POR=PCON.1,"Power-on Reset Status bit"
NOT_BOR=PCON.0,"Brown-out Reset Status bit"
GCEN=SSPCON2.7,"General Call Enable bit (In I2C Slave mode only)"
ACKSTAT=SSPCON2.6,"Acknowledge Status bit (In I2C Master mode only)"
ACKDT=SSPCON2.5,"Acknowledge Data bit (In I2C Master mode only)"
ACKEN=SSPCON2.4,"Acknowledge Sequence Enable bit (In I2C Master mode only)"
RCEN=SSPCON2.3,"Receive Enable bit (In I2C Master mode only)"
PEN=SSPCON2.2,"STOP Condition Enable bit (In I2C Master mode only)"
RSEN=SSPCON2.1,"Repeated START Condition Enabled bit (In I2C Master mode only)"
SEN=SSPCON2.0,"START Condition Enabled bit (In I2C Master mode only)"
PR2="Timer2 Period Register"
SSPADD="Synchronous Serial Port (I2C mode) Address Register"
SMP=SSPSTAT.7,"SPI Data Input Sample Phase bits"
CKE=SSPSTAT.6,"SPI Clock Edge Select bits "
NOT_DA=SSPSTAT.5,"Data/Address bit (I2C mode only)"
P=SSPSTAT.4,"STOP bit (I C mode only)<br>This bit is cleared when the SSP module is disabled,<br> or when the START bit is detected last.<br> SSPEN is cleared."
S=SSPSTAT.3,"START bit (I C mode only)<br>This bit is cleared when the SSP module is disabled<br> or when the STOP bit is detected last.<br> SSPEN is cleared."
NOT_RW=SSPSTAT.2,"Read/Write Information bit<br> (I2C mode only)<br>This bit holds the R/W bit information following the last address match.<br> This bit is only valid from the address match to the next START bit,STOP bit, or ACK bit."
UA=SSPSTAT.1,"Update Address bit (10-bit I2C mode only)"
BF=SSPSTAT.0,"Buffer Full Status bit"
ADRES="A/D Result Register"
ADRESL="A/D Result Register Low Byte"
ADFM=ADCON1.7,"A/D Result Format Select bit"
PCFG3=ADCON1.3,"A/D Port Configuration Control bits"
PCFG2=ADCON1.2,"A/D Port Configuration Control bits"
PCFG1=ADCON1.1,"A/D Port Configuration Control bits"
PCFG0=ADCON1.0,"A/D Port Configuration Control bits"
EEDATA="EEPROM data register"
EEADR="EEPROM address register"
EEDATH="EEPROM data register high byte"
EEADRH="EEPROM address register high byte"
EEPGD=EECON1.7,"Program / Data EEPROM Select bit"
WRERR=EECON1.3,"EEPROM Error Flag"
WREN=EECON1.2,"EEPROM Write/Enable"
WR=EECON1.1,"Write Control"
RD=EECON1.0,"Read Control"
EECON2="EEPROM control register2 (not a physical register)"






























