** BITNAMES **
FLT4EN=DFLTCON.6,"Noise Filter Output Enable bit, T5CKI input"
FLT3EN=DFLTCON.5,"Noise Filter Output Enable bit, CAP3/QEB input"
FLT2EN=DFLTCON.4,"Noise Filter Output Enable bit, CAP2/QEA input"
FLT1EN=DFLTCON.3,"Noise Filter Output Enable bit, CAP1/INDX input"
FLTCK2=DFLTCON.2,"Noise Filter Clock Divider Ratio bits"
FLTCK1=DFLTCON.1,"Noise Filter Clock Divider Ratio bits"
FLTCK0=DFLTCON.0,"Noise Filter Clock Divider Ratio bits"

CAP3REN=CAP3CON.6,"Time Base Reset Enable bit"
CAP3M3=CAP3CON.3,"Input Capture 1 (ICx) Mode Select bits"
CAP3M2=CAP3CON.2,"Input Capture 1 (ICx) Mode Select bits"
CAP3M1=CAP3CON.1,"Input Capture 1 (ICx) Mode Select bits"
CAP3M0=CAP3CON.0,"Input Capture 1 (ICx) Mode Select bits"

CAP2REN=CAP2CON.6,"Time Base Reset Enable bit"
CAP2M3=CAP2CON.3,"Input Capture 1 (ICx) Mode Select bits"
CAP2M2=CAP2CON.2,"Input Capture 1 (ICx) Mode Select bits"
CAP2M1=CAP2CON.1,"Input Capture 1 (ICx) Mode Select bits"
CAP2M0=CAP2CON.0,"Input Capture 1 (ICx) Mode Select bits"

CAP1REN=CAP1CON.6,"Time Base Reset Enable bit"
CAP1M3=CAP1CON.3,"Input Capture 1 (ICx) Mode Select bits"
CAP1M2=CAP1CON.2,"Input Capture 1 (ICx) Mode Select bits"
CAP1M1=CAP1CON.1,"Input Capture 1 (ICx) Mode Select bits"
CAP1M0=CAP1CON.0,"Input Capture 1 (ICx) Mode Select bits"

CAP3BUFL="Capture 3 Register, Low Byte"
MAXCNTL="QEI Max. Count Limit Register, Low Byte"
CAP3BUFH="Capture 3 Register, High Byte"
MAXCNTH="QEI Max. Count Limit Register, High Byte"
CAP2BUFL="Capture 2 Register, Low Byte"
POSCNTL="QEI Position Counter Register, Low Byte"
CAP2BUFH="Capture 2 Register, High Byte"
POSCNTH="QEI Position Counter Register, High Byte"
CAP1BUFL="Capture 1 Register, Low Byte"
VELRL="Velocity Register, Low Byte"
CAP1BUFH="Capture 1 Register, High Byte"
VELRH="Velocity Register, High Byte"

'POUT7=OVDCONS.7,"PWM Manual Output bits"
'POUT6=OVDCONS.6,"PWM Manual Output bits"
POUT5=OVDCONS.5,"PWM Manual Output bits"
POUT4=OVDCONS.4,"PWM Manual Output bits"
POUT3=OVDCONS.3,"PWM Manual Output bits"
POUT2=OVDCONS.2,"PWM Manual Output bits"
POUT1=OVDCONS.1,"PWM Manual Output bits"
POUT0=OVDCONS.0,"PWM Manual Output bits"

'POVD7=OVDCOND.7,"PWM Output Override bits"
'POVD6=OVDCOND.6,"PWM Output Override bits"
POVD5=OVDCOND.5,"PWM Output Override bits"
POVD4=OVDCOND.4,"PWM Output Override bits"
POVD3=OVDCOND.3,"PWM Output Override bits"
POVD2=OVDCOND.2,"PWM Output Override bits"
POVD1=OVDCOND.1,"PWM Output Override bits"
POVD0=OVDCOND.0,"PWM Output Override bits"

BRFEN=FLTCONFIG.7,"Breakpoint Fault Enable bit"
'FLTBS=FLTCONFIG.6,"Fault B Status bit"
'FLTBMOD=FLTCONFIG.5,"Fault B Mode bit"
'FLTBEN=FLTCONFIG.4,"Fault B Enable bit"
FLTCON=FLTCONFIG.3,"Fault Configuration bit"
FLTAS=FLTCONFIG.2,"Fault A Status bit"
FLTAMOD=FLTCONFIG.1,"Fault A Mode bit"
FLTAEN=FLTCONFIG.0,"Fault A Enable bit"

DTPS1=DTCON.7,"Dead Time Unit A Prescale Select bits"
DTPS0=DTCON.6,"Dead Time Unit A Prescale Select bits"
DT5=DTCON.5,"<DT5:DT0> Unsigned 6-bit dead time value bits for Dead Time Unit"
DT4=DTCON.4,"<DT5:DT0> Unsigned 6-bit dead time value bits for Dead Time Unit"
DT3=DTCON.3,"<DT5:DT0> Unsigned 6-bit dead time value bits for Dead Time Unit"
DT2=DTCON.2,"<DT5:DT0> Unsigned 6-bit dead time value bits for Dead Time Unit"
DT1=DTCON.1,"<DT5:DT0> Unsigned 6-bit dead time value bits for Dead Time Unit"
DT0=DTCON.0,"<DT5:DT0> Unsigned 6-bit dead time value bits for Dead Time Unit"

SEVOPS3=PWMCON1.7,"PWM Special Event Trigger Output Postscale Select bits"
SEVOPS2=PWMCON1.6,"PWM Special Event Trigger Output Postscale Select bits"
SEVOPS1=PWMCON1.5,"PWM Special Event Trigger Output Postscale Select bits"
SEVOPS0=PWMCON1.4,"PWM Special Event Trigger Output Postscale Select bits"
SEVTDIR=PWMCON1.3,"Special Event Trigger Time Base Direction bit"
UDIS=PWMCON1.1,"PWM Update Disable bit"
OSYNC=PWMCON1.0,"PWM Output Override Synchronization bit"

PWMEN2=PWMCON0.6,"PWM Module Enable bits"
PWMEN1=PWMCON0.5,"PWM Module Enable bits"
PWMEN0=PWMCON0.4,"PWM Module Enable bits"
PMOD3=PWMCON0.3,"PWM Output Pair Mode bits"
PMOD2=PWMCON0.2,"PWM Output Pair Mode bits"
PMOD1=PWMCON0.1,"PWM Output Pair Mode bits"
PMOD0=PWMCON0.0,"PWM Output Pair Mode bits"

SEVTCMPL="PWM Special Event Compare (lower 8 bits)"
SEVTCMPH="PWM Special Event Compare (upper 4 bits)"

'PDC3H="PWM Duty Cycle #3H register (Upper 6 bits)"
'PDC3L="PWM Duty Cycle #3L register (Lower 8 bits)"
PDC2H="PWM Duty Cycle #2H register (Upper 6 bits)"
PDC2L="PWM Duty Cycle #2L register (Lower 8 bits)"
PDC1H="PWM Duty Cycle #1H register (upper 6 bits)"
PDC1L="PWM Duty Cycle #1L register (lower 8 bits)"
PDC0H="PWM Duty Cycle #0H register (upper 6 bits)"
PDC0L="PWM Duty Cycle #0L register (lower 8 bits)"

PTPERH="PWM Time Base Period register (Upper 4 bits)"
PTPERL="PWM Time Base Period register (Lower 8 bits)"
PTMRH="PWM Time Base (upper 4 bits)"
PTMRL="PWM Time Base (lower 8 bits)"

PTEN=PTCON1.7,"PWM Time Base Timer Enable bit"
PTDIR=PTCON1.6,"PWM Time Base Count Direction Status bit"

PTOPS3=PTCON0.7,"PWM Time Base Output Postscale Select bits"
PTOPS2=PTCON0.6,"PWM Time Base Output Postscale Select bits"
PTOPS1=PTCON0.5,"PWM Time Base Output Postscale Select bits"
PTOPS0=PTCON0.4,"PWM Time Base Output Postscale Select bits"
PTCKPS1=PTCON0.3,"PWM Time Base Input Clock Prescale Select bits"
PTCKPS0=PTCON0.2,"PWM Time Base Input Clock Prescale Select bits"
PTMOD1=PTCON0.1,"PWM Time Base Mode Select bits"
PTMOD0=PTCON0.0,"PWM Time Base Mode Select bits"

NOT_MCLR=PORTE.3,"Master Clear (Reset) input"
VPP=PORTE.3,"High-voltage ICSP programming enable pin"
RE3=PORTE.3,"Digital input. Available only when MCLR is disabled"

RA0=PORTA.0,"Bidirectional Digital I/O"
AN0=PORTA.0,"Analog input 0"
RA1=PORTA.1,"Bidirectional Digital I/O"
AN1=PORTA.1,"Analog input 1"
RA2=PORTA.2,"Bidirectional Digital I/O"
AN2=PORTA.2,"Analog input 2"
VREF_MINUS=PORTA.2,"A/D Reference Voltage (Low) input"
CAP1=PORTA.2,"Input capture pin 1"
INDX=PORTA.2,"Quadrature Encoder Interface index input pin"
RA3=PORTA.3,"Bidirectional Digital I/O"
AN3=PORTA.3,"Analog input 3"
VREF_PLUS=PORTA.3,"A/D Reference Voltage (High) input"
CAP2=PORTA.3,"Input capture pin 2"
QEA=PORTA.3,"Quadrature Encoder Interface channel A input pin"
RA4=PORTA.4,"Bidirectional Digital I/O"
AN4=PORTA.4,"Analog input 4"
CAP3=PORTA.4,"Input capture pin 3"
QEB=PORTA.4,"Quadrature Encoder Interface channel B input pin"
RA6=PORTA.6,"General purpose I/O pin"
CLKO=PORTA.6,"In RC mode, OSC2 pin outputs CLKO, which has 1/4 the <br>frequency of OSC1 and denotes the instruction cycle rate"
OSC2=PORTA.6,"Oscillator crystal output. Connects to crystal or resonator <br>in Crystal Oscillator mode"
RA7=PORTA.7,"General purpose I/O pin"
CLKI=PORTA.7,"External clock source input. Always associated with pin <br>function OSC1. (See related OSC1/CLKI, OSC2/CLKO pins.)"
OSC1=PORTA.7,"Oscillator crystal input or external clock source input. <br>ST buffer when configured in RC mode, CMOS otherwise"

RB0=PORTB.0,"Bidirectional Digital I/O"
PWM0=PORTB.0,"PWM output 0"
RB1=PORTB.1,"Bidirectional Digital I/O"
PWM1=PORTB.1,"PWM output 1"
RB2=PORTB.2,"Bidirectional Digital I/O"
PWM2=PORTB.2,"PWM output 2"
RB3=PORTB.3,"Bidirectional Digital I/O"
PWM3=PORTB.3,"PWM output 3"
RB4=PORTB.4,"Bidirectional Digital I/O"
KBI0=PORTB.4,"Interrupt-on-change pin"
PWM5=PORTB.4,"PWM output 5"
RB5=PORTB.5,"Bidirectional Digital I/O"
KBI1=PORTB.5,"Interrupt-on-change pin"
PWM4=PORTB.5,"PWM output 4"
PGM=PORTB.5,"Low-voltage ICSP programming entry pin"
RB6=PORTB.6,"Bidirectional Digital I/O"
KBI2=PORTB.6,"Interrupt-on-change pin"
PGC=PORTB.6,"In-Circuit Debugger and ICSP programming clock pin"
RB7=PORTB.7,"Bidirectional Digital I/O"
KBI3=PORTB.7,"Interrupt-on-change pin"
PGD=PORTB.7,"In-Circuit Debugger and ICSP programming data pin"

RC0=PORTC.0,"Bidirectional Digital I/O"
T1OSO=PORTC.0,"Timer1 oscillator output"
T1CKI=PORTC.0,"Timer1 external clock input"
RC1=PORTC.1,"Bidirectional Digital I/O"
T1OSI=PORTC.1,"Timer1 oscillator input"
CCP2=PORTC.1,"Capture2 input, Compare2 output, PWM2 output"
NOT_FLTA=PORTC.1,"Fault interrupt input pin"
RC2=PORTC.2,"Bidirectional Digital I/O"
CCP1=PORTC.2,"Capture1 input/Compare1 output/PWM1 output"
NOT_FLTB=PORTC.2,"Fault interrupt input pin"
RC3=PORTC.3,"Bidirectional Digital I/O"
T0CKI=PORTC.3,"Timer0 alternate clock input"
T5CKI=PORTC.3,"Timer5 alternate clock input"
INT0=PORTC.3,"External interrupt 0"
RC4=PORTC.4,"Bidirectional Digital I/O"
INT1=PORTC.4,"External interrupt 1"
SDI=PORTC.4,"SPI™ data in"
SDA=PORTC.4,"I2C™ data I/O"
RC5=PORTC.5,"Bidirectional Digital I/O"
INT2=PORTC.5,"External interrupt 2"
SCK=PORTC.5,"Synchronous serial clock input/output for SPI mode"
SCL=PORTC.5,"Synchronous serial clock input/output for I2C mode"
RC6=PORTC.6,"Bidirectional Digital I/O"
TX=PORTC.6,"USART Asynchronous Transmit"
CK=PORTC.6,"USART Synchronous Clock (see related RX/DT)"
NOT_SS=PORTC.6,"SPI Slave Select input"
RC7=PORTC.7,"Bidirectional Digital I/O"
RX=PORTC.7,"USART Asynchronous Receive"
DT=PORTC.7,"USART Synchronous Data (see related TX/CK)"
SDO=PORTC.7,"SPI data out"

TMR5H="Timer5 Timer register High Byte"
TMR5L="Timer5 Timer register Low Byte"
LATC="Read PORTC Data Latch, Write PORTC Data Latch"
LATB="Read PORTB Data Latch, Write PORTB Data Latch"
LATA="Read PORTA Data Latch, Write PORTA Data Latch",[0..6]
PR5L="Timer5 Period Register Low Byte"
PR5H="Timer5 Period Register High Byte"

TRISA="Data Direction Control Register for PORTA"
TRISB="Data Direction Control Register for PORTB"
TRISC="Data Direction Control Register for PORTC"

GDSEL1=ADCHS.7,"Group D Select bits"
GDSEL0=ADCHS.6,"Group D Select bits"
GBSEL1=ADCHS.5,"Group B Select bits"
GBSEL0=ADCHS.4,"Group B Select bits"
GCSEL1=ADCHS.3,"Group C Select bits"
GCSEL0=ADCHS.2,"Group C Select bits"
GASEL1=ADCHS.1,"Group A Select bits"
GASEL0=ADCHS.0,"Group A Select bits"

ADRS1=ADCON3.7,"A/D Result Buffer Depth Interrupt Select Control bits for Continuous Loop mode"
ADRS0=ADCON3.6,"A/D Result Buffer Depth Interrupt Select Control bits for Continuous Loop mode"
SSRC4=ADCON3.4,"A/D Trigger Source Select bits"
SSRC3=ADCON3.3,"A/D Trigger Source Select bits"
SSRC2=ADCON3.2,"A/D Trigger Source Select bits"
SSRC1=ADCON3.1,"A/D Trigger Source Select bits"
SSRC0=ADCON3.0,"A/D Trigger Source Select bits"

TUN5=OSCTUNE.5,"Frequency Tuning bits"
TUN4=OSCTUNE.4,"Frequency Tuning bits"
TUN3=OSCTUNE.3,"Frequency Tuning bits"
TUN2=OSCTUNE.2,"Frequency Tuning bits"
TUN1=OSCTUNE.1,"Frequency Tuning bits"
TUN0=OSCTUNE.0,"Frequency Tuning bits"

ADIE=PIE1.6,"A/D Converter Interrupt Enable bit"
RCIE=PIE1.5,"USART Receive Interrupt Enable bit"
TXIE=PIE1.4,"USART Transmit Interrupt Enable bit"
SSPIE=PIE1.3,"Master Synchronous Serial Port Interrupt Enable bit"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable bit"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable bit"
TMR1IE=PIE1.0,"TMR1 Overflow Interrupt Enable bit"

ADIF=PIR1.6,"A/D Converter Interrupt Flag bit"
RCIF=PIR1.5,"USART Receive Interrupt Flag bit"
TXIF=PIR1.4,"USART Transmit Interrupt Flag bit"
SSPIF=PIR1.3,"Master Synchronous Serial Port Interrupt Flag bit"
CCP1IF=PIR1.2,"CCP1 Interrupt Flag bit"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag bit"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag bit"

ADIP=IPR1.6,"A/D Converter Interrupt Priority bit"
RCIP=IPR1.5,"USART Receive Interrupt Priority bit"
TXIP=IPR1.4,"USART Transmit Interrupt Priority bit"
SSPIP=IPR1.3,"Master Synchronous Serial Port Interrupt Priority bit"
CCP1IP=IPR1.2,"CCP1 Interrupt Priority bit"
TMR2IP=IPR1.1,"TMR2 to PR2 Match Interrupt Priority bit"
TMR1IP=IPR1.0,"TMR1 Overflow Interrupt Priority bit"

OSFIE=PIE2.7,"Oscillator Fail Interrupt Enable bit"
EEIE=PIE2.4,"EEPROM/FLASH Write Operation Interrupt Enable bit"
LVDIE=PIE2.2,"Low Voltage Detect Interrupt Enable bit"
CCP2IE=PIE2.0,"CCP2 Interrupt Enable bit"

OSFIF=PIR2.7,"Oscillator Fail Interrupt Flag bit"
EEIF=PIR2.4,"EEPROM/FLASH Write Operation Interrupt Flag bit"
LVDIF=PIR2.2,"Low Voltage Detect Interrupt Flag bit"
CCP2IF=PIR2.0,"CCP2 Interrupt Flag bit"

OSFIP=IPR2.7,"Oscillator Fail Interrupt Priority bit"
EEIP=IPR2.4,"Data EEPROM/FLASH Write Operation Interrupt Priority bit"
LVDIP=IPR2.2,"Low Voltage Detect Interrupt Priority bit"
CCP2IP=IPR2.0,"CCP2 Interrupt Priority bit"

PTIE=PIE3.4,"PWM Time Base Interrupt Enable bit"
IC3DRIE=PIE3.3,"IC3 Interrupt Enable/Direction Change Interrupt Enable bit"
IC2QEIE=PIE3.2,"IC2 Interrupt Flag/QEI Interrupt Flag Enable bit"
IC1IE=PIE3.1,"IC1 Interrupt Enable bit"
TMR5IE=PIE3.0,"Timer5 Interrupt Enable bit"

PTIF=PIR3.4,"PWM Time Base Interrupt bit"
IC3DRIF=PIR3.3,"IC3 Interrupt Flag/Direction Change Interrupt Flag bit"
IC2QEIF=PIR3.2,"IC2 Interrupt Flag/QEI Interrupt Flag bit"
IC1IF=PIR3.1,"IC1 Interrupt Flag bit"
TMR5IF=PIR3.0,"Timer5 Interrupt Flag bit"

PTIP=IPR3.4,"PWM Time Base Interrupt Priority bit"
IC3DRIP=IPR3.3,"IC3 Interrupt Priority/Direction Change Interrupt Priority bit"
IC2QEIP=IPR3.2,"IC2 Interrupt Priority/QEI Interrupt Priority bit"
IC1IP=IPR3.1,"IC1 Interrupt Priority bit"
TMR5IP=IPR3.0,"Timer5 Interrupt Priority bit"

EEPGD=EECON1.7,"FLASH Program or Data EEPROM Memory Select bit"
CFGS=EECON1.6,"FLASH Program/Data EEPROM or Configuration Select bit"
FREE=EECON1.4,"FLASH Row Erase Enable bit"
WRERR=EECON1.3,"EEPROM Error Flag"
WREN=EECON1.2,"EEPROM Write/Enable"
WR=EECON1.1,"Write Control"
RD=EECON1.0,"Read Control"

EECON2="EEPROM control register2 (not a physical register)"
EEADR="Data EEPROM Address Register"
EEDATA="Data EEPROM Data Register"

RCIDL=BAUDCTL.6,"Receive Operation Idle Status bit"
SCKP=BAUDCTL.4,"Synchronous Clock Polarity Select bit"
BRG16=BAUDCTL.3,"16-bit Baud Rate Register Enable bit"
WUE=BAUDCTL.1,"Wake-up Enable bit"
ABDEN=BAUDCTL.0,"Auto-Baud Detect Enable bit"

SPEN=RCSTA.7,"Serial Port Enable (Usart 1)"
RX9=RCSTA.6,"9-bit Receive Enable (Usart 1)"
SREN=RCSTA.5,"Single Receive Enable (Usart 1)"
CREN=RCSTA.4,"Continuous Receive Enable (Usart 1)"
ADDEN=RCSTA.3,"Address Detect Enable (Usart 1)"
FERR=RCSTA.2,"Framing Error (Usart 1)"
OERR=RCSTA.1,"Overrun Error (Usart 1)"
RX9D=RCSTA.0,"9th bit of received data (Can be parity bit) (Usart 1)"

CSRC=TXSTA.7,"Clock Source Select bit (Usart 1)"
TX9=TXSTA.6,"9-bit Transmit Enable (Usart 1)"
TXEN=TXSTA.5,"Transmit Enable (Usart 1)"
SENDB=TXSTA.3,"Send Break Character bit"
SYNC=TXSTA.4,"USART Mode Select bit (Usart 1)"
BRGH=TXSTA.2,"High Baud Rate Select bit (Usart 1)"
TRMT=TXSTA.1,"Transmit Shift Register Status flag (Usart 1)"
TX9D=TXSTA.0,"9th bit of transmit data. Can be parity bit. (Usart 1)"

TXREG="USART Transmit Register"
SPBRG="Baud Rate Generator Register, Low Byte"
SPBRGH="Baud Rate Generator Register, High Byte"
RCREG="USART Receive Register"

NOT_VELM=QEICON.7,"Velocity Mode bit"
ERROR=QEICON.6,"QEI error bit"
UP=QEICON.5,"Direction of Rotation Status bit"
NOT_DOWN=QEICON.5,"Direction of Rotation Status bit"
QEIM2=QEICON.4,"QEI Mode bits"
QEIM1=QEICON.3,"QEI Mode bits"
QEIM0=QEICON.2,"QEI Mode bits"
PDEC1=QEICON.1,"Velocity Pulse Reduction Ratio bit"
PDEC0=QEICON.0,"Velocity Pulse Reduction Ratio bit"

T5SEN=T5CON.7,"Timer5 Sleep Enable bit"
NOT_RESEN=T5CON.6,"Special Event Reset Enable bit"
T5MOD=T5CON.6,"Timer5 Mode bit"
T5PS1=T5CON.4,"Timer5 Input Clock Prescale Select bits"
T5PS0=T5CON.3,"Timer5 Input Clock Prescale Select bits"
NOT_T5SYNC=T5CON.2,"Timer5 External Clock Input Synchronization Select bit"
TMR5CS=T5CON.1,"Timer5 Clock Source Select bit"
TMR5ON=T5CON.0,"Timer5 On bit"

'ANS7=ANSEL0.7,"Analog Input Function Select bits"
'ANS6=ANSEL0.6,"Analog Input Function Select bits"
'ANS5=ANSEL0.5,"Analog Input Function Select bits"
ANS4=ANSEL0.4,"Analog Input Function Select bits"
ANS3=ANSEL0.3,"Analog Input Function Select bits"
ANS2=ANSEL0.2,"Analog Input Function Select bits"
ANS1=ANSEL0.1,"Analog Input Function Select bits"
ANS0=ANSEL0.0,"Analog Input Function Select bits"

'ANS8=ANSEL1.0,"Analog Input Function Select bits"
'bit8=ANSEL1.0

DC2B1=CCP2CON.5,"PWM2 Least Significant bits"
DC2B0=CCP2CON.4,"PWM2 Least Significant bits"
CCP2M3=CCP2CON.3,"CCP2 Mode Select"
CCP2M2=CCP2CON.2,"CCP2 Mode Select"
CCP2M1=CCP2CON.1,"CCP2 Mode Select"
CCP2M0=CCP2CON.0,"CCP2 Mode Select"

CCPR2H="Capture/Compare/PWM register2 (MSB)"
CCPR2L="Capture/Compare/PWM register2 (LSB)"
CCPR2="Capture/Compare/PWM register"

DC1B1=CCP1CON.5,"PWM1 Least Significant bits"
DC1B0=CCP1CON.4,"PWM1 Least Significant bits"
CCP1M3=CCP1CON.3,"CCP1 Mode Select"
CCP1M2=CCP1CON.2,"CCP1 Mode Select"
CCP1M1=CCP1CON.1,"CCP1 Mode Select"
CCP1M0=CCP1CON.0,"CCP1 Mode Select"

CCPR1H="Capture/Compare/PWM register1 (MSB)"
CCPR1L="Capture/Compare/PWM register1 (LSB)"
CCPR1="Capture/Compare/PWM Register"

ADFM=ADCON2.7,"A/D Result Format Select bit"
ACQT3=ADCON2.6,"A/D Acquisition Time Select bits"
ACQT2=ADCON2.5,"A/D Acquisition Time Select bits"
ACQT1=ADCON2.4,"A/D Acquisition Time Select bits"
ACQT0=ADCON2.3,"A/D Acquisition Time Select bits"
ADCS2=ADCON2.2,"A/D Conversion Clock Select bits"
ADCS1=ADCON2.1,"A/D Conversion Clock Select bits"
ADCS0=ADCON2.0,"A/D Conversion Clock Select bits"

VCFG1=ADCON1.7,"Voltage Reference Configuration bit, VREFL Source"
VCFG0=ADCON1.6,"Voltage Reference Configuration bit, VREFH Source"
FIFOEN=ADCON1.4,"FIFO Buffer Enable bit"
BFEMT=ADCON1.3,"Buffer Empty bit"
BFOVFL=ADCON1.2,"Buffer Overflow bit"
ADPNT1=ADCON1.1,"Buffer Read Pointer Locations bits"
ADPNT0=ADCON1.0,"Buffer Read Pointer Locations bits"

ADCONV=ADCON0.5,"Auto-Conversion Continuous Loop or Single-shot Mode Select bit"
ACSCH=ADCON0.4,"Auto-Conversion Single or Multi-Channel mode bit"
ACMOD1=ADCON0.3,"Auto-Conversion mode Sequence Select bits"
ACMOD0=ADCON0.2,"Auto-Conversion mode Sequence Select bits"
DONE=ADCON0.1,"A/D Conversion Status flag"
GO=ADCON0.1,"A/D Conversion Enable"
ADON=ADCON0.0,"A/D ON bit"

ADRESL="A/D Register low byte" 
ADRESH="A/D Register high byte" 
ADRES="A/D result as a 16 bit value <br> This feature is specific to the PROTON compiler",[0..0]

WCOL=SSPCON.7," Write Collision Detect bit"
SSPOV=SSPCON.6," Receive Overflow Indicator bit "
SSPEN=SSPCON.5," Synchronous Serial Port Enable bit"
CKP=SSPCON.4,"SCK Release Control bit"
SSPM3=SSPCON.3,"Synchronous Serial Port Mode Select bits"
SSPM2=SSPCON.2,"Synchronous Serial Port Mode Select bits"
SSPM1=SSPCON.1,"Synchronous Serial Port Mode Select bits"
SSPM0=SSPCON.0,"Synchronous Serial Port Mode Select bits"

SMP=SSPSTAT.7,"SPI Data Input Sample Phase bit"
CKE=SSPSTAT.6,"SPI Clock Edge Select"
D_A=SSPSTAT.5,"Data/NOT_Address bit (I2C mode only)"
P=SSPSTAT.4,"Stop bit (I2C mode only)"
S=SSPSTAT.3,"Start bit (I2C mode only)"
R_W=SSPSTAT.2,"Read/NOT_Write bit information (I2C mode only)"
UA=SSPSTAT.1,"Update Address (10-bit I2C mode only)"
BF=SSPSTAT.0,"Buffer Full Status flag"

SSPBUF="Synchonous serial port receive buffer or transmit register"
SSPADD="Synchronous serial port (I2C mode) address register"

TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 ON"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"

TMR2="Timer2 module's register"
PR2="Timer2 period register"

RD16=T1CON.7,"16-bit Read/Write Mode Enable bit"
T1RUN=T1CON.6,"Timer1 System Clock Status bit"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"

TMR1H="Timer1 Register High Byte"
TMR1L="Timer1 Register Low Byte"

IPEN=RCON.7,"Interrupt Priority Enable bit"
NOT_RI=RCON.4,"RESET Instruction Flag bit"
NOT_TO=RCON.3,"Watchdog Time-out Flag bit"
NOT_PD=RCON.2,"Power-down Detection Flag bit"
NOT_POR=RCON.1,"Power-on Reset Status bit"
NOT_BOR=RCON.0,"Brown-out Reset Status bit"

WDTW=WDTCON.7,"Watchdog Timer Window bit"
SWDTEN=WDTCON.0,"Software Controlled Watchdog Timer Enable bit"

IRVST=LVDCON.5,"Internal Reference Voltage Stable Flag"
LVDEN=LVDCON.4,"Low Voltage Detect Power Enable bit"
LVDL3=LVDCON.3,"Low Voltage Detection Limit bit"
LVDL2=LVDCON.2,"Low Voltage Detection Limit bit"
LVDL1=LVDCON.1,"Low Voltage Detection Limit bit"
LVDL0=LVDCON.0,"Low Voltage Detection Limit bit"

OSCCON="OSCCON REGISTER"
IDLEN=OSCCON.7,"Idle Enable bits"
IRCF2=OSCCON.6,"Internal Oscillator Frequency Select bits"
IRCF1=OSCCON.5,"Internal Oscillator Frequency Select bits"
IRCF0=OSCCON.4,"Internal Oscillator Frequency Select bits"
OSTS=OSCCON.3,"Oscillator Start-up Time-out Status bit"
IOFS=OSCCON.2,"INTOSC Frequency Stable bit"
SCS1=OSCCON.1,"System Clock Select bit"
SCS0=OSCCON.0,"System Clock Select bit"

TMR0ON=T0CON.7,"Timer0 On/Off Control bit"
T016BIT=T0CON.6,"Timer0 16-bit Control bit"
T0CS=T0CON.5,"Timer0 Clock Source Select bit"
T0SE=T0CON.4,"Timer0 Source Edge Select bit"
PSA=T0CON.3,"Timer0 Prescaler Assignment bit"
T0PS2=T0CON.2,"Timer0 Prescaler Select bit"
T0PS1=T0CON.1,"Timer0 Prescaler Select bit"
T0PS0=T0CON.0,"Timer0 Prescaler Select bit"

TMR0L="Timer0 Module Low Byte Register"
TMR0H="Timer0 Module High Byte Register"

N=STATUS.4,"Negative bit"
OV=STATUS.3,"Overflow bit"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"

FSR2H="Indirect Data Memory Address Pointer 2 High Byte",[0..3]
FSR2L="Indirect Data Memory Address Pointer 2 Low Byte"

POSTINC2="Uses contents of FSR2 to address data memory value of FSR2 post-incremented<br>(not a physical register)"
POSTDEC2="Uses contents of FSR2 to address data memory - value of FSR2 post-decremented <br>(not a physical register)"
PREINC2="Uses contents of FSR2 to address data memory - value of FSR2 pre-incremented <br>(not a physical register)"
PLUSW2="Uses contents of FSR2 to address data memory - value of FSR2 pre-incremented<BR>(not a physical register) - value of FSR2 offset by value in WREG"

BSR="Bank Select Register",[0..3]

INDF2="Uses contents of FSR2 to address data memory value of FSR2 not changed (not a physical register)"

POSTINC1="Uses contents of FSR1 to address data memory value of FSR1 post-incremented<br>(not a physical register)"
POSTDEC1="Uses contents of FSR1 to address data memory - value of FSR1 post-decremented <br>(not a physical register)"
PREINC1="Uses contents of FSR1 to address data memory - value of FSR1 pre-incremented <br>(not a physical register)"
PLUSW1="Uses contents of FSR1 to address data memory - value of FSR1 pre-incremented<BR>(not a physical register) - value of FSR1 offset by value in WREG"

FSR1H="Indirect Data Memory Address Pointer 1 High Byte",[0..3]
FSR1L="Indirect Data Memory Address Pointer 1 Low Byte"

WREG="Working Register"
INDF1="Uses contents of FSR1 to address data memory value of FSR1 not changed (not a physical register)"

INDF0="Uses contents of FSR0 to address data memory value of FSR0 not changed (not a physical register)"

POSTINC0="Uses contents of FSR0 to address data memory value of FSR0 post-incremented<br>(not a physical register)"
POSTDEC0="Uses contents of FSR0 to address data memory - value of FSR0 post-decremented <br>(not a physical register)"
PREINC0="Uses contents of FSR0 to address data memory - value of FSR0 pre-incremented <br>(not a physical register)"
PLUSW0="Uses contents of FSR0 to address data memory - value of FSR0 pre-incremented<BR>(not a physical register) - value of FSR0 offset by value in WREG"

FSR0H="Indirect Data Memory Address Pointer 0 High Byte",[0..3]
FSR0L="Indirect Data Memory Address Pointer 0 Low Byte"

INT2IP=INTCON3.7,"INT2 External Interrupt Priority bit"
INT1IP=INTCON3.6,"INT1 External Interrupt Priority bit"
INT2IE=INTCON3.4,"INT2 External Interrupt Enable"
INT1IE=INTCON3.3,"INT1 External Interrupt Enable"
INT2IF=INTCON3.1,"INT2 External Interrupt Flag"
INT1IF=INTCON3.0,"INT1 External Interrupt Flag"

NOT_RBPU=INTCON2.7,"PORTB Pull-up Enable bit"
INTEDG0=INTCON2.6,"External Interrupt0 Edge Select bit"
INTEDG1=INTCON2.5,"External Interrupt1 Edge Select bit"
INTEDG2=INTCON2.4,"External Interrupt2 Edge Select bit"
TMR0IP=INTCON2.2,"TMR0 Overflow Interrupt Priority bit"
RBIP=INTCON2.0,"RB Port Change Interrupt Priority bit"

GIE=INTCON.7,"Global Interrupt Enable"
GIEH=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
GIEL=INTCON.6,"Peripheral Interrupt Enable"
TMR0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INT0IE=INTCON.4,"INT0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
TMR0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INT0IF=INTCON.1,"INT0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"

PRODH="Product Register High Byte"
PRODL="Product Register Low Byte"
PROD="Product Register"

TBLPTRU="Program Memory Table Pointer<br>Upper Byte (TBLPTR<20:16>",[0..4]
TBLPTRH="Program Memory Table Pointer High Byte (TBLPTR<15:8>)"
TBLPTRL="Program Memory Table Pointer Low Byte (TBLPTR<7:0>)"
TABLAT="Program Memory Table Latch"
TBLPTR="Table Pointer Register"


PCLATU="Program Counter Upper Byte Latch"
BIT21=PCLATU.5
PCLATH="Program Counter High Byte Latch"
PCL="PC Low Byte"
PCH="PC High Byte"
PC="Program Counter"

STKFUL=STKPTR.7,"Stack Full Flag bit"
STKUNF=STKPTR.6,"Stack Underflow Flag bit"
SP4=STKPTR.4,"Stack Pointer Location bit"
SP3=STKPTR.3,"Stack Pointer Location bit"
SP2=STKPTR.2,"Stack Pointer Location bit"
SP1=STKPTR.1,"Stack Pointer Location bit"
SP0=STKPTR.0,"Stack Pointer Location bit"

TOSU="Top-of-Stack Upper Byte (TOS<20:16>)",[0..4]
TOSH="Top-of-Stack High Byte (TOS<15:8>)"
TOSLH="Top-of-Stack High Byte (TOS<15:8>)"
TOSL="Top-of-Stack Low Byte (TOS<7:0>)"
TOS="Top Of Stack Register"

