** BITNAMES **
RXF6SIDH="RECEIVE ACCEPTANCE FILTER 6 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF6SIDL="RECEIVE ACCEPTANCE FILTER 6 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF6EIDH="RECEIVE ACCEPTANCE FILTER 6 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF6EIDL="RECEIVE ACCEPTANCE FILTER 6 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF7SIDH="RECEIVE ACCEPTANCE FILTER 7 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF7SIDL="RECEIVE ACCEPTANCE FILTER 7 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF7EIDH="RECEIVE ACCEPTANCE FILTER 7 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF7EIDL="RECEIVE ACCEPTANCE FILTER 7 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF8SIDH="RECEIVE ACCEPTANCE FILTER 8 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF8SIDL="RECEIVE ACCEPTANCE FILTER 8 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF8EIDH="RECEIVE ACCEPTANCE FILTER 8 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF8EIDL="RECEIVE ACCEPTANCE FILTER 8 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF9SIDH="RECEIVE ACCEPTANCE FILTER 9 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF9SIDL="RECEIVE ACCEPTANCE FILTER 9 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF9EIDH="RECEIVE ACCEPTANCE FILTER 9 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF9EIDL="RECEIVE ACCEPTANCE FILTER 9 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF10SIDH="RECEIVE ACCEPTANCE FILTER 10 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF10SIDL="RECEIVE ACCEPTANCE FILTER 10 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF10EIDH="RECEIVE ACCEPTANCE FILTER 10 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF10EIDL="RECEIVE ACCEPTANCE FILTER 10 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF11SIDH="RECEIVE ACCEPTANCE FILTER 11 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF11SIDL="RECEIVE ACCEPTANCE FILTER 11 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF11EIDH="RECEIVE ACCEPTANCE FILTER 11 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF11EIDL="RECEIVE ACCEPTANCE FILTER 11 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF12SIDH="RECEIVE ACCEPTANCE FILTER 12 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF12SIDL="RECEIVE ACCEPTANCE FILTER 12 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF12EIDH="RECEIVE ACCEPTANCE FILTER 12 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF12EIDL="RECEIVE ACCEPTANCE FILTER 12 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF13SIDH="RECEIVE ACCEPTANCE FILTER 13 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF13SIDL="RECEIVE ACCEPTANCE FILTER 13 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF13EIDH="RECEIVE ACCEPTANCE FILTER 13 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF13EIDL="RECEIVE ACCEPTANCE FILTER 13 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF14SIDH="RECEIVE ACCEPTANCE FILTER 14 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF14SIDL="RECEIVE ACCEPTANCE FILTER 14 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF14EIDH="RECEIVE ACCEPTANCE FILTER 14 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF14EIDL="RECEIVE ACCEPTANCE FILTER 14 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF15SIDH="RECEIVE ACCEPTANCE FILTER 15 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF15SIDL="RECEIVE ACCEPTANCE FILTER 15 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF15EIDH="RECEIVE ACCEPTANCE FILTER 15 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF15EIDL="RECEIVE ACCEPTANCE FILTER 15 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF7EN=RXFCON0.7,"Receive Filter 0 Enable bits"
RXF6EN=RXFCON0.6,"Receive Filter 0 Enable bits"
RXF5EN=RXFCON0.5,"Receive Filter 0 Enable bits"
RXF4EN=RXFCON0.4,"Receive Filter 0 Enable bits"
RXF3EN=RXFCON0.3,"Receive Filter 0 Enable bits"
RXF2EN=RXFCON0.2,"Receive Filter 0 Enable bits"
RXF1EN=RXFCON0.1,"Receive Filter 0 Enable bits"
RXF0EN=RXFCON0.0,"Receive Filter 0 Enable bits"

RXF15EN=RXFCON1.7,"Receive Filter 1 Enable bits"
RXF14EN=RXFCON1.6,"Receive Filter 1 Enable bits"
RXF13EN=RXFCON1.5,"Receive Filter 1 Enable bits"
RXF12EN=RXFCON1.4,"Receive Filter 1 Enable bits"
RXF11EN=RXFCON1.3,"Receive Filter 1 Enable bits"
RXF10EN=RXFCON1.2,"Receive Filter 1 Enable bits"
RXF9EN=RXFCON1.1,"Receive Filter 1 Enable bits"
RXF8EN=RXFCON1.0,"Receive Filter 1 Enable bits"

FLC4=SDFLC.4,"Filter Length Count bits"
FLC3=SDFLC.3,"Filter Length Count bits"
FLC2=SDFLC.2,"Filter Length Count bits"
FLC1=SDFLC.1,"Filter Length Count bits"
FLC0=SDFLC.0,"Filter Length Count bits"

F1BP_3=RXFBCON0.7,"Filter 0 Buffer Pointer Nibble bits"
F1BP_2=RXFBCON0.6,"Filter 0 Buffer Pointer Nibble bits"
F1BP_1=RXFBCON0.5,"Filter 0 Buffer Pointer Nibble bits"
F1BP_0=RXFBCON0.4,"Filter 0 Buffer Pointer Nibble bits"
F0BP_3=RXFBCON0.3,"Filter 0 Buffer Pointer Nibble bits"
F0BP_2=RXFBCON0.2,"Filter 0 Buffer Pointer Nibble bits"
F0BP_1=RXFBCON0.1,"Filter 0 Buffer Pointer Nibble bits"
F0BP_0=RXFBCON0.0,"Filter 0 Buffer Pointer Nibble bits"

F3BP_3=RXFBCON1.7,"Filter 1 Buffer Pointer Nibble bits"
F3BP_2=RXFBCON1.6,"Filter 1 Buffer Pointer Nibble bits"
F3BP_1=RXFBCON1.5,"Filter 1 Buffer Pointer Nibble bits"
F3BP_0=RXFBCON1.4,"Filter 1 Buffer Pointer Nibble bits"
F2BP_3=RXFBCON1.3,"Filter 1 Buffer Pointer Nibble bits"
F2BP_2=RXFBCON1.2,"Filter 1 Buffer Pointer Nibble bits"
F2BP_1=RXFBCON1.1,"Filter 1 Buffer Pointer Nibble bits"
F2BP_0=RXFBCON1.0,"Filter 1 Buffer Pointer Nibble bits"

F5BP_3=RXFBCON2.7,"Filter 2 Buffer Pointer Nibble bits"
F5BP_2=RXFBCON2.6,"Filter 2 Buffer Pointer Nibble bits"
F5BP_1=RXFBCON2.5,"Filter 2 Buffer Pointer Nibble bits"
F5BP_0=RXFBCON2.4,"Filter 2 Buffer Pointer Nibble bits"
F4BP_3=RXFBCON2.3,"Filter 2 Buffer Pointer Nibble bits"
F4BP_2=RXFBCON2.2,"Filter 2 Buffer Pointer Nibble bits"
F4BP_1=RXFBCON2.1,"Filter 2 Buffer Pointer Nibble bits"
F4BP_0=RXFBCON2.0,"Filter 2 Buffer Pointer Nibble bits"

F7BP_3=RXFBCON3.7,"Filter 3 Buffer Pointer Nibble bits"
F7BP_2=RXFBCON3.6,"Filter 3 Buffer Pointer Nibble bits"
F7BP_1=RXFBCON3.5,"Filter 3 Buffer Pointer Nibble bits"
F7BP_0=RXFBCON3.4,"Filter 3 Buffer Pointer Nibble bits"
F6BP_3=RXFBCON3.3,"Filter 3 Buffer Pointer Nibble bits"
F6BP_2=RXFBCON3.2,"Filter 3 Buffer Pointer Nibble bits"
F6BP_1=RXFBCON3.1,"Filter 3 Buffer Pointer Nibble bits"
F6BP_0=RXFBCON3.0,"Filter 3 Buffer Pointer Nibble bits"

F9BP_3=RXFBCON4.7,"Filter 4 Buffer Pointer Nibble bits"
F9BP_2=RXFBCON4.6,"Filter 4 Buffer Pointer Nibble bits"
F9BP_1=RXFBCON4.5,"Filter 4 Buffer Pointer Nibble bits"
F9BP_0=RXFBCON4.4,"Filter 4 Buffer Pointer Nibble bits"
F8BP_3=RXFBCON4.3,"Filter 4 Buffer Pointer Nibble bits"
F8BP_2=RXFBCON4.2,"Filter 4 Buffer Pointer Nibble bits"
F8BP_1=RXFBCON4.1,"Filter 4 Buffer Pointer Nibble bits"
F8BP_0=RXFBCON4.0,"Filter 4 Buffer Pointer Nibble bits"

F11BP_3=RXFBCON5.7,"Filter 5 Buffer Pointer Nibble bits"
F11BP_2=RXFBCON5.6,"Filter 5 Buffer Pointer Nibble bits"
F11BP_1=RXFBCON5.5,"Filter 5 Buffer Pointer Nibble bits"
F11BP_0=RXFBCON5.4,"Filter 5 Buffer Pointer Nibble bits"
F10BP_3=RXFBCON5.3,"Filter 5 Buffer Pointer Nibble bits"
F10BP_2=RXFBCON5.2,"Filter 5 Buffer Pointer Nibble bits"
F10BP_1=RXFBCON5.1,"Filter 5 Buffer Pointer Nibble bits"
F10BP_0=RXFBCON5.0,"Filter 5 Buffer Pointer Nibble bits"

F13BP_3=RXFBCON6.7,"Filter 6 Buffer Pointer Nibble bits"
F13BP_2=RXFBCON6.6,"Filter 6 Buffer Pointer Nibble bits"
F13BP_1=RXFBCON6.5,"Filter 6 Buffer Pointer Nibble bits"
F13BP_0=RXFBCON6.4,"Filter 6 Buffer Pointer Nibble bits"
F12BP_3=RXFBCON6.3,"Filter 6 Buffer Pointer Nibble bits"
F12BP_2=RXFBCON6.2,"Filter 6 Buffer Pointer Nibble bits"
F12BP_1=RXFBCON6.1,"Filter 6 Buffer Pointer Nibble bits"
F12BP_0=RXFBCON6.0,"Filter 6 Buffer Pointer Nibble bits"

F15BP_3=RXFBCON7.7,"Filter 7 Buffer Pointer Nibble bits"
F15BP_2=RXFBCON7.6,"Filter 7 Buffer Pointer Nibble bits"
F15BP_1=RXFBCON7.5,"Filter 7 Buffer Pointer Nibble bits"
F15BP_0=RXFBCON7.4,"Filter 7 Buffer Pointer Nibble bits"
F14BP_3=RXFBCON7.3,"Filter 7 Buffer Pointer Nibble bits"
F14BP_2=RXFBCON7.2,"Filter 7 Buffer Pointer Nibble bits"
F14BP_1=RXFBCON7.1,"Filter 7 Buffer Pointer Nibble bits"
F14BP_0=RXFBCON7.0,"Filter 7 Buffer Pointer Nibble bits"

FIL3_1=MSEL0.7,"Filter 3 Select bit 1"
FIL3_0=MSEL0.6,"Filter 3 Select bit 0"
FIL2_1=MSEL0.5,"Filter 2 Select bit 1"
FIL2_0=MSEL0.4,"Filter 2 Select bit 0"
FIL1_1=MSEL0.3,"Filter 1 Select bit 1"
FIL1_0=MSEL0.2,"Filter 1 Select bit 0"
FIL0_1=MSEL0.1,"Filter 0 Select bit 1"
FIL0_0=MSEL0.0,"Filter 0 Select bit 0"

FIL7_1=MSEL1.7,"Filter 7 Select bit 1"
FIL7_0=MSEL1.6,"Filter 7 Select bit 0"
FIL6_1=MSEL1.5,"Filter 6 Select bit 1"
FIL6_0=MSEL1.4,"Filter 6 Select bit 0"
FIL5_1=MSEL1.3,"Filter 5 Select bit 1"
FIL5_0=MSEL1.2,"Filter 5 Select bit 0"
FIL4_1=MSEL1.1,"Filter 4 Select bit 1"
FIL4_0=MSEL1.0,"Filter 4 Select bit 0"

FIL11_1=MSEL2.7,"Filter 11 Select bit 1"
FIL11_0=MSEL2.6,"Filter 11 Select bit 0"
FIL10_1=MSEL2.5,"Filter 10 Select bit 1"
FIL10_0=MSEL2.4,"Filter 10 Select bit 0"
FIL9_1=MSEL2.3,"Filter 9 Select bit 1"
FIL9_0=MSEL2.2,"Filter 9 Select bit 0"
FIL8_1=MSEL2.1,"Filter 8 Select bit 1"
FIL8_0=MSEL2.0,"Filter 8 Select bit 0"

FIL15_1=MSEL3.7,"Filter 15 Select bit 1"
FIL15_0=MSEL3.6,"Filter 15 Select bit 0"
FIL14_1=MSEL3.5,"Filter 14 Select bit 1"
FIL14_0=MSEL3.4,"Filter 14 Select bit 0"
FIL13_1=MSEL3.3,"Filter 13 Select bit 1"
FIL13_0=MSEL3.2,"Filter 13 Select bit 0"
FIL12_1=MSEL3.1,"Filter 12 Select bit 1"
FIL12_0=MSEL3.0,"Filter 12 Select bit 0"

B5TXEN=BSEL0.7,"Buffer 5 Transmit Enable bit"
B4TXEN=BSEL0.6,"Buffer 4 Transmit Enable bit"
B3TXEN=BSEL0.5,"Buffer 3 Transmit Enable bit"
B2TXEN=BSEL0.4,"Buffer 2 Transmit Enable bit"
B1TXEN=BSEL0.3,"Buffer 1 Transmit Enable bit"
B0TXEN=BSEL0.2,"Buffer 0 Transmit Enable bit"

B5IE=BIE0.7,"Programmable Transmit/Receive Buffer 5 Interrupt Enable bit"
B4IE=BIE0.6,"Programmable Transmit/Receive Buffer 4 Interrupt Enable bit"
B3IE=BIE0.5,"Programmable Transmit/Receive Buffer 3 Interrupt Enable bit"
B2IE=BIE0.4,"Programmable Transmit/Receive Buffer 2 Interrupt Enable bit"
B1IE=BIE0.3,"Programmable Transmit/Receive Buffer 1 Interrupt Enable bit"
B0IE=BIE0.2,"Programmable Transmit/Receive Buffer 0 Interrupt Enable bit"
RXB1IE=BIE0.1,"Dedicated Receive Buffer 1 Interrupt Enable bit"
RXB0IE=BIE0.0,"Dedicated Receive Buffer 0 Interrupt Enable bit"

TXB2IE=TXBIE.4,"Transmit Buffer 2 Interrupt Enable bit"
TXB1IE=TXBIE.3,"Transmit Buffer 1 Interrupt Enable bit"
TXB0IE=TXBIE.2,"Transmit Buffer 0 Interrupt Enable bit"

RXFUL=B0CON.7,"Receive Full Status bit<br> In Receive Mode"
RXM1=B0CON.6,"Receive Buffer Mode bits<br> In Receive Mode"
RXRTRRO=B0CON.5,"Read-Only Remote Transmission Request for Received Message bit<br> In Receive Mode"
FILHIT4=B0CON.4,"Filter Hit bit<br> In Receive Mode"
FILHIT3=B0CON.3,"Filter Hit bit<br> In Receive Mode"
FILHIT2=B0CON.2,"Filter Hit bit<br> In Receive Mode"
FILHIT1=B0CON.1,"Filter Hit bit<br> In Receive Mode"
FILHIT0=B0CON.0,"Filter Hit bit<br> In Receive Mode"
TXBIF=B0CON.7,"Transmit Buffer Interrupt Flag bit<br> In Transmit Mode"
TXABT=B0CON.6,"Transmission Aborted Status bit<br> In Transmit Mode"
TXLARB=B0CON.5,"Transmission Lost Arbitration Status bit<br> In Transmit Mode"
TXERR=B0CON.4,"Transmission Error Detected Status bit<br> In Transmit Mode"
TXREQ=B0CON.3,"Transmit Request Status bit<br> In Transmit Mode"
RTREN=B0CON.2,"Automatic Remote Transmission Request Enable bit<br> In Transmit Mode"
TXPRI1=B0CON.1,"Transmit Priority bits<br> In Transmit Mode"
TXPRI0=B0CON.0,"Transmit Priority bits<br> In Transmit Mode"

B0SIDH="TX/RX BUFFER 0 STANDARD IDENTIFIER REGISTERS, <br>HIGH BYTE IN RECEIVE or TRANSMIT MODE <br>Standard Identifier Bits (SID10:SID3)"

SID2=B0SIDL.7,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID1=B0SIDL.6,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID0=B0SIDL.5,"Standard Identifier bits<br> In Receive or Transmit Mode"
SRR=B0SIDL.4,"Substitute Remote Transmission Request bit<br> In Receive Mode"
EXID=B0SIDL.3,"Extended Identifier Enable bit<br> In Receive Mode"
EXIDE=B0SIDL.3,"Extended Identifier Enable bit<br> In Transmit Mode"
EID17=B0SIDL.1,"Extended Identifier bits<br> In Receive or Transmit Mode"
EID16=B0SIDL.0,"Extended Identifier bits<br> In Receive or Transmit ode"

B0EIDH="TX/RX BUFFER 0 EXTENDED IDENTIFIER REGISTER, HIGH BYTE IN RECEIVE or TRANSMIT MODE"
B0EIDL="TX/RX BUFFER 0 EXTENDED IDENTIFIER REGISTERS, LOW BYTE IN RECEIVE or TRANSMIT MODE"

RXRTR=B0DLC.6,"Receiver Remote Transmission Request bit<br>in Receive Mode"
RB1=B0DLC.5,"Reserved bit 1<br> In Receive Mode"
RB0=B0DLC.4,"Reserved bit 0<br> In Receive Mode"
DLC3=B0DLC.3,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC2=B0DLC.2,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC1=B0DLC.1,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC0=B0DLC.0,"Data Length Code bits<br> In Transmit or Receive Mode"
TXRTR=B0DLC.6,"Transmitter Remote Transmission Request bit<br> In Transmit Mode"

B0D0="TX/RX BUFFER 0 DATA FIELD BYTE 0 REGISTER IN TRANSMIT or RECEIVE MODE"
B0D1="TX/RX BUFFER 0 DATA FIELD BYTE 1 REGISTER IN TRANSMIT or RECEIVE MODE"
B0D2="TX/RX BUFFER 0 DATA FIELD BYTE 2 REGISTER IN TRANSMIT or RECEIVE MODE"
B0D3="TX/RX BUFFER 0 DATA FIELD BYTE 3 REGISTER IN TRANSMIT or RECEIVE MODE"
B0D4="TX/RX BUFFER 0 DATA FIELD BYTE 4 REGISTER IN TRANSMIT or RECEIVE MODE"
B0D5="TX/RX BUFFER 0 DATA FIELD BYTE 5 REGISTER IN TRANSMIT or RECEIVE MODE"
B0D6="TX/RX BUFFER 0 DATA FIELD BYTE 6 REGISTER IN TRANSMIT or RECEIVE MODE"
B0D7="TX/RX BUFFER 0 DATA FIELD BYTE 7 REGISTER IN TRANSMIT or RECEIVE MODE"

OPMODE2=CANSTAT_RO9.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO9.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO9.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO9.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO9.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO9.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO9.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO9.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO9.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO9.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO9.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO9.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO9.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO9.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO9.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO9.3,"Window Address bits Mode 0"
WIN1=CANCON_RO9.2,"Window Address bits Mode 0"
WIN0=CANCON_RO9.1,"Window Address bits Mode 0"
FP3=CANCON_RO9.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO9.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO9.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO9.0,"FIFO Read Pointer bits Mode 2"

RXFUL=B1CON.7,"Receive Full Status bit<br> In Receive Mode"
RXM1=B1CON.6,"Receive Buffer Mode bits<br> In Receive Mode"
RXRTRRO=B1CON.5,"Read-Only Remote Transmission Request for Received Message bit<br> In Receive Mode"
FILHIT4=B1CON.4,"Filter Hit bit<br> In Receive Mode"
FILHIT3=B1CON.3,"Filter Hit bit<br> In Receive Mode"
FILHIT2=B1CON.2,"Filter Hit bit<br> In Receive Mode"
FILHIT1=B1CON.1,"Filter Hit bit<br> In Receive Mode"
FILHIT0=B1CON.0,"Filter Hit bit<br> In Receive Mode"
TXBIF=B1CON.7,"Transmit Buffer Interrupt Flag bit<br> In Transmit Mode"
TXABT=B1CON.6,"Transmission Aborted Status bit<br> In Transmit Mode"
TXLARB=B1CON.5,"Transmission Lost Arbitration Status bit<br> In Transmit Mode"
TXERR=B1CON.4,"Transmission Error Detected Status bit<br> In Transmit Mode"
TXREQ=B1CON.3,"Transmit Request Status bit<br> In Transmit Mode"
RTREN=B1CON.2,"Automatic Remote Transmission Request Enable bit<br> In Transmit Mode"
TXPRI1=B1CON.1,"Transmit Priority bits<br> In Transmit Mode"
TXPRI0=B1CON.0,"Transmit Priority bits<br> In Transmit Mode"

B1SIDH="TX/RX BUFFER 1 STANDARD IDENTIFIER REGISTERS, <br>HIGH BYTE IN RECEIVE or TRANSMIT MODE <br>Standard Identifier Bits (SID10:SID3)"

SID2=B1SIDL.7,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID1=B1SIDL.6,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID0=B1SIDL.5,"Standard Identifier bits<br> In Receive or Transmit Mode"
SRR=B1SIDL.4,"Substitute Remote Transmission Request bit<br> In Receive Mode"
EXID=B1SIDL.3,"Extended Identifier Enable bit<br> In Receive Mode"
EXIDE=B1SIDL.3,"Extended Identifier Enable bit<br> In Transmit Mode"
EID17=B1SIDL.1,"Extended Identifier bits<br> In Receive or Transmit Mode"
EID16=B1SIDL.0,"Extended Identifier bits<br> In Receive or Transmit ode"

B1EIDH="TX/RX BUFFER 1 EXTENDED IDENTIFIER REGISTER, HIGH BYTE IN RECEIVE or TRANSMIT MODE"
B1EIDL="TX/RX BUFFER 1 EXTENDED IDENTIFIER REGISTERS, LOW BYTE IN RECEIVE or TRANSMIT MODE"

RXRTR=B1DLC.6,"Receiver Remote Transmission Request bit<br>in Receive Mode"
RB1=B1DLC.5,"Reserved bit 1<br> In Receive Mode"
RB0=B1DLC.4,"Reserved bit 0<br> In Receive Mode"
DLC3=B1DLC.3,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC2=B1DLC.2,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC1=B1DLC.1,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC0=B1DLC.0,"Data Length Code bits<br> In Transmit or Receive Mode"
TXRTR=B1DLC.6,"Transmitter Remote Transmission Request bit<br> In Transmit Mode"

B1D0="TX/RX BUFFER 1 DATA FIELD BYTE 0 REGISTER IN TRANSMIT or RECEIVE MODE"
B1D1="TX/RX BUFFER 1 DATA FIELD BYTE 1 REGISTER IN TRANSMIT or RECEIVE MODE"
B1D2="TX/RX BUFFER 1 DATA FIELD BYTE 2 REGISTER IN TRANSMIT or RECEIVE MODE"
B1D3="TX/RX BUFFER 1 DATA FIELD BYTE 3 REGISTER IN TRANSMIT or RECEIVE MODE"
B1D4="TX/RX BUFFER 1 DATA FIELD BYTE 4 REGISTER IN TRANSMIT or RECEIVE MODE"
B1D5="TX/RX BUFFER 1 DATA FIELD BYTE 5 REGISTER IN TRANSMIT or RECEIVE MODE"
B1D6="TX/RX BUFFER 1 DATA FIELD BYTE 6 REGISTER IN TRANSMIT or RECEIVE MODE"
B1D7="TX/RX BUFFER 1 DATA FIELD BYTE 7 REGISTER IN TRANSMIT or RECEIVE MODE"

OPMODE2=CANSTAT_RO8.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO8.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO8.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO8.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO8.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO8.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO8.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO8.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO8.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO8.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO8.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO8.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO8.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO8.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO8.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO8.3,"Window Address bits Mode 0"
WIN1=CANCON_RO8.2,"Window Address bits Mode 0"
WIN0=CANCON_RO8.1,"Window Address bits Mode 0"
FP3=CANCON_RO8.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO8.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO8.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO8.0,"FIFO Read Pointer bits Mode 2"

RXFUL=B2CON.7,"Receive Full Status bit<br> In Receive Mode"
RXM1=B2CON.6,"Receive Buffer Mode bits<br> In Receive Mode"
RXRTRRO=B2CON.5,"Read-Only Remote Transmission Request for Received Message bit<br> In Receive Mode"
FILHIT4=B2CON.4,"Filter Hit bit<br> In Receive Mode"
FILHIT3=B2CON.3,"Filter Hit bit<br> In Receive Mode"
FILHIT2=B2CON.2,"Filter Hit bit<br> In Receive Mode"
FILHIT1=B2CON.1,"Filter Hit bit<br> In Receive Mode"
FILHIT0=B2CON.0,"Filter Hit bit<br> In Receive Mode"
TXBIF=B2CON.7,"Transmit Buffer Interrupt Flag bit<br> In Transmit Mode"
TXABT=B2CON.6,"Transmission Aborted Status bit<br> In Transmit Mode"
TXLARB=B2CON.5,"Transmission Lost Arbitration Status bit<br> In Transmit Mode"
TXERR=B2CON.4,"Transmission Error Detected Status bit<br> In Transmit Mode"
TXREQ=B2CON.3,"Transmit Request Status bit<br> In Transmit Mode"
RTREN=B2CON.2,"Automatic Remote Transmission Request Enable bit<br> In Transmit Mode"
TXPRI1=B2CON.1,"Transmit Priority bits<br> In Transmit Mode"
TXPRI0=B2CON.0,"Transmit Priority bits<br> In Transmit Mode"

B2SIDH="TX/RX BUFFER 2 STANDARD IDENTIFIER REGISTERS, <br>HIGH BYTE IN RECEIVE or TRANSMIT MODE <br>Standard Identifier Bits (SID10:SID3)"

SID2=B2SIDL.7,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID1=B2SIDL.6,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID0=B2SIDL.5,"Standard Identifier bits<br> In Receive or Transmit Mode"
SRR=B2SIDL.4,"Substitute Remote Transmission Request bit<br> In Receive Mode"
EXID=B2SIDL.3,"Extended Identifier Enable bit<br> In Receive Mode"
EXIDE=B2SIDL.3,"Extended Identifier Enable bit<br> In Transmit Mode"
EID17=B2SIDL.1,"Extended Identifier bits<br> In Receive or Transmit Mode"
EID16=B2SIDL.0,"Extended Identifier bits<br> In Receive or Transmit ode"

B2EIDH="TX/RX BUFFER 2 EXTENDED IDENTIFIER REGISTER, HIGH BYTE IN RECEIVE or TRANSMIT MODE"
B2EIDL="TX/RX BUFFER 2 EXTENDED IDENTIFIER REGISTERS, LOW BYTE IN RECEIVE or TRANSMIT MODE"

RXRTR=B2DLC.6,"Receiver Remote Transmission Request bit<br>in Receive Mode"
RB1=B2DLC.5,"Reserved bit 1<br> In Receive Mode"
RB0=B2DLC.4,"Reserved bit 0<br> In Receive Mode"
DLC3=B2DLC.3,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC2=B2DLC.2,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC1=B2DLC.1,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC0=B2DLC.0,"Data Length Code bits<br> In Transmit or Receive Mode"
TXRTR=B2DLC.6,"Transmitter Remote Transmission Request bit<br> In Transmit Mode"

B2D0="TX/RX BUFFER 2 DATA FIELD BYTE 0 REGISTER IN TRANSMIT or RECEIVE MODE"
B2D1="TX/RX BUFFER 2 DATA FIELD BYTE 1 REGISTER IN TRANSMIT or RECEIVE MODE"
B2D2="TX/RX BUFFER 2 DATA FIELD BYTE 2 REGISTER IN TRANSMIT or RECEIVE MODE"
B2D3="TX/RX BUFFER 2 DATA FIELD BYTE 3 REGISTER IN TRANSMIT or RECEIVE MODE"
B2D4="TX/RX BUFFER 2 DATA FIELD BYTE 4 REGISTER IN TRANSMIT or RECEIVE MODE"
B2D5="TX/RX BUFFER 2 DATA FIELD BYTE 5 REGISTER IN TRANSMIT or RECEIVE MODE"
B2D6="TX/RX BUFFER 2 DATA FIELD BYTE 6 REGISTER IN TRANSMIT or RECEIVE MODE"
B2D7="TX/RX BUFFER 2 DATA FIELD BYTE 7 REGISTER IN TRANSMIT or RECEIVE MODE"


OPMODE2=CANSTAT_RO7.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO7.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO7.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO7.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO7.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO7.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO7.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO7.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO7.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO7.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO7.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO7.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO7.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO7.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO7.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO7.3,"Window Address bits Mode 0"
WIN1=CANCON_RO7.2,"Window Address bits Mode 0"
WIN0=CANCON_RO7.1,"Window Address bits Mode 0"
FP3=CANCON_RO7.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO7.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO7.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO7.0,"FIFO Read Pointer bits Mode 2"

RXFUL=B3CON.7,"Receive Full Status bit<br> In Receive Mode"
RXM1=B3CON.6,"Receive Buffer Mode bits<br> In Receive Mode"
RXRTRRO=B3CON.5,"Read-Only Remote Transmission Request for Received Message bit<br> In Receive Mode"
FILHIT4=B3CON.4,"Filter Hit bit<br> In Receive Mode"
FILHIT3=B3CON.3,"Filter Hit bit<br> In Receive Mode"
FILHIT2=B3CON.2,"Filter Hit bit<br> In Receive Mode"
FILHIT1=B3CON.1,"Filter Hit bit<br> In Receive Mode"
FILHIT0=B3CON.0,"Filter Hit bit<br> In Receive Mode"
TXBIF=B3CON.7,"Transmit Buffer Interrupt Flag bit<br> In Transmit Mode"
TXABT=B3CON.6,"Transmission Aborted Status bit<br> In Transmit Mode"
TXLARB=B3CON.5,"Transmission Lost Arbitration Status bit<br> In Transmit Mode"
TXERR=B3CON.4,"Transmission Error Detected Status bit<br> In Transmit Mode"
TXREQ=B3CON.3,"Transmit Request Status bit<br> In Transmit Mode"
RTREN=B3CON.2,"Automatic Remote Transmission Request Enable bit<br> In Transmit Mode"
TXPRI1=B3CON.1,"Transmit Priority bits<br> In Transmit Mode"
TXPRI0=B3CON.0,"Transmit Priority bits<br> In Transmit Mode"

B3SIDH="TX/RX BUFFER 3 STANDARD IDENTIFIER REGISTERS, <br>HIGH BYTE IN RECEIVE or TRANSMIT MODE <br>Standard Identifier Bits (SID10:SID3)"

SID2=B3SIDL.7,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID1=B3SIDL.6,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID0=B3SIDL.5,"Standard Identifier bits<br> In Receive or Transmit Mode"
SRR=B3SIDL.4,"Substitute Remote Transmission Request bit<br> In Receive Mode"
EXID=B3SIDL.3,"Extended Identifier Enable bit<br> In Receive Mode"
EXIDE=B3SIDL.3,"Extended Identifier Enable bit<br> In Transmit Mode"
EID17=B3SIDL.1,"Extended Identifier bits<br> In Receive or Transmit Mode"
EID16=B3SIDL.0,"Extended Identifier bits<br> In Receive or Transmit ode"

B3EIDH="TX/RX BUFFER 3 EXTENDED IDENTIFIER REGISTER, HIGH BYTE IN RECEIVE or TRANSMIT MODE"
B3EIDL="TX/RX BUFFER 3 EXTENDED IDENTIFIER REGISTERS, LOW BYTE IN RECEIVE or TRANSMIT MODE"

RXRTR=B3DLC.6,"Receiver Remote Transmission Request bit<br>in Receive Mode"
RB1=B3DLC.5,"Reserved bit 1<br> In Receive Mode"
RB0=B3DLC.4,"Reserved bit 0<br> In Receive Mode"
DLC3=B3DLC.3,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC2=B3DLC.2,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC1=B3DLC.1,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC0=B3DLC.0,"Data Length Code bits<br> In Transmit or Receive Mode"
TXRTR=B3DLC.6,"Transmitter Remote Transmission Request bit<br> In Transmit Mode"

B3D0="TX/RX BUFFER 3 DATA FIELD BYTE 0 REGISTER IN TRANSMIT or RECEIVE MODE"
B3D1="TX/RX BUFFER 3 DATA FIELD BYTE 1 REGISTER IN TRANSMIT or RECEIVE MODE"
B3D2="TX/RX BUFFER 3 DATA FIELD BYTE 2 REGISTER IN TRANSMIT or RECEIVE MODE"
B3D3="TX/RX BUFFER 3 DATA FIELD BYTE 3 REGISTER IN TRANSMIT or RECEIVE MODE"
B3D4="TX/RX BUFFER 3 DATA FIELD BYTE 4 REGISTER IN TRANSMIT or RECEIVE MODE"
B3D5="TX/RX BUFFER 3 DATA FIELD BYTE 5 REGISTER IN TRANSMIT or RECEIVE MODE"
B3D6="TX/RX BUFFER 3 DATA FIELD BYTE 6 REGISTER IN TRANSMIT or RECEIVE MODE"
B3D7="TX/RX BUFFER 3 DATA FIELD BYTE 7 REGISTER IN TRANSMIT or RECEIVE MODE"



OPMODE2=CANSTAT_RO6.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO6.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO6.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO6.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO6.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO6.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO6.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO6.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO6.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO6.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO6.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO6.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO6.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO6.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO6.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO6.3,"Window Address bits Mode 0"
WIN1=CANCON_RO6.2,"Window Address bits Mode 0"
WIN0=CANCON_RO6.1,"Window Address bits Mode 0"
FP3=CANCON_RO6.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO6.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO6.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO6.0,"FIFO Read Pointer bits Mode 2"

RXFUL=B4CON.7,"Receive Full Status bit<br> In Receive Mode"
RXM1=B4CON.6,"Receive Buffer Mode bits<br> In Receive Mode"
RXRTRRO=B4CON.5,"Read-Only Remote Transmission Request for Received Message bit<br> In Receive Mode"
FILHIT4=B4CON.4,"Filter Hit bit<br> In Receive Mode"
FILHIT3=B4CON.3,"Filter Hit bit<br> In Receive Mode"
FILHIT2=B4CON.2,"Filter Hit bit<br> In Receive Mode"
FILHIT1=B4CON.1,"Filter Hit bit<br> In Receive Mode"
FILHIT0=B4CON.0,"Filter Hit bit<br> In Receive Mode"
TXBIF=B4CON.7,"Transmit Buffer Interrupt Flag bit<br> In Transmit Mode"
TXABT=B4CON.6,"Transmission Aborted Status bit<br> In Transmit Mode"
TXLARB=B4CON.5,"Transmission Lost Arbitration Status bit<br> In Transmit Mode"
TXERR=B4CON.4,"Transmission Error Detected Status bit<br> In Transmit Mode"
TXREQ=B4CON.3,"Transmit Request Status bit<br> In Transmit Mode"
RTREN=B4CON.2,"Automatic Remote Transmission Request Enable bit<br> In Transmit Mode"
TXPRI1=B4CON.1,"Transmit Priority bits<br> In Transmit Mode"
TXPRI0=B4CON.0,"Transmit Priority bits<br> In Transmit Mode"

B4SIDH="TX/RX BUFFER 4 STANDARD IDENTIFIER REGISTERS, <br>HIGH BYTE IN RECEIVE or TRANSMIT MODE <br>Standard Identifier Bits (SID10:SID3)"

SID2=B4SIDL.7,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID1=B4SIDL.6,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID0=B4SIDL.5,"Standard Identifier bits<br> In Receive or Transmit Mode"
SRR=B4SIDL.4,"Substitute Remote Transmission Request bit<br> In Receive Mode"
EXID=B4SIDL.3,"Extended Identifier Enable bit<br> In Receive Mode"
EXIDE=B4SIDL.3,"Extended Identifier Enable bit<br> In Transmit Mode"
EID17=B4SIDL.1,"Extended Identifier bits<br> In Receive or Transmit Mode"
EID16=B4SIDL.0,"Extended Identifier bits<br> In Receive or Transmit ode"

B4EIDH="TX/RX BUFFER 4 EXTENDED IDENTIFIER REGISTER, HIGH BYTE IN RECEIVE or TRANSMIT MODE"
B4EIDL="TX/RX BUFFER 4 EXTENDED IDENTIFIER REGISTERS, LOW BYTE IN RECEIVE or TRANSMIT MODE"

RXRTR=B4DLC.6,"Receiver Remote Transmission Request bit<br>in Receive Mode"
RB1=B4DLC.5,"Reserved bit 1<br> In Receive Mode"
RB0=B4DLC.4,"Reserved bit 0<br> In Receive Mode"
DLC3=B4DLC.3,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC2=B4DLC.2,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC1=B4DLC.1,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC0=B4DLC.0,"Data Length Code bits<br> In Transmit or Receive Mode"
TXRTR=B4DLC.6,"Transmitter Remote Transmission Request bit<br> In Transmit Mode"

B4D0="TX/RX BUFFER 4 DATA FIELD BYTE 0 REGISTER IN TRANSMIT or RECEIVE MODE"
B4D1="TX/RX BUFFER 4 DATA FIELD BYTE 1 REGISTER IN TRANSMIT or RECEIVE MODE"
B4D2="TX/RX BUFFER 4 DATA FIELD BYTE 2 REGISTER IN TRANSMIT or RECEIVE MODE"
B4D3="TX/RX BUFFER 4 DATA FIELD BYTE 3 REGISTER IN TRANSMIT or RECEIVE MODE"
B4D4="TX/RX BUFFER 4 DATA FIELD BYTE 4 REGISTER IN TRANSMIT or RECEIVE MODE"
B4D5="TX/RX BUFFER 4 DATA FIELD BYTE 5 REGISTER IN TRANSMIT or RECEIVE MODE"
B4D6="TX/RX BUFFER 4 DATA FIELD BYTE 6 REGISTER IN TRANSMIT or RECEIVE MODE"
B4D7="TX/RX BUFFER 4 DATA FIELD BYTE 7 REGISTER IN TRANSMIT or RECEIVE MODE"



OPMODE2=CANSTAT_RO5.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO5.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO5.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO5.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO5.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO5.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO5.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO5.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO5.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO5.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO5.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO5.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO5.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO5.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO5.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO5.3,"Window Address bits Mode 0"
WIN1=CANCON_RO5.2,"Window Address bits Mode 0"
WIN0=CANCON_RO5.1,"Window Address bits Mode 0"
FP3=CANCON_RO5.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO5.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO5.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO5.0,"FIFO Read Pointer bits Mode 2"

RXFUL=B5CON.7,"Receive Full Status bit<br> In Receive Mode"
RXM1=B5CON.6,"Receive Buffer Mode bits<br> In Receive Mode"
RXRTRRO=B5CON.5,"Read-Only Remote Transmission Request for Received Message bit<br> In Receive Mode"
FILHIT4=B5CON.4,"Filter Hit bit<br> In Receive Mode"
FILHIT3=B5CON.3,"Filter Hit bit<br> In Receive Mode"
FILHIT2=B5CON.2,"Filter Hit bit<br> In Receive Mode"
FILHIT1=B5CON.1,"Filter Hit bit<br> In Receive Mode"
FILHIT0=B5CON.0,"Filter Hit bit<br> In Receive Mode"
TXBIF=B5CON.7,"Transmit Buffer Interrupt Flag bit<br> In Transmit Mode"
TXABT=B5CON.6,"Transmission Aborted Status bit<br> In Transmit Mode"
TXLARB=B5CON.5,"Transmission Lost Arbitration Status bit<br> In Transmit Mode"
TXERR=B5CON.4,"Transmission Error Detected Status bit<br> In Transmit Mode"
TXREQ=B5CON.3,"Transmit Request Status bit<br> In Transmit Mode"
RTREN=B5CON.2,"Automatic Remote Transmission Request Enable bit<br> In Transmit Mode"
TXPRI1=B5CON.1,"Transmit Priority bits<br> In Transmit Mode"
TXPRI0=B5CON.0,"Transmit Priority bits<br> In Transmit Mode"

B5SIDH="TX/RX BUFFER 5 STANDARD IDENTIFIER REGISTERS, <br>HIGH BYTE IN RECEIVE or TRANSMIT MODE <br>Standard Identifier Bits (SID10:SID3)"

SID2=B5SIDL.7,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID1=B5SIDL.6,"Standard Identifier bits<br> In Receive or Transmit Mode"
SID0=B5SIDL.5,"Standard Identifier bits<br> In Receive or Transmit Mode"
SRR=B5SIDL.4,"Substitute Remote Transmission Request bit<br> In Receive Mode"
EXID=B5SIDL.3,"Extended Identifier Enable bit<br> In Receive Mode"
EXIDE=B5SIDL.3,"Extended Identifier Enable bit<br> In Transmit Mode"
EID17=B5SIDL.1,"Extended Identifier bits<br> In Receive or Transmit Mode"
EID16=B5SIDL.0,"Extended Identifier bits<br> In Receive or Transmit ode"

B5EIDH="TX/RX BUFFER 5 EXTENDED IDENTIFIER REGISTER, HIGH BYTE IN RECEIVE or TRANSMIT MODE"
B5EIDL="TX/RX BUFFER 5 EXTENDED IDENTIFIER REGISTERS, LOW BYTE IN RECEIVE or TRANSMIT MODE"

RXRTR=B5DLC.6,"Receiver Remote Transmission Request bit<br>in Receive Mode"
RB1=B5DLC.5,"Reserved bit 1<br> In Receive Mode"
RB0=B5DLC.4,"Reserved bit 0<br> In Receive Mode"
DLC3=B5DLC.3,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC2=B5DLC.2,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC1=B5DLC.1,"Data Length Code bits<br> In Transmit or Receive Mode"
DLC0=B5DLC.0,"Data Length Code bits<br> In Transmit or Receive Mode"
TXRTR=B5DLC.6,"Transmitter Remote Transmission Request bit<br> In Transmit Mode"

B5D0="TX/RX BUFFER 5 DATA FIELD BYTE 0 REGISTER IN TRANSMIT or RECEIVE MODE"
B5D1="TX/RX BUFFER 5 DATA FIELD BYTE 1 REGISTER IN TRANSMIT or RECEIVE MODE"
B5D2="TX/RX BUFFER 5 DATA FIELD BYTE 2 REGISTER IN TRANSMIT or RECEIVE MODE"
B5D3="TX/RX BUFFER 5 DATA FIELD BYTE 3 REGISTER IN TRANSMIT or RECEIVE MODE"
B5D4="TX/RX BUFFER 5 DATA FIELD BYTE 4 REGISTER IN TRANSMIT or RECEIVE MODE"
B5D5="TX/RX BUFFER 5 DATA FIELD BYTE 5 REGISTER IN TRANSMIT or RECEIVE MODE"
B5D6="TX/RX BUFFER 5 DATA FIELD BYTE 6 REGISTER IN TRANSMIT or RECEIVE MODE"
B5D7="TX/RX BUFFER 5 DATA FIELD BYTE 7 REGISTER IN TRANSMIT or RECEIVE MODE"


OPMODE2=CANSTAT_RO4.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO4.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO4.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO4.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO4.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO4.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO4.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO4.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO4.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO4.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO4.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO4.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO4.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO4.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO4.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO4.3,"Window Address bits Mode 0"
WIN1=CANCON_RO4.2,"Window Address bits Mode 0"
WIN0=CANCON_RO4.1,"Window Address bits Mode 0"
FP3=CANCON_RO4.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO4.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO4.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO4.0,"FIFO Read Pointer bits Mode 2"


RXF0SIDH="RECEIVE ACCEPTANCE FILTER 0 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF0SIDL="RECEIVE ACCEPTANCE FILTER 0 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF0EIDH="RECEIVE ACCEPTANCE FILTER 0 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF0EIDL="RECEIVE ACCEPTANCE FILTER 0 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF1SIDH="RECEIVE ACCEPTANCE FILTER 1 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF1SIDL="RECEIVE ACCEPTANCE FILTER 1 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF1EIDH="RECEIVE ACCEPTANCE FILTER 1 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF1EIDL="RECEIVE ACCEPTANCE FILTER 1 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF2SIDH="RECEIVE ACCEPTANCE FILTER 2 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF2SIDL="RECEIVE ACCEPTANCE FILTER 2 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF2EIDH="RECEIVE ACCEPTANCE FILTER 2 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF2EIDL="RECEIVE ACCEPTANCE FILTER 2 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF3SIDH="RECEIVE ACCEPTANCE FILTER 3 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF3SIDL="RECEIVE ACCEPTANCE FILTER 3 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF3EIDH="RECEIVE ACCEPTANCE FILTER 3 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF3EIDL="RECEIVE ACCEPTANCE FILTER 3 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF4SIDH="RECEIVE ACCEPTANCE FILTER 4 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF4SIDL="RECEIVE ACCEPTANCE FILTER 4 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF4EIDH="RECEIVE ACCEPTANCE FILTER 4 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF4EIDL="RECEIVE ACCEPTANCE FILTER 4 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXF5SIDH="RECEIVE ACCEPTANCE FILTER 5 STANDARD IDENTIFIER FILTER REGISTER, HIGH BYTE"
RXF5SIDL="RECEIVE ACCEPTANCE FILTER 5 STANDARD IDENTIFIER FILTER REGISTER, Low Byte"
RXF5EIDH="RECEIVE ACCEPTANCE FILTER 5 EXTENDED IDENTIFIER REGISTER, HIGH BYTE"
RXF5EIDL="RECEIVE ACCEPTANCE FILTER 5 EXTENDED IDENTIFIER REGISTER, Low Byte"

RXM0SIDH="RECEIVE ACCEPTANCE MASK 0 STANDARD IDENTIFIER MASK REGISTERS, HIGH BYTE"
RXM0SIDL="RECEIVE ACCEPTANCE MASK 0 STANDARD IDENTIFIER MASK REGISTERS, LOW BYTE"
RXM0EIDH="RECEIVE ACCEPTANCE MASK 0 EXTENDED IDENTIFIER MASK REGISTERS, HIGH BYTE"
RXM0EIDL="RECEIVE ACCEPTANCE MASK 0 EXTENDED IDENTIFIER MASK REGISTERS, LOW BYTE"

RXM1SIDH="RECEIVE ACCEPTANCE MASK 1 STANDARD IDENTIFIER MASK REGISTERS, HIGH BYTE"
RXM1SIDL="RECEIVE ACCEPTANCE MASK 1 STANDARD IDENTIFIER MASK REGISTERS, LOW BYTE"
RXM1EIDH="RECEIVE ACCEPTANCE MASK 1 EXTENDED IDENTIFIER MASK REGISTERS, HIGH BYTE"
RXM1EIDL="RECEIVE ACCEPTANCE MASK 1 EXTENDED IDENTIFIER MASK REGISTERS, LOW BYTE"

TXBIF=TXB2CON.7,"Transmit Buffer Interrupt Flag bit"
TXABT=TXB2CON.6,"Transmission Aborted Status bit"
TXLARB=TXB2CON.5,"Transmission Lost Arbitration Status bit"
TXERR=TXB2CON.4,"Transmission Error Detected Status bit"
TXREQ=TXB2CON.3,"Transmit Request Status bit"
TXPRI1=TXB2CON.1,"Transmit Priority bits"
TXPRI0=TXB2CON.0,"Transmit Priority bits"

TXB2SIDH="TRANSMIT BUFFER 2 STANDARD IDENTIFIER REGISTERS, HIGH BYTE"
TXB2SIDL="TRANSMIT BUFFER 2 STANDARD IDENTIFIER REGISTERS, LOW BYTE"
TXB2EIDH="TRANSMIT BUFFER 2 EXTENDED IDENTIFIER REGISTERS, HIGH BYTE"
TXB2EIDL="TRANSMIT BUFFER 2 EXTENDED IDENTIFIER REGISTERS, LOW BYTE"
TXRTR=TXB2DLC.6,"Transmit Remote Frame Transmission Request bit"
DLC3=TXB2DLC.3,"Data Length Code bits"
DLC2=TXB2DLC.2,"Data Length Code bits"
DLC1=TXB2DLC.1,"Data Length Code bits"
DLC0=TXB2DLC.0,"Data Length Code bits"
TXB2D0="TRANSMIT BUFFER 2 DATA FIELD BYTE 0 REGISTER"
TXB2D1="TRANSMIT BUFFER 2 DATA FIELD BYTE 1 REGISTER"
TXB2D2="TRANSMIT BUFFER 2 DATA FIELD BYTE 2 REGISTER"
TXB2D3="TRANSMIT BUFFER 2 DATA FIELD BYTE 3 REGISTER"
TXB2D4="TRANSMIT BUFFER 2 DATA FIELD BYTE 4 REGISTER"
TXB2D5="TRANSMIT BUFFER 2 DATA FIELD BYTE 5 REGISTER"
TXB2D6="TRANSMIT BUFFER 2 DATA FIELD BYTE 6 REGISTER"
TXB2D7="TRANSMIT BUFFER 2 DATA FIELD BYTE 7 REGISTER"

OPMODE2=CANSTAT_RO3.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO3.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO3.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO3.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO3.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO3.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO3.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO3.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO3.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO3.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO3.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO3.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO3.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO3.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO3.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO3.3,"Window Address bits Mode 0"
WIN1=CANCON_RO3.2,"Window Address bits Mode 0"
WIN0=CANCON_RO3.1,"Window Address bits Mode 0"
FP3=CANCON_RO3.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO3.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO3.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO3.0,"FIFO Read Pointer bits Mode 2"


TXBIF=TXB1CON.7,"Transmit Buffer Interrupt Flag bit"
TXABT=TXB1CON.6,"Transmission Aborted Status bit"
TXLARB=TXB1CON.5,"Transmission Lost Arbitration Status bit"
TXERR=TXB1CON.4,"Transmission Error Detected Status bit"
TXREQ=TXB1CON.3,"Transmit Request Status bit"
TXPRI1=TXB1CON.1,"Transmit Priority bits"
TXPRI0=TXB1CON.0,"Transmit Priority bits"

TXB1SIDH="TRANSMIT BUFFER 1 STANDARD IDENTIFIER REGISTERS, HIGH BYTE"
TXB1SIDL="TRANSMIT BUFFER 1 STANDARD IDENTIFIER REGISTERS, LOW BYTE"
TXB1EIDH="TRANSMIT BUFFER 1 EXTENDED IDENTIFIER REGISTERS, HIGH BYTE"
TXB1EIDL="TRANSMIT BUFFER 1 EXTENDED IDENTIFIER REGISTERS, LOW BYTE"
TXRTR=TXB1DLC.6,"Transmit Remote Frame Transmission Request bit"
DLC3=TXB1DLC.3,"Data Length Code bits"
DLC2=TXB1DLC.2,"Data Length Code bits"
DLC1=TXB1DLC.1,"Data Length Code bits"
DLC0=TXB1DLC.0,"Data Length Code bits"
TXB1D0="TRANSMIT BUFFER 1 DATA FIELD BYTE 0 REGISTER"
TXB1D1="TRANSMIT BUFFER 1 DATA FIELD BYTE 1 REGISTER"
TXB1D2="TRANSMIT BUFFER 1 DATA FIELD BYTE 2 REGISTER"
TXB1D3="TRANSMIT BUFFER 1 DATA FIELD BYTE 3 REGISTER"
TXB1D4="TRANSMIT BUFFER 1 DATA FIELD BYTE 4 REGISTER"
TXB1D5="TRANSMIT BUFFER 1 DATA FIELD BYTE 5 REGISTER"
TXB1D6="TRANSMIT BUFFER 1 DATA FIELD BYTE 6 REGISTER"
TXB1D7="TRANSMIT BUFFER 1 DATA FIELD BYTE 7 REGISTER"

OPMODE2=CANSTAT_RO2.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO2.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO2.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO2.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO2.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO2.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO2.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO2.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO2.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO2.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO2.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO2.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO2.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO2.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO2.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO2.3,"Window Address bits Mode 0"
WIN1=CANCON_RO2.2,"Window Address bits Mode 0"
WIN0=CANCON_RO2.1,"Window Address bits Mode 0"
FP3=CANCON_RO2.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO2.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO2.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO2.0,"FIFO Read Pointer bits Mode 2"


TXBIF=TXB0CON.7,"Transmit Buffer Interrupt Flag bit"
TXABT=TXB0CON.6,"Transmission Aborted Status bit"
TXLARB=TXB0CON.5,"Transmission Lost Arbitration Status bit"
TXERR=TXB0CON.4,"Transmission Error Detected Status bit"
TXREQ=TXB0CON.3,"Transmit Request Status bit"
TXPRI1=TXB0CON.1,"Transmit Priority bits"
TXPRI0=TXB0CON.0,"Transmit Priority bits"

TXB0SIDH="TRANSMIT BUFFER 0 STANDARD IDENTIFIER REGISTERS, HIGH BYTE"
TXB0SIDL="TRANSMIT BUFFER 0 STANDARD IDENTIFIER REGISTERS, LOW BYTE"
TXB0EIDH="TRANSMIT BUFFER 0 EXTENDED IDENTIFIER REGISTERS, HIGH BYTE"
TXB0EIDL="TRANSMIT BUFFER 0 EXTENDED IDENTIFIER REGISTERS, LOW BYTE"
TXRTR=TXB0DLC.6,"Transmit Remote Frame Transmission Request bit"
DLC3=TXB0DLC.3,"Data Length Code bits"
DLC2=TXB0DLC.2,"Data Length Code bits"
DLC1=TXB0DLC.1,"Data Length Code bits"
DLC0=TXB0DLC.0,"Data Length Code bits"
TXB0D0="TRANSMIT BUFFER 0 DATA FIELD BYTE 0 REGISTER"
TXB0D1="TRANSMIT BUFFER 0 DATA FIELD BYTE 1 REGISTER"
TXB0D2="TRANSMIT BUFFER 0 DATA FIELD BYTE 2 REGISTER"
TXB0D3="TRANSMIT BUFFER 0 DATA FIELD BYTE 3 REGISTER"
TXB0D4="TRANSMIT BUFFER 0 DATA FIELD BYTE 4 REGISTER"
TXB0D5="TRANSMIT BUFFER 0 DATA FIELD BYTE 5 REGISTER"
TXB0D6="TRANSMIT BUFFER 0 DATA FIELD BYTE 6 REGISTER"
TXB0D7="TRANSMIT BUFFER 0 DATA FIELD BYTE 7 REGISTER"

OPMODE2=CANSTAT_RO1.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO1.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO1.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO1.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO1.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO1.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO1.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO1.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO1.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO1.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO1.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO1.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO1.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO1.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO1.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO1.3,"Window Address bits Mode 0"
WIN1=CANCON_RO1.2,"Window Address bits Mode 0"
WIN0=CANCON_RO1.1,"Window Address bits Mode 0"
FP3=CANCON_RO1.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO1.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO1.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO1.0,"FIFO Read Pointer bits Mode 2"

RXFUL=RXB1CON.7,"Receive Full Status bit<br> Mode 0,1,2"
RXM1=RXB1CON.6,"Receive Buffer Mode bits<br> Mode 0,1,2"
RXM0=RXB1CON.5,"Receive Buffer Mode bits<br> Mode 0" 
RTRRO=RXB1CON.5,"Remote Transmission Request bit for Received Message<br> Mode 1,2"
FILHIT4=RXB1CON.4,"Filter Hit bit<br> Mode 1,2"
RXRTRRO=RXB1CON.3,"Remote Transmission Request bit for Received Message<br> Mode 0"
FILHIT2=RXB1CON.2,"Filter Hit bit<br> Mode 0,1,2"
FILHIT1=RXB1CON.1,"Filter Hit bit<br> Mode 0,1,2"
FILHIT0=RXB1CON.0,"Filter Hit bit<br> Mode 0,1,2"

RXB1SIDH="RECEIVE BUFFER 1 STANDARD IDENTIFIER REGISTERS, HIGH BYTE"
RXB1SIDL="RECEIVE BUFFER 1 STANDARD IDENTIFIER REGISTERS, LOW BYTE"
RXB1EIDH="RECEIVE BUFFER 1 EXTENDED IDENTIFIER REGISTERS, HIGH BYTE"
RXB1EIDL="RECEIVE BUFFER 1 EXTENDED IDENTIFIER REGISTERS, LOW BYTE"

RXRTR=RXB1DLC.6,"Receiver Remote Transmission Request bit"
RB1=RXB1DLC.5,"Reserved bit 1"
RB0=RXB1DLC.4,"Reserved bit 0"
DLC3=RXB1DLC.3,"Data Length Code bits"
DLC2=RXB1DLC.2,"Data Length Code bits"
DLC1=RXB1DLC.1,"Data Length Code bits"
DLC0=RXB1DLC.0,"Data Length Code bits"

RXB1D0="RECEIVE BUFFER 1 DATA FIELD BYTE 0 REGISTER"
RXB1D1="RECEIVE BUFFER 1 DATA FIELD BYTE 1 REGISTER"
RXB1D2="RECEIVE BUFFER 1 DATA FIELD BYTE 2 REGISTER"
RXB1D3="RECEIVE BUFFER 1 DATA FIELD BYTE 3 REGISTER"
RXB1D4="RECEIVE BUFFER 1 DATA FIELD BYTE 4 REGISTER"
RXB1D5="RECEIVE BUFFER 1 DATA FIELD BYTE 5 REGISTER"
RXB1D6="RECEIVE BUFFER 1 DATA FIELD BYTE 6 REGISTER"
RXB1D7="RECEIVE BUFFER 1 DATA FIELD BYTE 7 REGISTER"

OPMODE2=CANSTAT_RO0.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT_RO0.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT_RO0.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT_RO0.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT_RO0.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT_RO0.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT_RO0.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT_RO0.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT_RO0.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT_RO0.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT_RO0.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON_RO0.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON_RO0.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON_RO0.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON_RO0.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON_RO0.3,"Window Address bits Mode 0"
WIN1=CANCON_RO0.2,"Window Address bits Mode 0"
WIN0=CANCON_RO0.1,"Window Address bits Mode 0"
FP3=CANCON_RO0.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON_RO0.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON_RO0.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON_RO0.0,"FIFO Read Pointer bits Mode 2"


RXFUL=RXB0CON.7,"Receive Full Status bit<br> Mode 0,1,2"
RXM1=RXB0CON.6,"Receive Buffer Mode bits<br> Mode 0,1,2"
RXM0=RXB0CON.5,"Receive Buffer Mode bits<br> Mode 0" 
RTRRO=RXB0CON.5,"Remote Transmission Request bit for Received Message<br> Mode 1,2"
FILHIT4=RXB0CON.4,"Filter Hit bit<br> Mode 1,2"
RXRTRRO=RXB0CON.3,"Remote Transmission Request bit for Received Message<br> Mode 0"
FILHIT2=RXB0CON.2,"Filter Hit bit<br> Mode 0,1,2"
FILHIT1=RXB0CON.1,"Filter Hit bit<br> Mode 0,1,2"
FILHIT0=RXB0CON.0,"Filter Hit bit<br> Mode 0,1,2"

RXB0SIDH="RECEIVE BUFFER 0 STANDARD IDENTIFIER REGISTERS, HIGH BYTE"
RXB0SIDL="RECEIVE BUFFER 0 STANDARD IDENTIFIER REGISTERS, LOW BYTE"
RXB0EIDH="RECEIVE BUFFER 0 EXTENDED IDENTIFIER REGISTERS, HIGH BYTE"
RXB0EIDL="RECEIVE BUFFER 0 EXTENDED IDENTIFIER REGISTERS, LOW BYTE"

RXRTR=RXB0DLC.6,"Receiver Remote Transmission Request bit"
RB1=RXB0DLC.5,"Reserved bit 1"
RB0=RXB0DLC.4,"Reserved bit 0"
DLC3=RXB0DLC.3,"Data Length Code bits"
DLC2=RXB0DLC.2,"Data Length Code bits"
DLC1=RXB0DLC.1,"Data Length Code bits"
DLC0=RXB0DLC.0,"Data Length Code bits"

RXB0D0="RECEIVE BUFFER 0 DATA FIELD BYTE 0 REGISTER"
RXB0D1="RECEIVE BUFFER 0 DATA FIELD BYTE 1 REGISTER"
RXB0D2="RECEIVE BUFFER 0 DATA FIELD BYTE 2 REGISTER"
RXB0D3="RECEIVE BUFFER 0 DATA FIELD BYTE 3 REGISTER"
RXB0D4="RECEIVE BUFFER 0 DATA FIELD BYTE 4 REGISTER"
RXB0D5="RECEIVE BUFFER 0 DATA FIELD BYTE 5 REGISTER"
RXB0D6="RECEIVE BUFFER 0 DATA FIELD BYTE 6 REGISTER"
RXB0D7="RECEIVE BUFFER 0 DATA FIELD BYTE 7 REGISTER"

OPMODE2=CANSTAT.7,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE1=CANSTAT.6,"Operation Mode Status bits,<br> Modes 0,1,2"
OPMODE0=CANSTAT.5,"Operation Mode Status bits,<br> Modes 0,1,2"
EICODE4=CANSTAT.4,"Interrupt Code bits,<br> Modes 1,2"
EICODE3=CANSTAT.3,"Interrupt Code bits,<br> Modes 1,2"
EICODE2=CANSTAT.2,"Interrupt Code bits,<br> Modes 1,2"
EICODE1=CANSTAT.1,"Interrupt Code bits,<br> Modes 1,2"
EICODE0=CANSTAT.0,"Interrupt Code bits,<br> Modes 1,2"
ICODE3=CANSTAT.3,"Interrupt Code bits,<br> Modes 0"
ICODE2=CANSTAT.2,"Interrupt Code bits,<br> Modes 0"
ICODE1=CANSTAT.1,"Interrupt Code bits,<br> Modes 0"

REQOP2=CANCON.7,"Request CAN Operation Mode 0,1,2 bits"
REQOP1=CANCON.6,"Request CAN Operation Mode 0,1,2 bits"
REQOP0=CANCON.5,"Request CAN Operation Mode 0,1,2 bits"
ABAT=CANCON.4,"Abort All Pending Transmissions bit Mode 0,1,2"
WIN2=CANCON.3,"Window Address bits Mode 0"
WIN1=CANCON.2,"Window Address bits Mode 0"
WIN0=CANCON.1,"Window Address bits Mode 0"
FP3=CANCON.3,"FIFO Read Pointer bits Mode 2"
FP2=CANCON.2,"FIFO Read Pointer bits Mode 2"
FP1=CANCON.1,"FIFO Read Pointer bits Mode 2"
FP0=CANCON.0,"FIFO Read Pointer bits Mode 2"

SJW1=BRGCON1.7,"Synchronized Jump Width bits"
SJW0=BRGCON1.6,"Synchronized Jump Width bits"
BRP5=BRGCON1.5,"Baud Rate Prescaler bits"
BRP4=BRGCON1.4,"Baud Rate Prescaler bits"
BRP3=BRGCON1.3,"Baud Rate Prescaler bits"
BRP2=BRGCON1.2,"Baud Rate Prescaler bits"
BRP1=BRGCON1.1,"Baud Rate Prescaler bits"
BRP0=BRGCON1.0,"Baud Rate Prescaler bits"

SEG2PHTS=BRGCON2.7,"Phase Segment 2 Time Select bit"
SAM=BRGCON2.6,"Sample of the CAN bus Line bit"
SEG1PH2=BRGCON2.5,"Phase Segment 1 bits"
SEG1PH1=BRGCON2.4,"Phase Segment 1 bits"
SEG1PH0=BRGCON2.3,"Phase Segment 1 bits"
PRSEG2=BRGCON2.2,"Propagation Time Select bits"
PRSEG1=BRGCON2.1,"Propagation Time Select bits"
PRSEG0=BRGCON2.0,"Propagation Time Select bits"

WAKDIS=BRGCON3.7,"Wake-up Disable bit"
WAKFIL=BRGCON3.6,"Selects CAN bus Line Filter for Wake-up bit"
SEG2PH2=BRGCON3.2,"Phase Segment 2 Time Select bits"
SEG2PH1=BRGCON3.1,"Phase Segment 2 Time Select bits"
SEG2PH0=BRGCON3.0,"Phase Segment 2 Time Select bits"

ENDRHI=CIOCON.5,"Enable Drive High bit"
CANCAP=CIOCON.4,"CAN Message Receive Capture Enable bit"

RXB0OVFL=COMSTAT.7,"Receive Buffer 0 Overflow bit<br> Mode 0"
NOT_FIFOEMPTY=COMSTAT.7,"FIFO Not Empty bit<br> Mode 2"
RXB1OVFL=COMSTAT.6,"Receive Buffer 1 Overflow bit<br> Mode 0"
RXBnOVFL=COMSTAT.6,"Receive Buffer n Overflow bit<br> Mode 1,2"
TXBO=COMSTAT.5,"Transmitter Bus-Off bit<br> Mode 0,1,2"
TXBP=COMSTAT.4,"Transmitter Bus Passive bit<br> Mode 0,1,2"
RXBP=COMSTAT.3,"Receiver Bus Passive bit<br> Mode 0,1,2"
TXWARN=COMSTAT.2,"Transmitter Warning bit<br> Mode 0,1,2"
RXWARN=COMSTAT.1,"Receiver Warning bit<br> Mode 0,1,2"
EWARN=COMSTAT.0,"Error Warning bit<br> Mode 0,1,2"

RXERRCNT="RECEIVE ERROR COUNT REGISTER"
TXERRCNT="TRANSMIT ERROR COUNT REGISTER"

MDSEL1=ECANCON.7,"Mode Select bits"
MDSEL0=ECANCON.6,"Mode Select bits"
FIFOWM=ECANCON.5,"FIFO High Water Mark bit"
EWIN4=ECANCON.4,"Enhanced Window Address bits"
EWIN3=ECANCON.3,"Enhanced Window Address bits"
EWIN2=ECANCON.2,"Enhanced Window Address bits"
EWIN1=ECANCON.1,"Enhanced Window Address bits"
EWIN0=ECANCON.0,"Enhanced Window Address bits"

NOT_MCLR=PORTE.3,"Master Clear (Reset) input"
VPP=PORTE.3,"High-voltage ICSP programming enable pin"
RE3=PORTE.3,"Digital input. Available only when MCLR is disabled"

RA0=PORTA.0,"Bidirectional Digital I/O"
AN0=PORTA.0,"Analog input 0"
CVREF=PORTA.0,"Comparator reference voltage output"
RA1=PORTA.1,"Bidirectional Digital I/O"
AN1=PORTA.1,"Analog input 1"
RA2=PORTA.2,"Bidirectional Digital I/O"
AN2=PORTA.2,"Analog input 2"
VREF_MINUS=PORTA.2,"A/D Reference Voltage (Low) input"
RA3=PORTA.3,"Bidirectional Digital I/O"
AN3=PORTA.3,"Analog input 3"
VREF_PLUS=PORTA.3,"A/D Reference Voltage (High) input"
RA4=PORTA.4,"Bidirectional Digital I/O"
T0CKI=PORTA.4,"Timer0 external clock input"
RA5=PORTA.5,"Bidirectional Digital I/O"
AN4=PORTA.5,"Analog input 4"
NOT_SS=PORTA.5,"SPI™ slave select input"
HLVDIN=PORTA.5,"High/Low-Voltage Detect input"
RA6=PORTA.6,"General purpose I/O pin"
CLKO=PORTA.6,"In RC mode, OSC2 pin outputs CLKO, which has 1/4 the <br>frequency of OSC1 and denotes the instruction cycle rate"
OSC2=PORTA.6,"Oscillator crystal output. Connects to crystal or resonator <br>in Crystal Oscillator mode"
RA7=PORTA.7,"General purpose I/O pin"
CLKI=PORTA.7,"External clock source input. Always associated with pin <br>function OSC1. (See related OSC1/CLKI, OSC2/CLKO pins.)"
OSC1=PORTA.7,"Oscillator crystal input or external clock source input. <br>ST buffer when configured in RC mode, CMOS otherwise"

RB0=PORTB.0,"Bidirectional Digital I/O"
INT0=PORTB.0,"External interrupt 0"
FLT0=PORTB.0,"Enhanced PWM Fault input (ECCP1 module)"
AN10=PORTB.0,"Analog input 10"
RB1=PORTB.1,"Bidirectional Digital I/O"
INT1=PORTB.1,"External interrupt 1"
AN8=PORTB.1,"Analog input 8"
RB2=PORTB.2,"Bidirectional Digital I/O"
INT2=PORTB.2,"External interrupt 2"
CANTX=PORTB.2,"CAN bus TX"
RB3=PORTB.3,"Bidirectional Digital I/O"
CANRX=PORTB.3,"CAN bus RX"
RB4=PORTB.4,"Bidirectional Digital I/O"
KBI0=PORTB.4,"Interrupt-on-change pin"
AN9=PORTB.4,"Analog input 9"
RB5=PORTB.5,"Bidirectional Digital I/O"
KBI1=PORTB.5,"Interrupt-on-change pin"
PGM=PORTB.5,"Low-Voltage ICSP™ Programming enable pin"
RB6=PORTB.6,"Bidirectional Digital I/O"
KBI2=PORTB.6,"Interrupt-on-change pin"
PGC=PORTB.6,"In-Circuit Debugger and ICSP programming clock pin"
RB7=PORTB.7,"Bidirectional Digital I/O"
KBI3=PORTB.7,"Interrupt-on-change pin"
PGD=PORTB.7,"In-Circuit Debugger and ICSP programming data pin"

RC0=PORTC.0,"Bidirectional Digital I/O"
T1OSO=PORTC.0,"Timer1 oscillator output"
T13CKI=PORTC.0,"Timer1/Timer3 external clock input
RC1=PORTC.1,"Bidirectional Digital I/O"
T1OSI=PORTC.1,"Timer1 oscillator input"
RC2=PORTC.2,"Bidirectional Digital I/O"
CCP1=PORTC.2,"Capture1 input/Compare1 output/PWM1 output"
RC3=PORTC.3,"Bidirectional Digital I/O"
SCK=PORTC.3,"Synchronous serial clock input/output for SPI mode"
SCL=PORTC.3,"Synchronous serial clock input/output for I2C mode"
RC4=PORTC.4,"Bidirectional Digital I/O"
SDI=PORTC.4,"SPI™ data in"
SDA=PORTC.4,"I2C™ data I/O"
RC5=PORTC.5,"Bidirectional Digital I/O"
SDO=PORTC.5,"SPI data out"
RC6=PORTC.6,"Bidirectional Digital I/O"
TX=PORTC.6,"EUSART Asynchronous Transmit"
CK=PORTC.6,"EUSART Synchronous Clock (see related RX/DT)"
RC7=PORTC.7,"Bidirectional Digital I/O"
RX=PORTC.7,"EUSART Asynchronous Receive"
DT=PORTC.7,"EUSART Synchronous Data (see related TX/CK)"

RD0=PORTD.0,"Bidirectional Digital I/O"
PSP0=PORTD.0,"Parallel Slave Port data"
C1IN_PLUS=PORTD.0,"Comparator 1 input (+)"
RD1=PORTD.1,"Bidirectional Digital I/O"
PSP1=PORTD.1,"Parallel Slave Port data"
C1IN_MINUS=PORTD.1,"Comparator 1 input (-)"
RD2=PORTD.2,"Bidirectional Digital I/O"
PSP2=PORTD.2,"Parallel Slave Port data"
C2IN_PLUS=PORTD.2,"Comparator 2 input (+)"
RD3=PORTD.3,"Bidirectional Digital I/O"
PSP3=PORTD.3,"Parallel Slave Port data"
C2IN_MINUS=PORTD.3,"Comparator 2 input (-)"
RD4=PORTD.4,"Bidirectional Digital I/O"
PSP4=PORTD.4,"Parallel Slave Port data"
ECCP1=PORTD.4,"Capture2 input/Compare2 output/PWM2 output"
P1A=PORTD.4,"ECCP1 PWM output A"
RD5=PORTD.5,"Bidirectional Digital I/O"
PSP5=PORTD.5,"Parallel Slave Port data"
P1B=PORTD.5,"ECCP1 PWM output B"
RD6=PORTD.6,"Bidirectional Digital I/O"
PSP6=PORTD.6,"Parallel Slave Port data"
P1C=PORTD.6,"ECCP1 PWM output C"
RD7=PORTD.7,"Bidirectional Digital I/O"
PSP7=PORTD.7,"Parallel Slave Port data"
P1D=PORTD.7,"ECCP1 PWM output D"

RE0=PORTE.0,"Bidirectional Digital I/O"
NOT_RD=PORTE.0,"Read control for Parallel Slave Port"
AN5=PORTE.0,"Analog input 5"
RE1=PORTE.1,"Bidirectional Digital I/O"
NOT_WR=PORTE.1,"Write control for Parallel Slave Port"
AN6=PORTE.1,"Analog input 6"
C1OUT=PORTE.1,"Comparator 1 output"
RE2=PORTE.2,"Bidirectional Digital I/O"
NOT_CS=PORTE.2,"Chip select control for Parallel Slave Port"
AN7=PORTE.2,"Analog input 7"
C2OUT=PORTE.2,"Comparator 2 output"

LATE="Read PORTE Data Latch, Write PORTE Data Latch"
LATD="Read PORTD Data Latch, Write PORTD Data Latch"
LATC="Read PORTC Data Latch, Write PORTC Data Latch"
LATB="Read PORTB Data Latch, Write PORTB Data Latch"
LATA="Read PORTA Data Latch, Write PORTA Data Latch"

TRISA="Data Direction Control Register for PORTA"
TRISB="Data Direction Control Register for PORTB"
TRISC="Data Direction Control Register for PORTC"
TRISE="Data Direction Control Register for PORTE"
TRISD="Data Direction Control Register for PORTD"



INTSRC=OSCTUNE.7,"Internal Oscillator Low-Frequency Source Select bit"
PLLEN=OSCTUNE.6,"Frequency Multiplier PLL for INTOSC Enable bit"
TUN4=OSCTUNE.4,"Frequency Tuning bits"
TUN3=OSCTUNE.3,"Frequency Tuning bits"
TUN2=OSCTUNE.2,"Frequency Tuning bits"
TUN1=OSCTUNE.1,"Frequency Tuning bits"
TUN0=OSCTUNE.0,"Frequency Tuning bits"

PSPIE=PIE1.7,"Parallel Slave Port Read/Write Interrupt Enable bit<br>This bit is unimplemented on 28-pin devices and is read as ‘0’"
ADIE=PIE1.6,"A/D Converter Interrupt Enable bit"
RCIE=PIE1.5,"EUSART Receive Interrupt Enable bit"
TXIE=PIE1.4,"EUSART Transmit Interrupt Enable bit"
SSPIE=PIE1.3,"Master Synchronous Serial Port Interrupt Enable bit"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable bit"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable bit"
TMR1IE=PIE1.0,"TMR1 Overflow Interrupt Enable bit"

PSPIF=PIR1.7,"Parallel Slave Port Read/Write Interrupt Flag bit<br>This bit is unimplemented on 28-pin devices and is read as ‘0’"
ADIF=PIR1.6,"A/D Converter Interrupt Flag bit"
RCIF=PIR1.5,"EUSART Receive Interrupt Flag bit"
TXIF=PIR1.4,"EUSART Transmit Interrupt Flag bit"
SSPIF=PIR1.3,"Master Synchronous Serial Port Interrupt Flag bit"
CCP1IF=PIR1.2,"CCP1 Interrupt Flag bit"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag bit"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag bit"

PSPIP=IPR1.7,"Parallel Slave Port Read/Write Interrupt Priority bit<br>This bit is unimplemented on 28-pin devices and is read as ‘0’"
ADIP=IPR1.6,"A/D Converter Interrupt Priority bit"
RCIP=IPR1.5,"EUSART Receive Interrupt Priority bit"
TXIP=IPR1.4,"EUSART Transmit Interrupt Priority bit"
SSPIP=IPR1.3,"Master Synchronous Serial Port Interrupt Priority bit"
CCP1IP=IPR1.2,"CCP1 Interrupt Priority bit"
TMR2IP=IPR1.1,"TMR2 to PR2 Match Interrupt Priority bit"
TMR1IP=IPR1.0,"TMR1 Overflow Interrupt Priority bit"

OSCFIE=PIE2.7,"Oscillator Fail Interrupt Enable bit"
CMIE=PIE2.6,"Comparator Interrupt Enable bit"
EEIE=PIE2.4,"Data EEPROM/Flash Write Operation Interrupt Enable bit"
BCLIE=PIE2.3,"Bus Collision Interrupt Enable bit"
HLVDIE=PIE2.2,"High/Low Voltage Detect Interrupt Enable bit"
TMR3IE=PIE2.1,"TMR3 Overflow Interrupt Enable bit"
ECCP2IE=PIE2.0,"CCP2 Interrupt Enable bit"

OSCFIF=PIR2.7,"Oscillator Fail Interrupt Flag bit"
CMIF=PIR2.6,"Comparator Interrupt Flag bit"
EEIF=PIR2.4,"Data EEPROM/Flash Write Operation Interrupt Flag bit"
BCLIF=PIR2.3,"Bus Collision Interrupt Flag bit"
HLVDIF=PIR2.2,"High/Low Voltage Detect Interrupt Flag bit"
TMR3IF=PIR2.1,"TMR3 Overflow Interrupt Flag bit"
ECCP2IF=PIR2.0,"CCP2 Interrupt Flag bit"

OSCFIP=IPR2.7,"Oscillator Fail Interrupt Priority bit"
CMIP=IPR2.6,"Comparator Interrupt Priority bit"
EEIP=IPR2.4,"Data EEPROM/Flash Write Operation Interrupt Priority bit"
BCLIP=IPR2.3,"Bus Collision Interrupt Priority bit "
HLVDIP=IPR2.2,"High/Low Voltage Detect Interrupt Priority bit"
TMR3IP=IPR2.1,"TMR3 Overflow Interrupt Priority bit "
ECCP2IP=IPR2.0,"CCP2 Interrupt Priority bit"

IRXIE=PIE3.7,"CAN Invalid Received Message Interrupt Enable bit, Mode 0,1,2"
WAKIE=PIE3.6,"CAN bus Activity Wake-up Interrupt Enable bit, Mode 0,1,2"
ERRIE=PIE3.5,"CAN bus Error Interrupt Enable bit, Mode 0,1,2"
TXB2IE=PIE3.4,"CAN Transmit Buffer 2 Interrupt Enable bit, Mode 0"
TXBnIE=PIE3.4,"CAN Transmit Buffer Interrupts Enable bit, Mode 1,2"
TXB1IE=PIE3.3,"CAN Transmit Buffer 1 Interrupt Enable bit, Mode 0,1,2"
TXB0IE=PIE3.2,"CAN Transmit Buffer 0 Interrupt Enable bit, Mode 0,1,2"
RXB1IE=PIE3.1,"CAN Receive Buffer 1 Interrupt Enable bit, Mode 0"
RXBnIE=PIE3.1,"CAN Receive Buffer Interrupts Enable bit, Mode 1,2"
RXB0IE=PIE3.0,"CAN Receive Buffer 0 Interrupt Enable bit, Mode 0"
FIFOWMIE=PIE3.0,"FIFO Watermark Interrupt Enable bit, Mode 2"

IRXIP=IPR3.7,"CAN Invalid Received Message Interrupt Enable bit, Mode 0,1,2"
WAKIP=IPR3.6,"CAN bus Activity Wake-up Interrupt Enable bit, Mode 0,1,2"
ERRIP=IPR3.5,"CAN bus Error Interrupt Enable bit, Mode 0,1,2"
TXB2IP=IPR3.4,"CAN Transmit Buffer 2 Interrupt Enable bit, Mode 0"
TXBnIP=IPR3.4,"CAN Transmit Buffer Interrupts Enable bit, Mode 1,2"
TXB1IP=IPR3.3,"CAN Transmit Buffer 1 Interrupt Enable bit, Mode 0,1,2"
TXB0IP=IPR3.2,"CAN Transmit Buffer 0 Interrupt Enable bit, Mode 0,1,2"
RXB1IP=IPR3.1,"CAN Receive Buffer 1 Interrupt Enable bit, Mode 0"
RXBnIP=IPR3.1,"CAN Receive Buffer Interrupts Enable bit, Mode 1,2"
RXB0IP=IPR3.0,"CAN Receive Buffer 0 Interrupt Enable bit, Mode 0"
FIFOWMIP=IPR3.0,"FIFO Watermark Interrupt Enable bit, Mode 2"

IRXIF=PIR3.7,"CAN Invalid Received Message Interrupt Enable bit, Mode 0,1,2"
WAKIF=PIR3.6,"CAN bus Activity Wake-up Interrupt Enable bit, Mode 0,1,2"
ERRIF=PIR3.5,"CAN bus Error Interrupt Enable bit, Mode 0,1,2"
TXB2IF=PIR3.4,"CAN Transmit Buffer 2 Interrupt Enable bit, Mode 0"
TXBnIF=PIR3.4,"CAN Transmit Buffer Interrupts Enable bit, Mode 1,2"
TXB1IF=PIR3.3,"CAN Transmit Buffer 1 Interrupt Enable bit, Mode 0,1,2"
TXB0IF=PIR3.2,"CAN Transmit Buffer 0 Interrupt Enable bit, Mode 0,1,2"
RXB1IF=PIR3.1,"CAN Receive Buffer 1 Interrupt Enable bit, Mode 0"
RXBnIF=PIR3.1,"CAN Receive Buffer Interrupts Enable bit, Mode 1,2"
RXB0IF=PIR3.0,"CAN Receive Buffer 0 Interrupt Enable bit, Mode 0"
FIFOWMIF=PIR3.0,"FIFO Watermark Interrupt Enable bit, Mode 2"

EEPGD=EECON1.7,"FLASH Program or Data EEPROM Memory Select bit"
CFGS=EECON1.6,"FLASH Program/Data EEPROM or Configuration Select bit"
FREE=EECON1.4,"FLASH Row Erase Enable bit"
WRERR=EECON1.3,"EEPROM Error Flag"
WREN=EECON1.2,"EEPROM Write/Enable"
WR=EECON1.1,"Write Control"
RD=EECON1.0,"Read Control"

EECON2="EEPROM control register2 (not a physical register)"
EEADR="Data EEPROM Address Register"
EEDATA="Data EEPROM Data Register"
EEADRH="Data EEPROM Address register High Byte"

SPEN=RCSTA.7,"Serial Port Enable (Usart 1)"
RX9=RCSTA.6,"9-bit Receive Enable (Usart 1)"
SREN=RCSTA.5,"Single Receive Enable (Usart 1)"
CREN=RCSTA.4,"Continuous Receive Enable (Usart 1)"
ADDEN=RCSTA.3,"Address Detect Enable (Usart 1)"
FERR=RCSTA.2,"Framing Error (Usart 1)"
OERR=RCSTA.1,"Overrun Error (Usart 1)"
RX9D=RCSTA.0,"9th bit of received data (Can be parity bit) (Usart 1)"

CSRC=TXSTA.7,"Clock Source Select bit (Usart 1)"
TX9=TXSTA.6,"9-bit Transmit Enable (Usart 1)"
TXEN=TXSTA.5,"Transmit Enable (Usart 1)"
SENDB=TXSTA.3,"Send Break Character bit"
SYNC=TXSTA.4,"USART Mode Select bit (Usart 1)"
BRGH=TXSTA.2,"High Baud Rate Select bit (Usart 1)"
TRMT=TXSTA.1,"Transmit Shift Register Status flag (Usart 1)"
TX9D=TXSTA.0,"9th bit of transmit data. Can be parity bit. (Usart 1)"

TXREG="EUSART Transmit Register"
SPBRG="Baud Rate Generator Register, Low Byte"
SPBRGH="Baud Rate Generator Register, High Byte"
RCREG="EUSART Receive Register"

RD16=T3CON.7,"16-bit Read/Write Mode Enable bit"
T3ECCP1=T3CON.6,"Timer3 (bit6) and Timer1 (bit3) to CCPx Enable bits"
T3CKPS1=T3CON.5,"Timer3 Input Clock Prescale Select bits" 
T3CKPS0=T3CON.4,"Timer3 Input Clock Prescale Select bits" 
T3CCP1=T3CON.3,"Timer3 (bit6) and Timer1 (bit3) to CCPx Enable bits"
NOT_T3SYNC=T3CON.2,"Timer3 External Clock Input Synchronization Control bit"
TMR3CS=T3CON.1,"Timer3 Clock Source Select bit"
TMR3ON=T3CON.0,"Timer3 On enable bit"

TMR3H="Timer3 Register High Byte"
TMR3="Timer3 Register"
TMR3L="Timer3 Register Low Byte"

ABDOVF=BAUDCON.7,"Auto-Baud Acquisition Rollover Status bit"
RCIDL=BAUDCON.6,"Receive Operation Idle Status bit"
SCKP=BAUDCON.4,"Synchronous Clock Polarity Select bit"
BRG16=BAUDCON.3,"16-bit Baud Rate Register Enable bit"
WUE=BAUDCON.1,"Wake-up Enable bit"
ABDEN=BAUDCON.0,"Auto-Baud Detect Enable bit"

DC1B1=CCP1CON.5,"PWM1 Least Significant bits"
DC1B0=CCP1CON.4,"PWM1 Least Significant bits"
CCP1M3=CCP1CON.3,"CCP1 Mode Select"
CCP1M2=CCP1CON.2,"CCP1 Mode Select"
CCP1M1=CCP1CON.1,"CCP1 Mode Select"
CCP1M0=CCP1CON.0,"CCP1 Mode Select"

CCPR1H="Capture/Compare/PWM register1 (MSB)"
CCPR1L="Capture/Compare/PWM register1 (LSB)"
CCPR1="Capture/Compare/PWM Register"

ADFM=ADCON2.7,"A/D Result Format Select bit"
ACQT2=ADCON2.5,"A/D Acquisition Time Select bits"
ACQT1=ADCON2.4,"A/D Acquisition Time Select bits"
ACQT0=ADCON2.3,"A/D Acquisition Time Select bits"
ADCS2=ADCON2.2,"A/D Conversion Clock Select bits"
ADCS1=ADCON2.1,"A/D Conversion Clock Select bits"
ADCS0=ADCON2.0,"A/D Conversion Clock Select bits"

VCFG1=ADCON1.5,"Voltage Reference Configuration bit (VREF- source)"
VCFG0=ADCON1.4,"Voltage Reference Configuration bit (VREF+ source)"
PCFG3=ADCON1.3,"A/D Port Configuration Control bits"
PCFG2=ADCON1.2,"A/D Port Configuration Control bits"
PCFG1=ADCON1.1,"A/D Port Configuration Control bits"
PCFG0=ADCON1.0,"A/D Port Configuration Control bits"

CHS3=ADCON0.5,"Analog Channel Select bits"
CHS2=ADCON0.4,"Analog Channel Select bits"
CHS1=ADCON0.3,"Analog Channel Select bits"
CHS0=ADCON0.2,"Analog Channel Select bits"
NOT_DONE=ADCON0.1,"A/D Conversion Status flag"
GO=ADCON0.1,"A/D Conversion Enable"
ADON=ADCON0.0,"A/D ON bit"

ADRESL="A/D Register low byte" 
ADRESH="A/D Register high byte" 
ADRES="A/D result as a 16 bit value <br> This feature is specific to the PROTON compiler",[0..0]

GCEN=SSPCON2.7,"General Call Enable bit (Slave mode only)"
ACKSTAT=SSPCON2.6,"Acknowledge Status bit (Master Transmit mode only)"
ACKDT=SSPCON2.5," Acknowledge Data bit (Master Receive mode only)"
ACKEN=SSPCON2.4," Acknowledge Sequence Enable bit (Master Receive mode only)"
RCEN=SSPCON2.3,"Receive Enable bit (Master mode only)"
PEN=SSPCON2.2,"Stop Condition Enable bit (Master mode only) "
RSEN=SSPCON2.1,"Repeated Start Condition Enabled bit (Master mode only) "
SEN=SSPCON2.0," Start Condition Enabled/Stretch Enabled bit"

WCOL=SSPCON1.7," Write Collision Detect bit"
SSPOV=SSPCON1.6," Receive Overflow Indicator bit "
SSPEN=SSPCON1.5," Synchronous Serial Port Enable bit"
CKP=SSPCON1.4,"SCK Release Control bit"
SSPM3=SSPCON1.3,"Synchronous Serial Port Mode Select bits"
SSPM2=SSPCON1.2,"Synchronous Serial Port Mode Select bits"
SSPM1=SSPCON1.1,"Synchronous Serial Port Mode Select bits"
SSPM0=SSPCON1.0,"Synchronous Serial Port Mode Select bits"

SMP=SSPSTAT.7,"Sample bit"
CKE=SSPSTAT.6,"SPI Clock Edge Select"
D_A=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
DATA_ADDR=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
P=SSPSTAT.4,"I2C Stop"
S=SSPSTAT.3,"I2C Start"
R_W=SSPSTAT.2,"Read/Write bit information (I2C mode only)"
UA=SSPSTAT.1,"Update Address (10-bit I2C mode only)"
BF=SSPSTAT.0,"Buffer Full Status flag"

SSPBUF="Synchonous serial port receive buffer or transmit register"
SSPADD="Synchronous serial port (I2C mode) address register"

TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 ON"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"

TMR2="Timer2 module's register"
PR2="Timer2 period register"

RD16=T1CON.7,"16-bit Read/Write Mode Enable bit"
T1RUN=T1CON.6,"Timer1 System Clock Status bit"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"

TMR1H="Timer1 Register High Byte"
TMR1L="Timer1 Register Low Byte"

IPEN=RCON.7,"Interrupt Priority Enable bit"
SBOREN=RCON.6,"Software BOR Enable bit"
NOT_RI=RCON.4,"RESET Instruction Flag bit"
NOT_TO=RCON.3,"Watchdog Time-out Flag bit"
NOT_PD=RCON.2,"Power-down Detection Flag bit"
NOT_POR=RCON.1,"Power-on Reset Status bit"
NOT_BOR=RCON.0,"Brown-out Reset Status bit"

SWDTEN=WDTCON.0,"Software Controlled Watchdog Timer Enable bit"

VDIRMAG=HLVDCON.7,"Voltage Direction Magnitude Select bit"
IRVST=HLVDCON.5,"Internal Reference Voltage Stable Flag"
HLVDEN=HLVDCON.4,"High/Low Voltage Detect Power Enable bit"
HLVDL3=HLVDCON.3,"High/Low Voltage Detection Limit bit"
HLVDL2=HLVDCON.2,"High/Low Voltage Detection Limit bit"
HLVDL1=HLVDCON.1,"High/Low Voltage Detection Limit bit"
HLVDL0=HLVDCON.0,"High/Low Voltage Detection Limit bit"

OSCCON="OSCCON REGISTER"
IDLEN=OSCCON.7,"Idle Enable bits"
IRCF2=OSCCON.6,"Internal Oscillator Frequency Select bits"
IRCF1=OSCCON.5,"Internal Oscillator Frequency Select bits"
IRCF0=OSCCON.4,"Internal Oscillator Frequency Select bits"
OSTS=OSCCON.3,"Oscillator Start-up Time-out Status bit"
IOFS=OSCCON.2,"INTOSC Frequency Stable bit"
SCS1=OSCCON.1,"System Clock Select bit"
SCS0=OSCCON.0,"System Clock Select bit"

TMR0ON=T0CON.7,"Timer0 On/Off Control bit"
T08BIT=T0CON.6,"Timer0 8-bit/16-bit Control bit"
T0CS=T0CON.5,"Timer0 Clock Source Select bit"
T0SE=T0CON.4,"Timer0 Source Edge Select bit"
PSA=T0CON.3,"Timer0 Prescaler Assignment bit"
T0PS2=T0CON.2,"Timer0 Prescaler Select bit"
T0PS1=T0CON.1,"Timer0 Prescaler Select bit"
T0PS0=T0CON.0,"Timer0 Prescaler Select bit"

TMR0L="Timer0 Module Low Byte Register"
TMR0H="Timer0 Module High Byte Register"

N=STATUS.4,"Negative bit"
OV=STATUS.3,"Overflow bit"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"

FSR2H="Indirect Data Memory Address Pointer 2 High Byte",[0..3]
FSR2L="Indirect Data Memory Address Pointer 2 Low Byte"

POSTINC2="Uses contents of FSR2 to address data memory value of FSR2 post-incremented<br>(not a physical register)"
POSTDEC2="Uses contents of FSR2 to address data memory - value of FSR2 post-decremented <br>(not a physical register)"
PREINC2="Uses contents of FSR2 to address data memory - value of FSR2 pre-incremented <br>(not a physical register)"
PLUSW2="Uses contents of FSR2 to address data memory - value of FSR2 pre-incremented<BR>(not a physical register) - value of FSR2 offset by value in WREG"

BSR="Bank Select Register",[0..3]

INDF2="Uses contents of FSR2 to address data memory value of FSR2 not changed (not a physical register)"

POSTINC1="Uses contents of FSR1 to address data memory value of FSR1 post-incremented<br>(not a physical register)"
POSTDEC1="Uses contents of FSR1 to address data memory - value of FSR1 post-decremented <br>(not a physical register)"
PREINC1="Uses contents of FSR1 to address data memory - value of FSR1 pre-incremented <br>(not a physical register)"
PLUSW1="Uses contents of FSR1 to address data memory - value of FSR1 pre-incremented<BR>(not a physical register) - value of FSR1 offset by value in WREG"

FSR1H="Indirect Data Memory Address Pointer 1 High Byte",[0..3]
FSR1L="Indirect Data Memory Address Pointer 1 Low Byte"

WREG="Working Register"
INDF1="Uses contents of FSR1 to address data memory value of FSR1 not changed (not a physical register)"

INDF0="Uses contents of FSR0 to address data memory value of FSR0 not changed (not a physical register)"

POSTINC0="Uses contents of FSR0 to address data memory value of FSR0 post-incremented<br>(not a physical register)"
POSTDEC0="Uses contents of FSR0 to address data memory - value of FSR0 post-decremented <br>(not a physical register)"
PREINC0="Uses contents of FSR0 to address data memory - value of FSR0 pre-incremented <br>(not a physical register)"
PLUSW0="Uses contents of FSR0 to address data memory - value of FSR0 pre-incremented<BR>(not a physical register) - value of FSR0 offset by value in WREG"

FSR0H="Indirect Data Memory Address Pointer 0 High Byte",[0..3]
FSR0L="Indirect Data Memory Address Pointer 0 Low Byte"

INT2IP=INTCON3.7,"INT2 External Interrupt Priority bit"
INT1IP=INTCON3.6,"INT1 External Interrupt Priority bit"
INT2IE=INTCON3.4,"INT2 External Interrupt Enable"
INT1IE=INTCON3.3,"INT1 External Interrupt Enable"
INT2IF=INTCON3.1,"INT2 External Interrupt Flag"
INT1IF=INTCON3.0,"INT1 External Interrupt Flag"

NOT_RBPU=INTCON2.7,"PORTB Pull-up Enable bit"
INTEDG0=INTCON2.6,"External Interrupt0 Edge Select bit"
INTEDG1=INTCON2.5,"External Interrupt1 Edge Select bit"
INTEDG2=INTCON2.4,"External Interrupt2 Edge Select bit"
TMR0IP=INTCON2.2,"TMR0 Overflow Interrupt Priority bit"
RBIP=INTCON2.0,"RB Port Change Interrupt Priority bit"

GIE=INTCON.7,"Global Interrupt Enable"
GIEH=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
GIEL=INTCON.6,"Peripheral Interrupt Enable"
TMR0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INT0IE=INTCON.4,"INT0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
TMR0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INT0IF=INTCON.1,"INT0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"

PRODH="Product Register High Byte"
PRODL="Product Register Low Byte"
PROD="Product Register"

TBLPTRU="Program Memory Table Pointer<br>Upper Byte (TBLPTR<20:16>",[0..4]
TBLPTRH="Program Memory Table Pointer High Byte (TBLPTR<15:8>)"
TBLPTRL="Program Memory Table Pointer Low Byte (TBLPTR<7:0>)"
TABLAT="Program Memory Table Latch"
TBLPTR="Table Pointer Register"

PCLATU="Program Counter Upper Byte Latch"
PCLATH="Program Counter High Byte Latch"
PCL="PC Low Byte"
PCH="PC High Byte"
PC="Program Counter"

STKFUL=STKPTR.7,"Stack Full Flag bit"
STKUNF=STKPTR.6,"Stack Underflow Flag bit"
SP4=STKPTR.4,"Stack Pointer Location bit"
SP3=STKPTR.3,"Stack Pointer Location bit"
SP2=STKPTR.2,"Stack Pointer Location bit"
SP1=STKPTR.1,"Stack Pointer Location bit"
SP0=STKPTR.0,"Stack Pointer Location bit"

TOSU="Top-of-Stack Upper Byte (TOS<20:16>)",[0..4]
TOSH="Top-of-Stack High Byte (TOS<15:8>)"
TOSLH="Top-of-Stack High Byte (TOS<15:8>)"
TOSL="Top-of-Stack Low Byte (TOS<7:0>)"
TOS="Top Of Stack Register"

PRSEN=ECCP1DEL.7,"PWM Restart Enable bit"
PDC6=ECCP1DEL.6,"PWM Delay Count bits"
PDC5=ECCP1DEL.5,"PWM Delay Count bits"
PDC4=ECCP1DEL.4,"PWM Delay Count bits"
PDC3=ECCP1DEL.3,"PWM Delay Count bits"
PDC2=ECCP1DEL.2,"PWM Delay Count bits"
PDC1=ECCP1DEL.1,"PWM Delay Count bits"
PDC0=ECCP1DEL.0,"PWM Delay Count bits"

ECCPASE=ECCP1AS.7,"ECCP Auto-Shutdown Event Status bit"
ECCPAS2=ECCP1AS.6,"ECCP Auto-Shutdown bit 2"
ECCPAS1=ECCP1AS.5,"ECCP Auto-Shutdown bit 1"
ECCPAS0=ECCP1AS.4,"ECCP Auto-Shutdown bit 0"
PSSAC1=ECCP1AS.3,"Pins A and C Shutdown State Control bits"
PSSAC0=ECCP1AS.2,"Pins A and C Shutdown State Control bits"
PSSBD1=ECCP1AS.1,"Pins B and D Shutdown State Control bits<br>Unimplemented on 28-pin devices and read as ‘0’"
PSSBD0=ECCP1AS.0,"Pins B and D Shutdown State Control bits<br>Unimplemented on 28-pin devices and read as ‘0’"

C2OUT=CMCON.7,"Comparator 1 Output"
C1OUT=CMCON.6,"Comparator 1 Output"
C2INV=CMCON.5,"Comparator 2 Output Inversion"
C1INV=CMCON.4,"Comparator 1 Output Inversion"
CIS=CMCON.3,"Comparator Input Switch"
CM2=CMCON.2,"Comparator Mode bit"
CM1=CMCON.1,"Comparator Mode bit"
CM0=CMCON.0,"Comparator Mode bit"

CVREN=CVRCON.7,"Comparator Voltage Reference Enable bit"
CVROE=CVRCON.6,"Comparator VREF Output Enable bit<br>CVROE overrides the TRISA<2> bit setting"
CVRR=CVRCON.5,"Comparator VREF Range Selection bit"
CVRSS=CVRCON.4,"Comparator VREF Source Selection bit"
CVR3=CVRCON.3,"CVREF value selection"
CVR2=CVRCON.2,"CVREF value selection"
CVR1=CVRCON.1,"CVREF value selection"
CVR0=CVRCON.0,"CVREF value selection"



