** BITNAMES **

RE3=PORTE.3,"Digital input"
VPP=PORTE.3,"Programming voltage input"
NOT_MCLR=PORTE.3,"Master Clear (Reset) input"

RA0=PORTA.0,"Bidirectional Digital I/O"
AN0=PORTA.0,"Analog input 0"
RA1=PORTA.1,"Bidirectional Digital I/O"
AN1=PORTA.1,"Analog input 1"
RA2=PORTA.2,"Bidirectional Digital I/O"
AN2=PORTA.2,"Analog input 2"
VREF_MINUS=PORTA.2,"A/D Reference Voltage (Low) input"
CVREF=PORTA.2,"Comparator reference voltage output"
RA3=PORTA.3,"Bidirectional Digital I/O"
AN3=PORTA.3,"Analog input 3"
VREF_PLUS=PORTA.3,"A/D Reference Voltage (High) input"
RA4=PORTA.4,"Bidirectional Digital I/O"
T0CKI=PORTA.4,"Timer0 external clock input"
C1OUT=PORTA.4,"Comparator 1 output"
RA5=PORTA.5,"Bidirectional Digital I/O"
AN4=PORTA.5,"Analog input 4"
NOT_SS=PORTA.5,"SPI™ slave select input."
HLVDIN=PORTA.5,"High/Low-Voltage Detect input"
C2OUT=PORTA.5,"Comparator 2 output"
RA6=PORTA.6,"General purpose I/O pin"
CLKO=PORTA.6,"In RC mode, OSC2 pin outputs CLKO, which has 1/4 the <br>frequency of OSC1 and denotes the instruction cycle rate"
OSC2=PORTA.6,"Oscillator crystal output. Connects to crystal or resonator <br>in Crystal Oscillator mode"
RA7=PORTA.7,"General purpose I/O pin"
CLKI=PORTA.7,"External clock source input. Always associated with pin <br>function OSC1. (See related OSC1/CLKI, OSC2/CLKO pins.)"
OSC1=PORTA.7,"Oscillator crystal input or external clock source input. <br>ST buffer when configured in RC mode, CMOS otherwise"

RB0=PORTB.0,"Bidirectional Digital I/O"
INT0=PORTB.0,"External interrupt 0"
FLT0=PORTB.0,"PWM Fault input for CCP1"
AN12=PORTB.0,"Analog input 12"
RB1=PORTB.1,"Bidirectional Digital I/O"
INT1=PORTB.1,"External interrupt 1"
AN10=PORTB.1,"Analog input 10"
RB2=PORTB.2,"Bidirectional Digital I/O"
INT2=PORTB.2,"External interrupt 2"
AN8=PORTB.2,"Analog input 8"
RB3=PORTB.3,"Bidirectional Digital I/O"
AN9=PORTB.3,"Analog input 9"
CCP2=PORTB.3,"Capture 2 input/Compare 2 output/PWM 2 output."
RB4=PORTB.4,"Bidirectional Digital I/O"
KBI0=PORTB.4,"Interrupt-on-change pin"
AN11=PORTB.4,"Analog input 11"
RB5=PORTB.5,"Bidirectional Digital I/O"
KBI1=PORTB.5,"Interrupt-on-change pin"
PGM=PORTB.5,"Low-Voltage ICSP™ Programming enable pin"
RB6=PORTB.6,"Bidirectional Digital I/O"
KBI2=PORTB.6,"Interrupt-on-change pin"
PGC=PORTB.6,"In-Circuit Debugger and ICSP programming clock"
RB7=PORTB.7,"Bidirectional Digital I/O"
KBI3=PORTB.7,"Interrupt-on-change pin"
PGD=PORTB.7,"In-Circuit Debugger and ICSP programming data"

RC0=PORTC.0,"Bidirectional Digital I/O"
T1OSO=PORTC.0,"Timer1 oscillator output"
T13CKI=PORTC.0,"Timer1/Timer3 external clock input
RC1=PORTC.1,"Bidirectional Digital I/O"
T1OSI=PORTC.1,"Timer1 oscillator input"
CCP2=PORTC.1,"Capture2 input, Compare2 output, PWM2 output"
RC2=PORTC.2,"Bidirectional Digital I/O"
CCP1=PORTC.2,"Capture1 input/Compare1 output/PWM1 output"
P1A=PORTC.2,"Enhanced CCP1 output"
RC3=PORTC.3,"Bidirectional Digital I/O"
SCK=PORTC.3,"Synchronous serial clock input/output for SPI mode"
SCL=PORTC.3,"Synchronous serial clock input/output for I2C mode"
RC4=PORTC.4,"Bidirectional Digital I/O"
SDI=PORTC.4,"SPI™ data in"
SDA=PORTC.4,"I2C™ data I/O"
RC5=PORTC.5,"Bidirectional Digital I/O"
SDO=PORTC.5,"SPI data out"
RC6=PORTC.6,"Bidirectional Digital I/O"
TX=PORTC.6,"EUSART Asynchronous Transmit"
CK=PORTC.6,"EUSART Synchronous Clock (see related RX/DT)"
RC7=PORTC.7,"Bidirectional Digital I/O"
RX=PORTC.7,"EUSART Asynchronous Receive"
DT=PORTC.7,"EUSART Synchronous Data (see related TX/CK)"

RD0=PORTD.0,"Bidirectional Digital I/O"
PSP0=PORTD.0,"Parallel Slave Port data"
RD1=PORTD.1,"Bidirectional Digital I/O"
PSP1=PORTD.1,"Parallel Slave Port data"
RD2=PORTD.2,"Bidirectional Digital I/O"
PSP2=PORTD.2,"Parallel Slave Port data"
RD3=PORTD.3,"Bidirectional Digital I/O"
PSP3=PORTD.3,"Parallel Slave Port data"
RD4=PORTD.4,"Bidirectional Digital I/O"
PSP4=PORTD.4,"Parallel Slave Port data"
RD5=PORTD.5,"Bidirectional Digital I/O"
PSP5=PORTD.5,"Parallel Slave Port data"
P1B=PORTD.5,"Enhanced CCP1 output"
RD6=PORTD.6,"Bidirectional Digital I/O"
PSP6=PORTD.6,"Parallel Slave Port data"
P1C=PORTD.6,"Enhanced CCP1 output"
RD7=PORTD.7,"Bidirectional Digital I/O"
PSP7=PORTD.7,"Parallel Slave Port data"
P1D=PORTD.7,"Enhanced CCP1 output"

LATE="Read PORTE Data Latch, Write PORTE Data Latch"
LATD="Read PORTD Data Latch, Write PORTD Data Latch"
LATC="Read PORTC Data Latch, Write PORTC Data Latch"
LATB="Read PORTB Data Latch, Write PORTB Data Latch"
LATA="Read PORTA Data Latch, Write PORTA Data Latch"

TRISA="Data Direction Control Register for PORTA"
TRISB="Data Direction Control Register for PORTB"
TRISC="Data Direction Control Register for PORTC"
TRISD="Data Direction Control Register for PORTD"
TRISE="Data Direction Control Register for PORTE"

INTSRC=OSCTUNE.7,"Internal Oscillator Low-Frequency Source Select bit"
PLLEN=OSCTUNE.6,"Frequency Multiplier PLL for INTOSC Enable bit"
TUN4=OSCTUNE.4,"Frequency Tuning bits"
TUN3=OSCTUNE.3,"Frequency Tuning bits"
TUN2=OSCTUNE.2,"Frequency Tuning bits"
TUN1=OSCTUNE.1,"Frequency Tuning bits"
TUN0=OSCTUNE.0,"Frequency Tuning bits"

PSPIE=PIE1.7,"Parallel Slave Port Read/Write Interrupt Enable bit<br>This bit is unimplemented on 28-pin devices and is read as ‘0’"
ADIE=PIE1.6,"A/D Converter Interrupt Enable bit"
RCIE=PIE1.5,"EUSART Receive Interrupt Enable bit"
TXIE=PIE1.4,"EUSART Transmit Interrupt Enable bit"
SSPIE=PIE1.3,"Master Synchronous Serial Port Interrupt Enable bit"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable bit"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable bit"
TMR1IE=PIE1.0,"TMR1 Overflow Interrupt Enable bit"

PSPIF=PIR1.7,"Parallel Slave Port Read/Write Interrupt Flag bit<br>This bit is unimplemented on 28-pin devices and is read as ‘0’"
ADIF=PIR1.6,"A/D Converter Interrupt Flag bit"
RCIF=PIR1.5,"EUSART Receive Interrupt Flag bit"
TXIF=PIR1.4,"EUSART Transmit Interrupt Flag bit"
SSPIF=PIR1.3,"Master Synchronous Serial Port Interrupt Flag bit"
CCP1IF=PIR1.2,"CCP1 Interrupt Flag bit"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag bit"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag bit"

PSPIP=IPR1.7,"Parallel Slave Port Read/Write Interrupt Priority bit<br>This bit is unimplemented on 28-pin devices and is read as ‘0’"
ADIP=IPR1.6,"A/D Converter Interrupt Priority bit"
RCIP=IPR1.5,"EUSART Receive Interrupt Priority bit"
TXIP=IPR1.4,"EUSART Transmit Interrupt Priority bit"
SSPIP=IPR1.3,"Master Synchronous Serial Port Interrupt Priority bit"
CCP1IP=IPR1.2,"CCP1 Interrupt Priority bit"
TMR2IP=IPR1.1,"TMR2 to PR2 Match Interrupt Priority bit"
TMR1IP=IPR1.0,"TMR1 Overflow Interrupt Priority bit"

OSCFIE=PIE2.7,"Oscillator Fail Interrupt Enable bit"
CMIE=PIE2.6,"Comparator Interrupt Enable bit"
HLVDIE=PIE2.2,"High/Low Voltage Detect Interrupt Enable bit"
TMR3IE=PIE2.1,"TMR3 Overflow Interrupt Enable bit"
CCP2IE=PIE2.0,"CCP2 Interrupt Enable bit"

OSCFIF=PIR2.7,"Oscillator Fail Interrupt Flag bit"
CMIF=PIR2.6,"Comparator Interrupt Flag bit"
BCLIF=PIR2.3,"Bus Collision Interrupt Flag bit"
HLVDIF=PIR2.2,"High/Low Voltage Detect Interrupt Flag bit"
TMR3IF=PIR2.1,"TMR3 Overflow Interrupt Flag bit"
CCP2IF=PIR2.0,"CCP2 Interrupt Flag bit"

OSCFIP=IPR2.7,"Oscillator Fail Interrupt Priority bit"
CMIP=IPR2.6,"Comparator Interrupt Priority bit"
BCLIP=IPR2.3,"Bus Collision Interrupt Priority bit "
LVHLVDIP=IPR2.2,"High/Low Voltage Detect Interrupt Priority bit"
TMR3IP=IPR2.1,"TMR3 Overflow Interrupt Priority bit "
CCP2IP=IPR2.0,"CCP2 Interrupt Priority bit"

SPEN=RCSTA.7,"Serial Port Enable (Usart 1)"
RX9=RCSTA.6,"9-bit Receive Enable (Usart 1)"
SREN=RCSTA.5,"Single Receive Enable (Usart 1)"
CREN=RCSTA.4,"Continuous Receive Enable (Usart 1)"
ADDEN=RCSTA.3,"Address Detect Enable (Usart 1)"
FERR=RCSTA.2,"Framing Error (Usart 1)"
OERR=RCSTA.1,"Overrun Error (Usart 1)"
RX9D=RCSTA.0,"9th bit of received data (Can be parity bit) (Usart 1)"

CSRC=TXSTA.7,"Clock Source Select bit (Usart 1)"
TX9=TXSTA.6,"9-bit Transmit Enable (Usart 1)"
TXEN=TXSTA.5,"Transmit Enable (Usart 1)"
SENDB=TXSTA.3,"Send Break Character bit"
SYNC=TXSTA.4,"USART Mode Select bit (Usart 1)"
BRGH=TXSTA.2,"High Baud Rate Select bit (Usart 1)"
TRMT=TXSTA.1,"Transmit Shift Register Status flag (Usart 1)"
TX9D=TXSTA.0,"9th bit of transmit data. Can be parity bit. (Usart 1)"

TXREG="USART Transmit Register"
SPBRG="Baud Rate Generator Register, Low Byte"
SPBRGH="Baud Rate Generator Register, High Byte"
RCREG="USART Receive Register"

RD16=T3CON.7,"16-bit Read/Write Mode Enable bit"
T3CCP2=T3CON.6,"Timer3 (bit6) and Timer1 (bit3) to CCPx Enable bits"
T3CKPS1=T3CON.5,"Timer3 Input Clock Prescale Select bits" 
T3CKPS0=T3CON.4,"Timer3 Input Clock Prescale Select bits" 
T3CCP1=T3CON.3,"Timer3 (bit6) and Timer1 (bit3) to CCPx Enable bits"
NOT_T3SYNC=T3CON.2,"Timer3 External Clock Input Synchronization Control bit"
TMR3CS=T3CON.1,"Timer3 Clock Source Select bit"
TMR3ON=T3CON.0,"Timer3 On enable bit"

TMR3H="Timer3 Register High Byte"
TMR3="Timer3 Register"
TMR3L="Timer3 Register Low Byte"

C2OUT=CMCON.7,"Comparator 1 Output"
C1OUT=CMCON.6,"Comparator 1 Output"
C2INV=CMCON.5,"Comparator 2 Output Inversion"
C1INV=CMCON.4,"Comparator 1 Output Inversion"
CIS=CMCON.3,"Comparator Input Switch"
CM2=CMCON.2,"Comparator Mode bit"
CM1=CMCON.1,"Comparator Mode bit"
CM0=CMCON.0,"Comparator Mode bit"

CVREN=CVRCON.7,"Comparator Voltage Reference Enable bit"
CVROE=CVRCON.6,"Comparator VREF Output Enable bit<br>CVROE overrides the TRISA<2> bit setting"
CVRR=CVRCON.5,"Comparator VREF Range Selection bit"
CVRSS=CVRCON.4,"Comparator VREF Source Selection bit"
CVR3=CVRCON.3,"CVREF value selection"
CVR2=CVRCON.2,"CVREF value selection"
CVR1=CVRCON.1,"CVREF value selection"
CVR0=CVRCON.0,"CVREF value selection"

ECCPASE=ECCP1AS.7,"ECCP Auto-Shutdown Event Status bit"
ECCPAS2=ECCP1AS.6,"ECCP Auto-Shutdown bit 2"
ECCPAS1=ECCP1AS.5,"ECCP Auto-Shutdown bit 1"
ECCPAS0=ECCP1AS.4,"ECCP Auto-Shutdown bit 0"
PSSAC1=ECCP1AS.3,"Pins A and C Shutdown State Control bits"
PSSAC0=ECCP1AS.2,"Pins A and C Shutdown State Control bits"
PSSBD1=ECCP1AS.1,"Pins B and D Shutdown State Control bits<br>Unimplemented on 28-pin devices and read as ‘0’"
PSSBD0=ECCP1AS.0,"Pins B and D Shutdown State Control bits<br>Unimplemented on 28-pin devices and read as ‘0’"

PRSEN=PWM1CON.7,"PWM Restart Enable bit"
PDC6=PWM1CON.6,"PWM Delay Count bit<br>Unimplemented on 28-pin devices and read as ‘0’"
PDC5=PWM1CON.5,"PWM Delay Count bit<br>Unimplemented On 28-pin devices And Read As ‘0’"
PDC4=PWM1CON.4,"PWM Delay Count bit<br>Unimplemented On 28-pin devices And Read As ‘0’"
PDC3=PWM1CON.3,"PWM Delay Count bit<br>Unimplemented On 28-pin devices And Read As ‘0’"
PDC2=PWM1CON.2,"PWM Delay Count bit<br>Unimplemented On 28-pin devices And Read As ‘0’"
PDC1=PWM1CON.1,"PWM Delay Count bit<br>Unimplemented On 28-pin devices And Read As ‘0’"
PDC0=PWM1CON.0,"PWM Delay Count bit<br>Unimplemented On 28-pin devices And Read As ‘0’"

ABDOVF=BAUDCON.7,"Auto-Baud Acquisition Rollover Status bit"
RCIDL=BAUDCON.6,"Receive Operation Idle Status bit"
SCKP=BAUDCON.4,"Synchronous Clock Polarity Select bit"
BRG16=BAUDCON.3,"16-bit Baud Rate Register Enable bit"
WUE=BAUDCON.1,"Wake-up Enable bit"
ABDEN=BAUDCON.0,"Auto-Baud Detect Enable bit"

DC2B1=CCP2CON.5,"PWM2 Least Significant bits"
DC2B0=CCP2CON.4,"PWM2 Least Significant bits"
CCP2M3=CCP2CON.3,"CCP2 Mode Select"
CCP2M2=CCP2CON.2,"CCP2 Mode Select"
CCP2M1=CCP2CON.1,"CCP2 Mode Select"
CCP2M0=CCP2CON.0,"CCP2 Mode Select"

CCPR2H="Capture/Compare/PWM register2 (MSB)"
CCPR2L="Capture/Compare/PWM register2 (LSB)"
CCPR2="Capture/Compare/PWM register"

P1M1=CCP1CON.7,"Enhanced PWM Output Configuration bits"
P1M0=CCP1CON.6,"Enhanced PWM Output Configuration bits"
DC1B1=CCP1CON.5,"PWM1 Least Significant bits"
DC1B0=CCP1CON.4,"PWM1 Least Significant bits"
CCP1M3=CCP1CON.3,"CCP1 Mode Select"
CCP1M2=CCP1CON.2,"CCP1 Mode Select"
CCP1M1=CCP1CON.1,"CCP1 Mode Select"
CCP1M0=CCP1CON.0,"CCP1 Mode Select"

CCPR1H="Capture/Compare/PWM register1 (MSB)"
CCPR1L="Capture/Compare/PWM register1 (LSB)"
CCPR1="Capture/Compare/PWM Register"

ADFM=ADCON2.7,"A/D Result Format Select bit"
ACQT2=ADCON2.5,"A/D Acquisition Time Select bits"
ACQT1=ADCON2.4,"A/D Acquisition Time Select bits"
ACQT0=ADCON2.3,"A/D Acquisition Time Select bits"
ADCS2=ADCON2.2,"A/D Conversion Clock Select bits"
ADCS1=ADCON2.1,"A/D Conversion Clock Select bits"
ADCS0=ADCON2.0,"A/D Conversion Clock Select bits"

VCFG1=ADCON1.5,"Voltage Reference Configuration bit (VREF- source)"
VCFG0=ADCON1.4,"Voltage Reference Configuration bit (VREF+ source)"
PCFG3=ADCON1.3,"A/D Port Configuration Control bits"
PCFG2=ADCON1.2,"A/D Port Configuration Control bits"
PCFG1=ADCON1.1,"A/D Port Configuration Control bits"
PCFG0=ADCON1.0,"A/D Port Configuration Control bits"

CHS3=ADCON0.5,"Analog Channel Select bits"
CHS2=ADCON0.4,"Analog Channel Select bits"
CHS1=ADCON0.3,"Analog Channel Select bits"
CHS0=ADCON0.2,"Analog Channel Select bits"
NOT_DONE=ADCON0.1,"A/D Conversion Status flag"
GO=ADCON0.1,"A/D Conversion Enable"
ADON=ADCON0.0,"A/D ON bit"

ADRESL="A/D Register low byte" 
ADRESH="A/D Register high byte" 
ADRES="A/D result as a 16 bit value <br> This feature is specific to the PROTON compiler",[0..0]

GCEN=SSPCON2.7,"General Call Enable bit (Slave mode only)"
ACKSTAT=SSPCON2.6,"Acknowledge Status bit (Master Transmit mode only)"
ACKDT=SSPCON2.5," Acknowledge Data bit (Master Receive mode only)"
ACKEN=SSPCON2.4," Acknowledge Sequence Enable bit (Master Receive mode only)"
RCEN=SSPCON2.3,"Receive Enable bit (Master mode only)"
PEN=SSPCON2.2,"Stop Condition Enable bit (Master mode only) "
RSEN=SSPCON2.1,"Repeated Start Condition Enabled bit (Master mode only) "
SEN=SSPCON2.0," Start Condition Enabled/Stretch Enabled bit"

WCOL=SSPCON1.7," Write Collision Detect bit"
SSPOV=SSPCON1.6," Receive Overflow Indicator bit "
SSPEN=SSPCON1.5," Synchronous Serial Port Enable bit"
CKP=SSPCON1.4,"SCK Release Control bit"
SSPM3=SSPCON1.3,"Synchronous Serial Port Mode Select bits"
SSPM2=SSPCON1.2,"Synchronous Serial Port Mode Select bits"
SSPM1=SSPCON1.1,"Synchronous Serial Port Mode Select bits"
SSPM0=SSPCON1.0,"Synchronous Serial Port Mode Select bits"

SMP=SSPSTAT.7,"Sample bit"
CKE=SSPSTAT.6,"SPI Clock Edge Select"
D_A=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
DATA_ADDR=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
P=SSPSTAT.4,"I2C Stop"
S=SSPSTAT.3,"I2C Start"
R_W=SSPSTAT.2,"Read/Write bit information (I2C mode only)"
UA=SSPSTAT.1,"Update Address (10-bit I2C mode only)"
BF=SSPSTAT.0,"Buffer Full Status flag"

SSPBUF="Synchonous serial port receive buffer or transmit register"
SSPADD="Synchronous serial port (I2C mode) address register"

TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 ON"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"

TMR2="Timer2 module's register"
PR2="Timer2 period register"

RD16=T1CON.7,"16-bit Read/Write Mode Enable bit"
T1RUN=T1CON.6,"Timer1 System Clock Status bit"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"

TMR1H="Timer1 Register High Byte"
TMR1L="Timer1 Register Low Byte"

IPEN=RCON.7,"Interrupt Priority Enable bit"
SBOREN=RCON.6,"Software BOR Enable bit"
NOT_RI=RCON.4,"RESET Instruction Flag bit"
NOT_TO=RCON.3,"Watchdog Time-out Flag bit"
NOT_PD=RCON.2,"Power-down Detection Flag bit"
NOT_POR=RCON.1,"Power-on Reset Status bit"
NOT_BOR=RCON.0,"Brown-out Reset Status bit"

SWDTEN=WDTCON.0,"Software Controlled Watchdog Timer Enable bit"

VDIRMAG=HLVDCON.7,"Voltage Direction Magnitude Select bit"
IRVST=HLVDCON.5,"Internal Reference Voltage Stable Flag"
HLVDEN=HLVDCON.4,"High/Low Voltage Detect Power Enable bit"
HLVDL3=HLVDCON.3,"High/Low Voltage Detection Limit bit"
HLVDL2=HLVDCON.2,"High/Low Voltage Detection Limit bit"
HLVDL1=HLVDCON.1,"High/Low Voltage Detection Limit bit"
HLVDL0=HLVDCON.0,"High/Low Voltage Detection Limit bit"

OSCCON="OSCCON REGISTER"
IDLEN=OSCCON.7,"Idle Enable bits"
IRCF2=OSCCON.6,"Internal Oscillator Frequency Select bits"
IRCF1=OSCCON.5,"Internal Oscillator Frequency Select bits"
IRCF0=OSCCON.4,"Internal Oscillator Frequency Select bits"
OSTS=OSCCON.3,"Oscillator Start-up Time-out Status bit"
IOFS=OSCCON.2,"INTOSC Frequency Stable bit"
SCS1=OSCCON.1,"System Clock Select bit"
SCS0=OSCCON.0,"System Clock Select bit"

Debug="Background Debugger Enable bit"

TMR0ON=T0CON.7,"Timer0 On/Off Control bit"
T08BIT=T0CON.6,"Timer0 8-bit/16-bit Control bit"
T0CS=T0CON.5,"Timer0 Clock Source Select bit"
T0SE=T0CON.4,"Timer0 Source Edge Select bit"
PSA=T0CON.3,"Timer0 Prescaler Assignment bit"
T0PS2=T0CON.2,"Timer0 Prescaler Select bit"
T0PS1=T0CON.1,"Timer0 Prescaler Select bit"
T0PS0=T0CON.0,"Timer0 Prescaler Select bit"

TMR0L="Timer0 Module Low Byte Register"
TMR0H="Timer0 Module High Byte Register"

N=STATUS.4,"Negative bit"
OV=STATUS.3,"Overflow bit"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"

FSR2H="Indirect Data Memory Address Pointer 2 High Byte",[0..3]
FSR2L="Indirect Data Memory Address Pointer 2 Low Byte"

POSTINC2="Uses contents of FSR2 to address data memory value of FSR2 post-incremented<br>(not a physical register)"
POSTDEC2="Uses contents of FSR2 to address data memory - value of FSR2 post-decremented <br>(not a physical register)"
PREINC2="Uses contents of FSR2 to address data memory - value of FSR2 pre-incremented <br>(not a physical register)"
PLUSW2="Uses contents of FSR2 to address data memory - value of FSR2 pre-incremented<BR>(not a physical register) - value of FSR2 offset by value in WREG"

BSR="Bank Select Register",[0..3]

INDF2="Uses contents of FSR2 to address data memory value of FSR2 not changed (not a physical register)"

POSTINC1="Uses contents of FSR1 to address data memory value of FSR1 post-incremented<br>(not a physical register)"
POSTDEC1="Uses contents of FSR1 to address data memory - value of FSR1 post-decremented <br>(not a physical register)"
PREINC1="Uses contents of FSR1 to address data memory - value of FSR1 pre-incremented <br>(not a physical register)"
PLUSW1="Uses contents of FSR1 to address data memory - value of FSR1 pre-incremented<BR>(not a physical register) - value of FSR1 offset by value in WREG"

FSR1H="Indirect Data Memory Address Pointer 1 High Byte",[0..3]
FSR1L="Indirect Data Memory Address Pointer 1 Low Byte"

WREG="Working Register"
INDF1="Uses contents of FSR1 to address data memory value of FSR1 not changed (not a physical register)"

INDF0="Uses contents of FSR0 to address data memory value of FSR0 not changed (not a physical register)"

POSTINC0="Uses contents of FSR0 to address data memory value of FSR0 post-incremented<br>(not a physical register)"
POSTDEC0="Uses contents of FSR0 to address data memory - value of FSR0 post-decremented <br>(not a physical register)"
PREINC0="Uses contents of FSR0 to address data memory - value of FSR0 pre-incremented <br>(not a physical register)"
PLUSW0="Uses contents of FSR0 to address data memory - value of FSR0 pre-incremented<BR>(not a physical register) - value of FSR0 offset by value in WREG"

FSR0H="Indirect Data Memory Address Pointer 0 High Byte",[0..3]
FSR0L="Indirect Data Memory Address Pointer 0 Low Byte"

INT2IP=INTCON3.7,"INT2 External Interrupt Priority bit"
INT1IP=INTCON3.6,"INT1 External Interrupt Priority bit"
INT2IE=INTCON3.4,"INT2 External Interrupt Enable"
INT1IE=INTCON3.3,"INT1 External Interrupt Enable"
INT2IF=INTCON3.1,"INT2 External Interrupt Flag"
INT1IF=INTCON3.0,"INT1 External Interrupt Flag"

NOT_RBPU=INTCON2.7,"PORTB Pull-up Enable bit"
INTEDG0=INTCON2.6,"External Interrupt0 Edge Select bit"
INTEDG1=INTCON2.5,"External Interrupt1 Edge Select bit"
INTEDG2=INTCON2.4,"External Interrupt2 Edge Select bit"
TMR0IP=INTCON2.2,"TMR0 Overflow Interrupt Priority bit"
RBIP=INTCON2.0,"RB Port Change Interrupt Priority bit"

GIE=INTCON.7,"Global Interrupt Enable"
GIEH=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
GIEL=INTCON.6,"Peripheral Interrupt Enable"
TMR0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INT0IE=INTCON.4,"INT0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
TMR0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INT0IF=INTCON.1,"INT0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"

PRODH="Product Register High Byte"
PRODL="Product Register Low Byte"
PROD="Product Register"

TBLPTRU="Program Memory Table Pointer<br>Upper Byte (TBLPTR<20:16>",[0..4]
TBLPTRH="Program Memory Table Pointer High Byte (TBLPTR<15:8>)"
TBLPTRL="Program Memory Table Pointer Low Byte (TBLPTR<7:0>)"
TABLAT="Program Memory Table Latch"
TBLPTR="Table Pointer Register"

PCLATU="Program Counter Upper Byte Latch"
PCLATH="Program Counter High Byte Latch"
PCL="PC Low Byte"
PCH="PC High Byte"
PC="Program Counter"

STKFUL=STKPTR.7,"Stack Full Flag bit"
STKUNF=STKPTR.6,"Stack Underflow Flag bit"
SP4=STKPTR.4,"Stack Pointer Location bit"
SP3=STKPTR.3,"Stack Pointer Location bit"
SP2=STKPTR.2,"Stack Pointer Location bit"
SP1=STKPTR.1,"Stack Pointer Location bit"
SP0=STKPTR.0,"Stack Pointer Location bit"

TOSU="Top-of-Stack Upper Byte (TOS<20:16>)",[0..4]
TOSH="Top-of-Stack High Byte (TOS<15:8>)"
TOSLH="Top-of-Stack High Byte (TOS<15:8>)"
TOSL="Top-of-Stack Low Byte (TOS<7:0>)"
TOS="Top Of Stack Register"

