** BITNAMES **
IRP=0X07
RP1=0X06
RP0=0X05
NOT_TO=0X04
NOT_PD=0X03
Z=0X02
DC=0X01
C=0X00
GIE=0X07
PEIE=0X06
T0IE=0X05
INTE=0X04
RBIE=0X03
T0IF=0X02
INTF=0X01
RBIF=0X00
SSPIF=0X03
CCP1IF=0X02
TMR2IF=0X01
TMR1IF=0X00
T1CKPS1=0X05
T1CKPS0=0X04
T1OSCEN=0X03
NOT_T1SYNC=0X02
T1INSYNC=0X02
TMR1CS=0X01
TMR1ON=0X00
TOUTPS3=0X06
TOUTPS2=0X05
TOUTPS1=0X04
TOUTPS0=0X03
TMR2ON=0X02
T2CKPS1=0X01
T2CKPS0=0X00
WCOL=0X07
SSPOV=0X06
SSPEN=0X05
CKP=0X04
SSPM3=0X03
SSPM2=0X02
SSPM1=0X01
SSPM0=0X00
CCP1X=0X05
CCP1Y=0X04
CCP1M3=0X03
CCP1M2=0X02
CCP1M1=0X01
CCP1M0=0X00
NOT_RBPU=0X07
INTEDG=0X06
T0CS=0X05
T0SE=0X04
PSA=0X03
PS2=0X02
PS1=0X01
PS0=0X00
SSPIE=0X03
CCP1IE=0X02
TMR2IE=0X01
TMR1IE=0X00
NOT_POR=0X01
D=0X05
_I2C_DAT=0X05
NOT_A=0X05
_NOT_ADDRESS=0X05
D_A=0X05
_DATA_ADDRESS=0X05
P=0X04
_I2C_STP=0X04
S=0X03
_I2C_STRT=0X03
R=0X02
I2C_RD=0X02
NOT_W=0X02
_NOT_WRITE=0X02
R_W=0X02
_READ_WRITE=0X02
UA=0X01
BF=0X00
TMR0="Timer0 module's register"
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"
FSR="Indirect data memory address pointer"
RA5=PORTA.5,"Bi-directional I/O pin"
NOT_SS=PORTA.5,"Slave select input for synchronous serial port"
RA4=PORTA.4,"Bi-directional I/O<br>Output is open drain type"
T0CK1=PORTA.4,"External clock input for Timer0"
RA3=PORTA.3,"Bi-directional I/O pin"
RA2=PORTA.2,"Bi-directional I/O pin"
RA1=PORTA.1,"Bi-directional I/O pin"
RA0=PORTA.0,"Bi-directional I/O pin"
RB7=PORTB.7,"Bi-directional I/O pin"
RB6=PORTB.6,"Bi-directional I/O pin"
RB5=PORTB.5,"Bi-directional I/O pin"
RB4=PORTB.4,"Bi-directional I/O pin"
RB3=PORTB.3,"Bi-directional I/O pin"
RB2=PORTB.2,"Bi-directional I/O pin"
RB1=PORTB.1,"Bi-directional I/O pin"
RB0=PORTB.0,"Bi-directional I/O pin"
RC0=PORTC.0,"Bi-directional I/O pin"
T1OSO=PORTC.0,"Timer1 oscillator output"
T1CKI=PORTC.0,"Timer1 clock input"
RC1=PORTC.1,"Bi-directional I/O pin"
T1CK1=PORTC.1,"Timer1 oscillator input"
RC2=PORTC.2,"Bi-directional I/O pin"
CCP1=PORTC.2,"Capture1 input<br>Compare1 output<br>PWM1 output"
RC3=PORTC.3,"Bi-directional I/O pin"
SCK=PORTC.3,"Synchronous serial clock (SPI mode)"
SCL=PORTC.3,"Synchronous serial clock (I2C mode)"
RC4=PORTC.4,"Bi-directional I/O pin"
SDI=PORTC.4,"Data In (SPI mode)"
SDA=PORTC.4,"Data Input/output (I2C mode)"
RC5=PORTC.5,"Bi-directional I/O pin"
SDO=PORTC.5,"Sychronous Serial Port Output"
RC6=PORTC.6,"Bi-directional I/O pin"
TX=PORTC.6,"USART Asynchronous Transmit"
SYN_CK=PORTC.6,"Synchronous Clock"
RC7=PORTC.7,"Bi-directional I/O pin"
RX=PORTC.7,"USART Asynchronous Receive"
SYN_DT=PORTC.7,"Synchronous Data"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4] 
NOT_POR=PCON.1,"Power-on Reset Status flag"
NOT_BOR=PCON.0,"Brown-out Reset Status flag"
SSPIE=PIE1.3,"Synchronous Serial Port Interrupt Enable"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable"
TMR1IE=PIE1.0,"TMR1 Overflow Interrupt Enable"
SSPIF=PIR1.3,"Synchronous Serial Port (SSP) Interrupt Flag"
CCP1IF=PIR1.2,"CCP1 Interrupt Flag"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag"
GIE=INTCON.7,"Global Interrupt Enable"
T0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INTE=INTCON.4,"RB0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
T0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INTF=INTCON.1,"RB0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"
NOT_RBPU=OPTION_REG.07,"PORTB Pull-up Enable"
INTEDG=OPTION_REG.6,"Interrupt Edge Select"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select"
PSA=OPTION_REG.3,"Prescaler Assignment"
PS2=OPTION_REG.2,"Prescaler Rate Select"
PS1=OPTION_REG.1,"Prescaler Rate Select"
PS0=OPTION_REG.0,"Prescaler Rate Select"
PR2="Timer2 period register"
SSPADD="Synchronous serial port (I2C mode) address register"
SSPBUF="Synchonous serial port receive buffer or transmit register"
WCOL=SSPCON.7,"Write Collision Detect flag"
SSPOV=SSPCON.6,"Receive Overflow Indicator flag"
SSPEN=SSPCON.5,"Synchronous Serial Port Enable flag"
CKP=SSPCON.4,"Clock Polarity Select bit"
SSPM3=SSPCON.3,"Synchronous Serial Port Mode Select bits"
SSPM2=SSPCON.2,"Synchronous Serial Port Mode Select bits"
SSPM1=SSPCON.1,"Synchronous Serial Port Mode Select bits"
SSPM0=SSPCON.0,"Synchronous Serial Port Mode Select bits"
SMP=SSPSTAT.7,"Sample bit"
CKE=SSPSTAT.6,"SPI Clock Edge Select"
D_A=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
DATA_ADDR=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
P=SSPSTAT.4,"I2C Stop"
I2C_STP=SSPSTAT.4,"I2C Stop"
S=SSPSTAT.3,"I2C Start"
I2C_STR=SSPSTAT.3,"I2C Start"
R_W=SSPSTAT.2,"Read/Write bit information (I2C mode only)"
UA=SSPSTAT.1,"Update Address (10-bit I2C mode only)"
BF=SSPSTAT.0,"Buffer Full Status flag"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"
TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 ON"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"
TMR1L="Holding register for the Least Significant Byte of the 16 bit TMR1 register"
TMR1H="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
TMR2="Timer2 module's register"
TRISA="PORTA data direction register",[0..4]
TRISB="PORTB data direction register"
TRISC="PORTC data direction register"

