** BITNAMES **
NOT_RBPU=0X07
INTEDG=0X06
T0CS=0X05
T0SE=0X04
PSA=0X03
PS2=0X02
PS1=0X01
PS0=0X00
IRP=0X07
RP1=0X06
RP0=0X05
NOT_TO=0X04
NOT_PD=0X03
Z=0X02
DC=0X01
C=0X00
GIE=0X07
T0IE=0X05
INTE=0X04
RBIE=0X03
T0IF=0X02
INTF=0X01
RBIF=0X00
TMR0="Timer0 module's register"
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"
FSR="Indirect data memory address pointer"
RA4=PORTA.4,"Bi-directional I/O<br>Output is open drain type"
T0CK1=PORTA.4,"External clock input for Timer0"
RA3=PORTA.3,"Bi-directional I/O pin"
RA2=PORTA.2,"Bi-directional I/O pin"
RA1=PORTA.1,"Bi-directional I/O pin"
RA0=PORTA.0,"Bi-directional I/O pin"
RB7=PORTB.7,"Bi-directional I/O pin"
RB6=PORTB.6,"Bi-directional I/O pin"
RB5=PORTB.5,"Bi-directional I/O pin"
RB4=PORTB.4,"Bi-directional I/O pin"
RB3=PORTB.3,"Bi-directional I/O pin"
RB2=PORTB.2,"Bi-directional I/O pin"
RB1=PORTB.1,"Bi-directional I/O pin"
RB0=PORTB.0,"Bi-directional I/O pin"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4] 
GIE=INTCON.7,"Global Interrupt Enable"
T0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INTE=INTCON.4,"RB0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
T0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INTF=INTCON.1,"RB0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"
NOT_RBPU=OPTION_REG.07,"PORTB Pull-up Enable"
INTEDG=OPTION_REG.6,"Interrupt Edge Select"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select"
PSA=OPTION_REG.3,"Prescaler Assignment"
PS2=OPTION_REG.2,"Prescaler Rate Select"
PS1=OPTION_REG.1,"Prescaler Rate Select"
PS0=OPTION_REG.0,"Prescaler Rate Select"
TRISA="PORTA data direction register",[0..4]
TRISB="PORTB data direction register"

