** BITNAMES **
TMR0="Timer0 module's register"
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"
FSR="Indirect data memory address pointer"
RA0=PORTA.0,"Bi-directional I/O pin"
AN0=PORTA.0,"Analog input pin"
RA1=PORTA.1,"Bi-directional I/O pin"
AN1=PORTA.1,"Analog input pin"
RA2=PORTA.2,"Bi-directional I/O pin"
AN2=PORTA.2,"Analog input pin"
VREF_NEG=PORTA.2,"A/D reference voltage input (low)"
CVREF=PORTA.2,"Comparator voltage reference output"
RA3=PORTA.3,"Bi-directional I/O pin"
AN3=PORTA.3,"Analog input pin"
VREF_PLUS=PORTA.3,"A/D reference voltage input (high)"
C1OUT=PORTA.3,"Comparator 1 Output"
RA4=PORTA.4,"Bi-directional I/O<br>Output is open drain type"
AN4=PORTA.4,"Analog input pin"
T0CK1=PORTA.4,"External clock input for Timer0"
C2OUT=PORTA.4,"Comparator 2 Output"
RA5=PORTA.5,"Bi-directional I/O pin"
NOT_MCLR=PORTA.5,"Master Clear (Reset). Input/programming voltage input"
RA6=PORTA.6,"Bi-directional I/O pin"
OSC2=PORTA.6,"Oscillator crystal output. Connects to crystal or<br>resonator in Crystal Oscillator mode"
CLKO=PORTA.6,"In RC mode, this pin outputs CLKO signal which has<br>1/4 the frequency of OSC1 and denotes the<br>instruction cycle rate"
RB0=PORTB.0,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
INT=PORTB.0,"External interrupt input"
CCP1=PORTB.0,"Capture1 input<br>Compare1 output<br>PWM1 output"
RB1=PORTB.1,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
SDI=PORTB.1,"Data In (SPI mode)"
SDA=PORTB.1,"Data Input/output (I2C mode)"
RB2=PORTB.2,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
SDO=PORTB.2,"Sychronous Serial Port Output"
RX=PORTB.2,"USART Asynchronous Receive"
DT=PORTB.2,"USART synchronous detect"
RB3=PORTB.3,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
PGM=PORTB.3,"Programming pin in LVP mode"
CCP1=PORTB.3,"Capture1 input<br>Compare1 output<br>PWM1 output"
RB4=PORTB.4,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
SCK=PORTB.4,"Synchronous serial clock (SPI mode)"
SCL=PORTB.4,"Synchronous serial clock (I2C mode)"
RB5=PORTB.5,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
NOT_SS=PORTB.5,"Slave select for SPI in Slave mode"
TX=PORTB.5,"USART Asynchronous Transmit"
SYN_CK=PORTB.5,"Synchronous Clock"
RB6=PORTB.6,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
AN5=PORTB.6,"Analog input pin"
PGC=PORTB.6,"Serial programming clock"
T1OSO=PORTB.6,"Timer1 oscillator output"
T1CKI=PORTB.6,"Timer1 external clock input"
RC1=PORTC.1,"Bi-directional I/O pin"
PGC=PORTB.6,"Serial programming clock"
RB7=PORTB.7,"Input/output pin (with interrupt on change)<br>Internal software programmable weak pull-up"
AN6=PORTB.7,"Analog input pin"
PGD=PORTB.7,"Serial programming data"
T1OSI=PORTb.7,"Timer1 oscillator input"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4] 
GIE=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
TMR0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INT0IE=INTCON.4,"RB0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
TMR0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INT0IF=INTCON.1,"RB0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"
ADIF=PIR1.6,"A/D Converter Interrupt Flag"
RCIF=PIR1.5,"USART Receive Interrupt Flag"
TXIF=PIR1.4,"USART Transmit Interrupt Flag"
SSPIF=PIR1.3,"Synchronous Serial Port (SSP) Interrupt Flag"
CCP1IF=PIR1.2,"CCP1 Interrupt Flag"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag"
OSFIF=PIR2.7,"Oscillator Fail Interrupt Flag"
CMIF=PIR2.6,"Comparator Interrupt Flag"
EEIF=PIR2.4,"EEPROM Write Operation Interrupt Flag"
TMR1L="Holding register for the Least Significant Byte of the 16 bit TMR1 register"
TMR1H="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
TMR1LH="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
T1RUN=T1CON.6,"Timer1 System Clock Status flag"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"
TMR2="Timer2 module's register"
TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 ON"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"
SSPBUF="Synchonous serial port receive buffer or transmit register"
WCOL=SSPCON.7,"Write Collision Detect flag"
SSPOV=SSPCON.6,"Receive Overflow Indicator flag"
SSPEN=SSPCON.5,"Synchronous Serial Port Enable flag"
CKP=SSPCON.4,"Clock Polarity Select bit"
SSPM3=SSPCON.3,"Synchronous Serial Port Mode Select bits"
SSPM2=SSPCON.2,"Synchronous Serial Port Mode Select bits"
SSPM1=SSPCON.1,"Synchronous Serial Port Mode Select bits"
SSPM0=SSPCON.0,"Synchronous Serial Port Mode Select bits"
CCPR1L="Capture or Compare or PWM register1 (LSB)"
CCPR1H="Capture or Compare or PWM register1 (MSB)"
CCPR1lH="Capture or Compare or PWM register1 (MSB)"
CCP1X=CCP1CON.5,"PWM1 Least Significant bits"
CCP1Y=CCP1CON.4,"PWM1 Least Significant bits"
CCP1M3=CCP1CON.3,"CCP1 Mode Select"
CCP1M2=CCP1CON.2,"CCP1 Mode Select"
CCP1M1=CCP1CON.1,"CCP1 Mode Select"
CCP1M0=CCP1CON.0,"CCP1 Mode Select"
SPEN=RCSTA.7,"Serial Port Enable"
RX9=RCSTA.6,"9-bit Receive Enable"
SREN=RCSTA.5,"Single Receive Enable"
CREN=RCSTA.4,"Continuous Receive Enable"
ADDEN=RCSTA.3,"Address Detect Enable"
FERR=RCSTA.2,"Framing Error"
OERR=RCSTA.1,"Overrun Error"
RX9D=RCSTA.0,"9th bit of received data (Can be parity bit)" 
TXREG="USART transmit data register"
RCREG="USART receive data register"
NOT_RBPU=OPTION_REG.07,"PORTB Pull-up Enable"
INTEDG=OPTION_REG.6,"Interrupt Edge Select"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select"
PSA=OPTION_REG.3,"Prescaler Assignment"
PS2=OPTION_REG.2,"Prescaler Rate Select"
PS1=OPTION_REG.1,"Prescaler Rate Select"
PS0=OPTION_REG.0,"Prescaler Rate Select"
TRISA="PORTA data direction register",[0..4]
TRISA5=TRISA.5,"RA5 is an input only"
TRISA="PORTA data direction register",[6..7]
TRISB="PORTB data direction register"
ADIE=PIE1.6,"A/D Converter Interrupt Enable"
RCIE=PIE1.5,"USART Receive Interrupt Enable"
TXIE=PIE1.4,"USART Transmit Interrupt Enable"
SSPIE=PIE1.3,"Synchronous Serial Port Interrupt Enable"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable"
TMR1IE=PIE1.0,"TMR1 Overflow Interrupt Enable"
OSFIE=PIE2.7,"Oscillator Fail Interrupt Enable"
CMIE=PIE2.6,"Comparator Interrupt Enable bit"
EEIE=PIE2.4,"EEPROM Write Operation Interrupt Enable"
SBOREN=PCON.2,"Software Brown-out Reset Enable"
NOT_POR=PCON.1,"Power-on Reset Status flag"
NOT_BOR=PCON.0,"Brown-out Reset Status flag"
IRCF2=OSCCON.6,"Internal RC Oscillator Frequency Select bit"
IRCF1=OSCCON.5,"Internal RC Oscillator Frequency Select bit"
IRCF0=OSCCON.4,"Internal RC Oscillator Frequency Select bit"
OSTS=OSCCON.3,"Oscillator Start-up Time-out Status bit"
IOFS=OSCCON.2,"INTOSC Frequency Stable flag"
SCS1=OSCCON.1,"Oscillator Mode Select bit"
SCS0=OSCCON.0,"Oscillator Mode Select bit"
TUN5=OSCTUNE.5,"Frequency Tuning bit"
TUN4=OSCTUNE.4,"Frequency Tuning bit"
TUN3=OSCTUNE.3,"Frequency Tuning bit"
TUN2=OSCTUNE.2,"Frequency Tuning bit"
TUN1=OSCTUNE.1,"Frequency Tuning bit"
TUN0=OSCTUNE.0,"Frequency Tuning bit"
PR2="Timer2 period register"
SSPADD="Synchronous serial port (I2C mode) address register"
SMP=SSPSTAT.7,"Sample bit"
CKE=SSPSTAT.6,"SPI Clock Edge Select"
D_A=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
DATA_ADDR=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
P=SSPSTAT.4,"I2C Stop"
I2C_STP=SSPSTAT.4,"I2C Stop"
S=SSPSTAT.3,"I2C Start"
I2C_STR=SSPSTAT.3,"I2C Start"
R_W=SSPSTAT.2,"Read/Write bit information (I2C mode only)"
UA=SSPSTAT.1,"Update Address (10-bit I2C mode only)"
BF=SSPSTAT.0,"Buffer Full Status flag"
CSRC=TXSTA.7,"Clock Source Select bit"
TX9=TXSTA.6,"9-bit Transmit Enable"
NOT_TX8=TXSTA.6,"9-bit Transmit Enable" 
TX8_9=TXSTA.6,"9-bit Transmit Enable" 
TXEN=TXSTA.5,"Transmit Enable"
SYNC=TXSTA.4,"USART Mode Select flag"
BRGH=TXSTA.2,"High Baud Rate Select flag"
TRMT=TXSTA.1,"Transmit Shift Register Status flag"
TX9D=TXSTA.0,"9th bit of transmit data. Can be parity bit."
TXD8=TXSTA.0,"9th bit of transmit data. Can be parity bit."
SPBRG="Baud rate generator"
ADCS6=ANSEL.6,"A/D Conversion Clock Select bit 6"
ADCS5=ANSEL.5,"A/D Conversion Clock Select bit 5"
ADCS4=ANSEL.4,"A/D Conversion Clock Select bit 4"
ADCS3=ANSEL.3,"A/D Conversion Clock Select bit 3"
ADCS2=ANSEL.2,"A/D Conversion Clock Select bit 2"
ADCS1=ANSEL.1,"A/D Conversion Clock Select bit 1"
ADCS0=ANSEL.0,"A/D Conversion Clock Select bit 0"
C2OUT=CMCON.7,"Comparator 1 Output"
C1OUT=CMCON.6,"Comparator 1 Output"
C2INV=CMCON.5,"Comparator 2 Output Inversion"
C1INV=CMCON.4,"Comparator 1 Output Inversion"
CIS=CMCON.3,"Comparator Input Switch"
CM2=CMCON.2,"Comparator Mode bit"
CM1=CMCON.1,"Comparator Mode bit"
CM0=CMCON.0,"Comparator Mode bit"
CVREN=CVRCON.7,"CVREF Enable"
CVROE=CVRCON.6,"Comparator VREF Output Enable"
CVRR=CVRCON.5,"CVREF Range Selection"
CVR3=CVRCON.3,"CVREF value selection"
CVR2=CVRCON.2,"CVREF value selection"
CVR1=CVRCON.1,"CVREF value selection"
CVR0=CVRCON.0,"CVREF value selection" 
ADRES="A/D result as a 8 bit value",[0..7]
WDTPS3=WDTCON.4,"Watchdog Timer Period Select bit"
WDTPS2=WDTCON.3,"Watchdog Timer Period Select bit"
WDTPS1=WDTCON.2,"Watchdog Timer Period Select bit"
WDTPS0=WDTCON.1,"Watchdog Timer Period Select bit"
SWDTEN=WDTCON.0,"Software Enable/Disable for Watchdog Timer"
EEDATA="EEPROM data register"
EEADR="EEPROM address register"
EEDATH="EEPROM data register high byte",[0..5]
EEADRH="EEPROM address register high byte",[0..4]
EEPGD=EECON1.7,"Program / Data EEPROM Select bit"
FREE=EECON1.4,"EEPROM Forced Row Erase bit"
WRERR=EECON1.3,"EEPROM Error Flag"
WREN=EECON1.2,"EEPROM Write/Enable"
WR=EECON1.1,"Write Control"
RD=EECON1.0,"Read Control"
EECON2="EEPROM control register2 (not a physical register)"

