** BITNAMES **
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
TMR0="Timer0 module's register"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero"
DC=STATUS.1,[protect], "Digit Carry"
C=STATUS.0,"Carry"
FSR="Indirect data memory address pointer"
PORTA="PORTA data latch when written, PORTA pins when read",[0..5]
PORTB="PORTB data latch when written, PORTB pins when read"
RA4=PORTA.4,"Bi-directional I/O pin<br>Output is open drain type"
T0CKI=PORTA.4,"External clock input for TMR0"
RA3=PORTA.3,"Bi-directional I/O pin"
RA2=PORTA.2,"Bi-directional I/O pin"
RA1=PORTA.1,"Bi-directional I/O pin"
RA0=PORTA.0,"Bi-directional I/O pin"
RB7=PORTB.7,"Bi-directional I/O pin<br>Internal software programmable weak pull-up<br>Serial programming data"
RB6=PORTB.6,"Bi-directional I/O pin<br>Internal software programmable weak pull-up<br>Serial programming clock"
RB5=PORTB.5,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB4=PORTB.4,"Bi-directional I/O pin<br>Internal software programmable weak pull-up<br>Interrupt-on-change"
RB3=PORTB.3,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB2=PORTB.2,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB1=PORTB.1,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
RB0=PORTB.0,"Bi-directional I/O pin<br>Internal software programmable weak pull-up"
INT=PORTB.0,"External interrupt input"
EEDATA="EEPROM data register"
EEADR="EEPROM address register"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4]
GIE=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
T0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INTE=INTCON.4,"RB0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
T0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INTF=INTCON.1,"RB0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4]
NOT_RBPU=OPTION_REG.07,"PORTB Pull-up Enable"
INTEDG=OPTION_REG.6,"Interrupt Edge Select"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select"
PSA=OPTION_REG.3,"Prescaler Assignment"
PS2=OPTION_REG.2,"Prescaler Rate Select bits"
PS1=OPTION_REG.1,"Prescaler Rate Select bits"
PS0=OPTION_REG.0,"Prescaler Rate Select bits"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4]
TRISA="PORTA data direction register",[0..5]
TRISB="PORTB data direction register"
EEIF=EECON1.4,"EEPROM Write Operation Interrupt Flag"
WREER=EECON1.3,"EEPROM Error Flag"
WREN=EECON1.2,"EEPROM Write Enable"
WR=EECON1.1,"Write Control"
RD=EECON1.0,"Read Control"
EECON2="EEPROM Control Register 2"
CAL3=OSCAL.7,"Fine Calibration"
CAL2=OSCAL.6,"Fine Calibration"
CAL1=OSCAL.5,"Fine Calibration"
CAL0=OSCAL.4,"Fine Calibration"
CALFST=CAL.3,"Calibration Fast"
CALSLW=CAL.2,"Calibration Slow"
POR=PCON.1,"Power-on Reset Status flag"

