** BITNAMES **
TMR0="Timer0 module's register"
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
PCL="Program counter's (PC) least significant byte"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out flag"
NOT_PD=STATUS.3,"Power Down flag"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"
FSR="Indirect data memory address pointer"
RA0=PORTA.0,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
AN0=PORTA.0,"Analog input pin"
CIN_PLUS=PORTA.0,"Comparator input"
ICSPDAT=PORTA.0,"Serial Programming Data I/O"
RA1=PORTA.1,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
AN1=PORTA.1,"Analog input pin"
CIN_NEG=PORTA.1,"Comparator input"
VREF=PORTA.1,"Voltage reference pin"
ICSPCLK=PORTA.1,"Serial Programming Clock"
RA2=PORTA.2,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
AN2=PORTA.2,"Analog input pin"
COUT=PORTA.2,"Comparator Output"
T0CK1=PORTA.2,"External clock input for Timer0"
INT=PORTA.2,"External interrupt input"
RA3=PORTA.3,"Input port with Interrupt-on-change"
NOT_MCLR=PORTA.3,"Master Clear (Reset). Input/programming voltage input"
RA4=PORTA.4,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
NOT_T1G=PORTA.4,"Timer1 gate"
AN3=PORTA.4,"Analog input pin"
OSC2=PORTA.4,"Crystal/Resonator"
CLKOUT=PORTA.4,"FOSC/4 output"
RA5=PORTA.5,"Bi-directional I/O pin (with interrupt on change)<br>Internal software programmable weak pull-up"
T1CKI=PORTA.5,"Timer1 clock"
OSC1=PORTA.5,"Crystal/Resonator"
CLKIN=PORTA.5,"External clock input/RC oscillator connection"
PORTB="PORTB aliased to PORTC see PORTC"
RC0=PORTC.0,"Bi-directional I/O pin"
AN4=PORTC.0,"Analog input pin"
RC1=PORTC.1,"Bi-directional I/O pin"
AN5=PORTC.1,"Analog input pin"
RC2=PORTC.2,"Bi-directional I/O pin"
AN6=PORTC.2,"Analog input pin"
RC3=PORTC.3,"Bi-directional I/O pin"
AN7=PORTC.3,"Analog input pin"
RC4=PORTC.4,"Bi-directional I/O pin"
RC5=PORTC.5,"Bi-directional I/O pin"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4] 
GIE=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
TMR0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INT0IE=INTCON.4,"RA0 External Interrupt Enable"
RAIE=INTCON.3,"RA Port Change Interrupt Enable"
TMR0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INT0IF=INTCON.1,"RA0 External Interrupt Flag"
RAIF=INTCON.0,"RB Port Interrupt Flag"
EEIF=PIR1.7,"EEPROM Write Operation Interrupt Flag bit"
ADIF=PIR1.6,"A/D Converter Interrupt Flag bit"
CMIF=PIR1.3,"Comparator Interrupt Flag bit£
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag"
TMR1L="Holding register for the Least Significant Byte of the 16 bit TMR1 register"
TMR1LH="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
TMR1H="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
TMR1GE=T1CON.6,"Timer1 Gate Enable bit"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"
COUT=CMCON.6,"Comparator Output"
CINV=CMCON.4,"Comparator Output Inversion"
CIS=CMCON.3,"Comparator Input Switch"
CM2=CMCON.2,"Comparator Mode bit"
CM1=CMCON.1,"Comparator Mode bit"
CM0=CMCON.0,"Comparator Mode bit"
ADRESH="A/D result register high byte"
ADRESLH="A/D result register high byte"
ADFM=ADCON0.7,"A/D Result Formed Select bit"
VCFG=ADCON0.6,"VCFG: Voltage Reference bit"
CHS2=ADCON0.4,"Analog Channel Select bits"
CHS1=ADCON0.3,"Analog Channel Select bits"
CHS0=ADCON0.2,"Analog Channel Select bits"
NOT_DONE=ADCON0.1,"A/D Conversion Status flag"
GO_DONE=ADCON0.1,"A/D Conversion Enable"
ADON=ADCON0.0,"A/D ON bit"
NOT_RAPU=OPTION_REG.07,"PORTB Pull-up Enable"
INTEDG=OPTION_REG.6,"Interrupt Edge Select"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select"
PSA=OPTION_REG.3,"Prescaler Assignment"
PS2=OPTION_REG.2,"Prescaler Rate Select"
PS1=OPTION_REG.1,"Prescaler Rate Select"
PS0=OPTION_REG.0,"Prescaler Rate Select"
TRISA="PORTA data direction register",[0..5]
TRISB="TRISB aliased to TRISC see TRISC",[0..5]
TRISC="PORTC data direction register",[0..5]
EEIE=PIE1.7,"EE Write Complete Interrupt Enable bit"
ADIE=PIE1.6,"A/D Converter Interrupt Enable bit"
CMIE=PIE1.3,"Comparator Interrupt Enable bit"
TMR1IE=PIE1.0,"TMR1 Overflow Interrupt Enable"
NOT_POR=PCON.1,"Power-on Reset Status flag"
NOT_BOR=PCON.0,"Brown-out Reset Status flag"
CAL5=OSCCAL.7,"Signed Oscillator Calibration bit"
CAL4=OSCCAL.6,"Signed Oscillator Calibration bit"
CAL3=OSCCAL.5,"Signed Oscillator Calibration bit"
CAL2=OSCCAL.4,"Signed Oscillator Calibration bit"
CAL1=OSCCAL.3,"Signed Oscillator Calibration bit"
CAL0=OSCCAL.2,"Signed Oscillator Calibration bit"
ANS7=ANSEL.7,"Pin Analog / Digital Selection"
ANS6=ANSEL.6,"Pin Analog / Digital Selection"
ANS5=ANSEL.5,"Pin Analog / Digital Selection"
ANS4=ANSEL.4,"Pin Analog / Digital Selection"
ANS3=ANSEL.3,"Pin Analog / Digital Selection"
ANS2=ANSEL.2,"Pin Analog / Digital Selection"
ANS1=ANSEL.1,"Pin Analog / Digital Selection"
ANS0=ANSEL.0,"Pin Analog / Digital Selection"
WPUA5=WPU.5,"Weak Pull-up Register bit"
WPUA4=WPU.4,"Weak Pull-up Register bit"
WPUA2=WPU.2,"Weak Pull-up Register bit"
WPUA1=WPU.1,"Weak Pull-up Register bit"
WPUA0=WPU.0,"Weak Pull-up Register bit"
WPUA5=WPUA.5,"Weak Pull-up Register bit"
WPUA4=WPUA.4,"Weak Pull-up Register bit"
WPUA2=WPUA.2,"Weak Pull-up Register bit"
WPUA1=WPUA.1,"Weak Pull-up Register bit"
WPUA0=WPUA.0,"Weak Pull-up Register bit"
IOCA5=IOC.5,"Interrupt-on-Change PORTA Control bit"
IOCA4=IOC.4,"Interrupt-on-Change PORTA Control bit"
IOCA3=IOC.3,"Interrupt-on-Change PORTA Control bit"
IOCA2=IOC.2,"Interrupt-on-Change PORTA Control bit"
IOCA1=IOC.1,"Interrupt-on-Change PORTA Control bit"
IOCA0=IOC.0,"Interrupt-on-Change PORTA Control bit"
IOCA5=IOCA.5,"Interrupt-on-Change PORTA Control bit"
IOCA4=IOCA.4,"Interrupt-on-Change PORTA Control bit"
IOCA3=IOCA.3,"Interrupt-on-Change PORTA Control bit"
IOCA2=IOCA.2,"Interrupt-on-Change PORTA Control bit"
IOCA1=IOCA.1,"Interrupt-on-Change PORTA Control bit"
IOCA0=IOCA.0,"Interrupt-on-Change PORTA Control bit"
VREN=VRCON.7,"CVREF Enable"
VRR=VRCON.5,"CVREF Range Selection"
VR3=VRCON.3,"CVREF value selection"
VR2=VRCON.2,"CVREF value selection"
VR1=VRCON.1,"CVREF value selection"
VR0=VRCON.0,"CVREF value selection" 
ADRESL="Least Significant 2 bits of the left shifted result<BR>or 8 bits of the right shifted result" 
ADRES="A/D result as a 8 bit value",[0..7]
ADCS2=ADCON1.6,"A/D Conversion Clock Select bit"
ADCS1=ADCON1.5,"A/D Conversion Clock Select bit"
ADCS0=ADCON1.4,"A/D Conversion Clock Select bit"
EEDAT="EEPROM data register"
EEDATA="EEPROM data register"
EEADR="EEPROM address register",[0..6]
EEDATH="EEPROM data register high byte",[0..5]
EEADRH="EEPROM address register high byte",[0..4]
WRERR=EECON1.3,"EEPROM Error Flag"
WREN=EECON1.2,"EEPROM Write/Enable"
WR=EECON1.1,"Write Control"
RD=EECON1.0,"Read Control"
EECON2="EEPROM control register2 (not a physical register)"

