** BITNAMES **
INDF="Addressing this location uses contents of FSR to address data memory<br>(not a physical register)"
TMR0="Timer0 module's register"
PCL="Program counter's (PC) least significant byte"
IRP=STATUS.7,"Register bank select bit, used for indirect addressing"
RP1=STATUS.6,"Register bank select bit, used for direct addressing"
RP0=STATUS.5,"Register bank select bit, used for direct addressing"
NOT_TO=STATUS.4,"Time Out bit"
NOT_PD=STATUS.3,"Power Down bit"
Z=STATUS.2,"Zero bit"
DC=STATUS.1,[protect], "Digit Carry bit"
C=STATUS.0,"Carry bit"
FSR="Indirect data memory address pointer"
RA7=PORTA.7,"Bi-directional I/O port"
OSC1=PORTA.7,"Oscillator crystal input"
CLKIN=PORTA.7,"External clock source input.<br> RC Biasing pin."
RA6=PORTA.6,"Bi-directional I/O port"
OSC2=PORTA.6,"Oscillator crystal output.<br>Connects to crystal or resonator in Crystal Oscillator mode"
CLKOUT=PORTA.6,"In RC/INTOSC mode, OSC2 pin can output CLKOUT,<br> which has 1/4 the frequency of OSC1."
RA5=PORTA.5,"Input port"
NOT_MCLR=PORTA.5,"Master clear<br>(reset input/programming voltage input)"
Vpp=PORTA.5,"Programming voltage input"
RA4=PORTA.4,"Bi-directional I/O port"
T0CKI=PORTA.4,"TMR0 Clock Input"
CMP2=PORTA.4,"Comparator 2 output"
RA3=PORTA.3,"Bi-directional I/O port"
AN3=PORTA.3,"Analog comparator input"
CMP1=PORTA.3,"Comparator 1 output"
RA2=PORTA.2,"Bi-directional I/O port"
AN2=PORTA.2,"Analog comparator input"
VREF=PORTA.2,"VREF output"
RA1=PORTA.1,"Bi-directional I/O port"
AN1=PORTA.1,"Analog comparator input"
RA0=PORTA.0,"Bi-directional I/O port"
AN0=PORTA.0,"Analog comparator input"
RB7=PORTB.7,"Bi-directional I/O port<br> Interrupt-on-pin change.<br>Can be software programmed for internal weak pull-up."
T1OSI=PORTB.7,"Timer1 oscillator input"
PGD=PORTB.7,"ICSP data I/O"
RB6=PORTB.6,"Bi-directional I/O port<br> Interrupt-on-pin change.<br>Can be software programmed for internal weak pull-up."
T1OSO=PORTB.6,"Timer1 oscillator output"
T1CKI=PORTB.6,"Timer1 clock input"
PGC=PORTB.6,"ICSP Programming clock"
RB5=PORTB.5,"Bi-directional I/O port<br> Interrupt-on-pin change.<br>Can be software programmed for internal weak pull-up."
RB4=PORTB.4,"Bi-directional I/O port<br> Interrupt-on-pin change.<br>Can be software programmed for internal weak pull-up."
PGM=PORTB.4,"Low voltage programming input pin"
RB3=PORTB.3,"Bi-directional I/O port<br>Can be software programmed for internal weak pull-up"
CCP1=PORTB.3,"Capture/Compare/PWM I/O"
RB2=PORTB.2,"Bi-directional I/O port<br>Can be software programmed For internal weak pull-up"
TX=PORTB.2,"USART transmit pin"
CK=PORTB.2,"Synchronous clock I/O"
RB1=PORTB.1,"Bi-directional I/O port<br>Can be software programmed For internal weak pull-up"
RX=PORTB.1,"USART receive pin"
DT=PORTB.1,"Synchronous data I/O"
RB0=PORTB.0,"Bi-directional I/O port<br>Can be software programmed For internal weak pull-up"
INT=PORTB.0,"External interrupt input"
PCLATH="Write buffer for the program counter (PC) upper 5 bits",[0..4]
GIE=INTCON.7,"Global Interrupt Enable"
PEIE=INTCON.6,"Peripheral Interrupt Enable"
T0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INTE=INTCON.4,"RB0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
T0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INTF=INTCON.1,"RB0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"
EEIF=PIR1.7,"EEPROM Write Operation Interrupt Flag"
CMIF=PIR1.6,"Comparator Interrupt Flag"
RCIF=PIR1.5,"USART Receive Interrupt Flag"
TXIF=PIR1.4,"USART Transmit Interrupt Flag"
CCP1IF=PIR1.2,"CCP1 Interrupt Flag"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag bit"
TMR1L="Holding register for the Least Significant Byte of the 16 bit TMR1 register"
TMR1H="Holding register for the Most Significant Byte of the 16 bit TMR1 register"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"
TMR2="Timer2 module's register"
TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 ON"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"
CCPR1L="Capture or Compare or PWM register1 (LSB)"
CCPR1H="Capture or Compare or PWM register1 (MSB)"
CCP1X=CCP1CON.5,"PWM Least Significant bits"
CCP1Y=CCP1CON.4,"PWM Least Significant bits"
CCP1M3=CCP1CON.3,"CCPx Mode Select bits"
CCP1M2=CCP1CON.2,"CCPx Mode Select bits"
CCP1M1=CCP1CON.1,"CCPx Mode Select bits"
CCP1M0=CCP1CON.0,"CCPx Mode Select bits"
SPEN=RCSTA.7,"Serial Port Enable"
RX9=RCSTA.6,"9-bit Receive Enable""   
SREN=RCSTA.5,"Single Receive Enable"
CREN=RCSTA.4,"Continuous Receive Enable"
ADEN=RCSTA.3,"Address Detect Enable"
FERR=RCSTA.2,"Framing Error Enable"
OERR=RCSTA.1,"Overrun Error Enable"
RX9D=RCSTA.0,"9th bit of received data (Can be parity bit)"
TXREG="USART transmit data register"
RCREG="USART receive data register"
C2OUT=CMCON.7,"Comparator 2 output"
C1OUT=CMCON.6,"Comparator 1 output"
C2INV=CMCON.5,"Comparator 2 output inversion"
C1INV=CMCON.4,"Comparator 1 output inversion"
CIS=CMCON.3,"Comparator Input Switch"
CM2=CMCON.2,"Comparator mode bits"
CM1=CMCON.1,"Comparator mode bits"
CM0=CMCON.0,"Comparator mode bits"
NOT_RBPU=OPTION_REG.07,"PORTB Pull-up Enable bit"
INTEDG=OPTION_REG.6,"Interrupt Edge Select bit"
T0CS=OPTION_REG.5,"TMR0 Clock Source Select bit"
T0SE=OPTION_REG.4,"TMR0 Source Edge Select bit"
PSA=OPTION_REG.3,"Prescaler Assignment bit"
PS2=OPTION_REG.2,"Prescaler Rate Select bits"
PS1=OPTION_REG.1,"Prescaler Rate Select bits"
PS0=OPTION_REG.0,"Prescaler Rate Select bits"
TRISA="PORTA data direction register"
TRISB="PORTB data direction register"
EEIE=PIE1.7,"EE Write Complete Interrupt Enable"
CMIE=PIE1.6,"Comparator Interrupt Enable"
RCIE=PIE1.5,"USART Receive Interrupt Enable"
TXIE=PIE1.4,"USART Transmit Interrupt Enable"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable"
TMR1IE=PIE1.0,"TMR1 Overflow Interrupt Enable"
OSCF=PCON.3,"INTOSC Oscillator Frequency bit"
NOT_POR=PCON.1,"Power-on Reset Status bit"
NOT_BOR=PCON.0,"Brown-out Reset Status bit"
PR2="Timer2 period register"
CSRC=TXSTA.7,"Clock Source Select bit"
TX9=TXSTA.6,"9-bit Transmit Enable bit" 
TXEN=TXSTA.5,"Transmit Enable bit"
SYNC=TXSTA.4,"USART Mode Select bit"
BRGH=TXSTA.2,"High Baud Rate Select bit"
TRMT=TXSTA.1,"Transmit Shift Register Status bit"
TX9D=TXSTA.0,"9th bit of transmit data. Can be parity bit."
SPBRG="Baud Rate Generator Register"
EEDATA="EEPROM data register"
EEADR="EEPROM address register.<br>Specifies one of 256 locations of EEPROM Read/Write Operation"
WRERR=EECON1.3,"EEPROM Error Flag bit"
WREN=EECON1.2,"EEPROM Write Enable bit"
WR=EECON1.1,"Write Control bit"
RD=EECON1.0,"Read Control bit"
EECON2="EEPROM control register2 (not a physical register)"
VREN=VRCON.7,"VREF Enable bit"
VROE=VRCON.6,"VREF Output Enable bit"
VRR=VRCON.5,"VREF Range selection bit"
VR3=VRCON.3,"VREF value selection"
VR2=VRCON.2,"VREF value selection"
VR1=VRCON.1,"VREF value selection"
VR0=VRCON.0,"VREF value selection"


