** BITNAMES **
 TOSU="Top-of-Stack Upper Byte (TOS<20:16>)",[0..4]
TOSH="Top-of-Stack High Byte (TOS<15:8>)"
TOSLH="Top-of-Stack High Byte (TOS<15:8>)"
TOSL="Top-of-Stack Low Byte (TOS<7:0>)"

STKFUL=STKPTR.7,"Stack Full Flag bit"
STKUN=STKPTR.6,"Stack Underflow Flag bit"
SP4=STKPTR.4,"Stack Pointer Location bit"
SP3=STKPTR.3,"Stack Pointer Location bit"
SP2=STKPTR.2,"Stack Pointer Location bit"
SP1=STKPTR.1,"Stack Pointer Location bit"
SP0=STKPTR.0,"Stack Pointer Location bit"
PCLATU="Holding Register for PC<20:16>",[0..4]
BIT21=PCLATU.5
PCLATH="Holding Register for PC<15:8>"
PCL="PC Low Byte (PC<7:0>)"

TBLPTRU="Program Memory Table Pointer<br>Upper Byte (TBLPTR<20:16>",[0..4]
TBLPTRH="Program Memory Table Pointer High Byte (TBLPTR<15:8>)"
TBLPTRLH="Program Memory Table Pointer High Byte (TBLPTR<15:8>)"
TBLPTRL="Program Memory Table Pointer Low Byte (TBLPTR<7:0>)"
TABLAT="Program Memory Table Latch"
PRODH="Product Register High Byte"
PRODLH="Product Register High Byte"
PRODL="Product Register Low Byte"

GIE=INTCON.7,"Global Interrupt Enable<BR>use in conjunction with IPEN (RCON<7>)"
GIEH=INTCON.7," Enable all high priority interrupts<br>use in conjunction with IPEN (RCON<7>)"
PEIE=INTCON.6,"Peripheral Interrupt Enable<br>use in conjunction with IPEN (RCON<7>)"
GIEL=INTCON.6,"Low priority peripheral interrupt<br>use in conjunction with IPEN (RCON<7>)"
T0IE=INTCON.5,"TMR0 Overflow Interrupt Enable"
INT0IE=INTCON.4,"INT0 External Interrupt Enable"
RBIE=INTCON.3,"RB Port Change Interrupt Enable"
TMR0IF=INTCON.2,"TMR0 Overflow Interrupt Flag"
INT0IF=INTCON.1,"INT0 External Interrupt Flag"
RBIF=INTCON.0,"RB Port Interrupt Flag"

INTCON1="Aliased to INTCON"
 
NOT_RBPU=INTCON2.7,"PORTB Pull-up Enable bit"
INTEDG0=INTCON2.6,"External Interrupt0 Edge Select bit"
INTEDG1=INTCON2.5,"External Interrupt1 Edge Select bit"
INTEDG2=INTCON2.4,"External Interrupt2 Edge Select bit"
INTEDG2=INTCON2.3,"External Interrupt3 Edge Select bit"
TMR0IP=INTCON2.2,"TMR0 Overflow Interrupt Priority bit"
INT3IP=INTCON2.1,"INT3 External Interrupt Priority bit"
RBIP=INTCON2.0,"RB Port Change Interrupt Priority bit"

INT2IP=INTCON3.7,"INT2 External Interrupt Priority bit"
INT1IP=INTCON3.6,"INT1 External Interrupt Priority bit"
INT3IE=INTCON3.5,"INT3 External Interrupt Enable"
INT2IE=INTCON3.4,"INT2 External Interrupt Enable"
INT1IE=INTCON3.3,"INT1 External Interrupt Enable"
INT3IF=INTCON3.2,"INT3 External Interrupt Flag"
INT2IF=INTCON3.1,"INT2 External Interrupt Flag"
INT1IF=INTCON3.0,"INT1 External Interrupt Flag"

INDF0="Uses contents of FSR0 to address data memory value of FSR0 not changed (not a physical register)"

POSTINC0="Uses contents of FSR0 to address data memory value of FSR0 post-incremented<br>(not a physical register)"
POSTDEC0="Uses contents of FSR0 to address data memory - value of FSR0 post-decremented <br>(not a physical register)"
PREINC0="Uses contents of FSR0 to address data memory - value of FSR0 pre-incremented <br>(not a physical register)"
PLUSW0="Uses contents of FSR0 to address data memory - value of FSR0 pre-incremented<BR>(not a physical register) - value of FSR0 offset by value in WREG"

FSR0H="Indirect Data Memory Address Pointer 0 High Byte",[0..3]
FSR0LH="Indirect Data Memory Address Pointer 0 Low Byte<br>aliased to FSR0L"
FSR0L="Indirect Data Memory Address Pointer 0 Low Byte"

WREG="Working Register"

INDF1="Uses contents of FSR1 to address data memory value of FSR1 not changed (not a physical register)"

INDF1="Uses contents of FSR1 to address data memory value of FSR1 not changed (not a physical register)"

POSTINC1="Uses contents of FSR1 to address data memory value of FSR1 post-incremented<br>(not a physical register)"
POSTDEC1="Uses contents of FSR1 to address data memory - value of FSR1 post-decremented <br>(not a physical register)"
PREINC1="Uses contents of FSR1 to address data memory - value of FSR1 pre-incremented <br>(not a physical register)"
PLUSW1="Uses contents of FSR1 to address data memory - value of FSR1 pre-incremented<BR>(not a physical register) - value of FSR1 offset by value in WREG"

FSR1H="Indirect Data Memory Address Pointer 1 High Byte",[0..3]
FSR1LH="Indirect Data Memory Address Pointer 1 Low Byte<br>aliased to FSR1L"
FSR1L="Indirect Data Memory Address Pointer 1 Low Byte"

BSR="Bank Select Register",[0..3]

INDF2="Uses contents of FSR2 to address data memory value of FSR2 not changed (not a physical register)"

POSTINC2="Uses contents of FSR2 to address data memory value of FSR2 post-incremented<br>(not a physical register)"
POSTDEC2="Uses contents of FSR2 to address data memory - value of FSR2 post-decremented <br>(not a physical register)"
PREINC2="Uses contents of FSR2 to address data memory - value of FSR2 pre-incremented <br>(not a physical register)"
PLUSW2="Uses contents of FSR2 to address data memory - value of FSR2 pre-incremented<BR>(not a physical register) - value of FSR2 offset by value in WREG"

FSR2H="Indirect Data Memory Address Pointer 2 High Byte",[0..3]
FSR2LH="Indirect Data Memory Address Pointer 2 Low Byte<br>aliased to FSR2L"
FSR2L="Indirect Data Memory Address Pointer 2 Low Byte"


N=STATUS.4,"Negative bit"
OV=STATUS.3,"Overflow bit"
Z=STATUS.2,"Zero flag"
DC=STATUS.1,[protect], "Digit Carry flag"
C=STATUS.0,"Carry flag"

TMR0L="Timer0 Module Low Byte Register"
TMR0LH="Aliased to Timer0 Module ???? Byte Register"
TMR0H="Timer0 Module High Byte Register"

T0CON="TIMER0 CONTROL REGISTER"
TMR0ON=T0CON.7,"Timer0 On/Off Control bit"
T08BIT=T0CON.6,"Timer0 8-bit/16-bit Control bit"
T0CS=T0CON.5,"Timer0 Clock Source Select bit"
T0SE=T0CON.4,"Timer0 Source Edge Select bit"
PSA=T0CON.3,"Timer0 Prescaler Assignment bit"
T0PS2=T0CON.2,"Timer0 Prescaler Select bit"
T0PS1=T0CON.1,"Timer0 Prescaler Select bit"
T0PS0=T0CON.0,"Timer0 Prescaler Select bit"

OSCCON="OSCCON REGISTER"
SCS=OSCCON.0,"System Clock Switch bit"

IRVST=LVDCON.5,"Internal Reference Voltage Stable Flag"
LVDEN=LVDCON.4,"Low Voltage Detect Power Enable bit"
LVDL3=LVDCON.3,"Low Voltage Detection Limit bit"
LVDL2=LVDCON.2,"Low Voltage Detection Limit bit"
LVDL1=LVDCON.1,"Low Voltage Detection Limit bit"
LVDL0=LVDCON.0,"Low Voltage Detection Limit bit"

SWDTE=WDTCON.0,"Software Controlled Watchdog Timer Enable bit"

IPEN=RCON.7,"Interrupt Priority Enable bit"
RI=RCON.4,"RESET Instruction Flag bit"
NOT_TO=RCON.3,"Watchdog Time-out Flag bit"
NOT_PD=RCON.2,"Power-down Detection Flag bit"
NOT_POR=RCON.1,"Power-on Reset Status bit"
NOT_BOR=RCON.0,"Brown-out Reset Status bit"

TMR1H="Timer1 Register High Byte"
TMR1LH="Timer1 Register High Byte"
TMR1L="Timer1 Register Low Byte"

RD16=T1CON.7,"16-bit Read/Write Mode Enable bit"
T1CKPS1=T1CON.5,"Timer1 Input Clock Prescale Select bits"
T1CKPS0=T1CON.4,"Timer1 Input Clock Prescale Select bits"
T1OSCEN=T1CON.3,"Timer1 Oscillator Enable Control"
NOT_T1SYNC=T1CON.2,"Timer1 External Clock Input Synchronization Control"
TMR1CS=T1CON.1,"Timer1 Clock Source Select"
TMR1ON=T1CON.0,"Timer1 ON"

TMR2="Timer2 module's register"
PR2="Timer2 period register"

TOUTPS3=T2CON.6,"Timer2 Output Postscale Select bits"
TOUTPS2=T2CON.5,"Timer2 Output Postscale Select bits"
TOUTPS1=T2CON.4,"Timer2 Output Postscale Select bits"
TOUTPS0=T2CON.3,"Timer2 Output Postscale Select bits"
TMR2ON=T2CON.2,"Timer2 ON"
T2CKPS1=T2CON.1,"Timer2 Clock Prescale Select bits"
T2CKPS0=T2CON.0,"Timer2 Clock Prescale Select bits"

SSPBUF="Synchonous serial port receive buffer or transmit register"
SSPADD="Synchronous serial port (I2C mode) address register"
SMP=SSPSTAT.7,"Sample bit"
CKE=SSPSTAT.6,"SPI Clock Edge Select"
D_A=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
DATA_ADDR=SSPSTAT.5,"Data/NOT Address bit (I2C mode only)"
P=SSPSTAT.4,"I2C Stop"
I2C_STP=SSPSTAT.4,"I2C Stop"
S=SSPSTAT.3,"I2C Start"
I2C_STR=SSPSTAT.3,"I2C Start"
R_W=SSPSTAT.2,"Read/Write bit information (I2C mode only)"
UA=SSPSTAT.1,"Update Address (10-bit I2C mode only)"
BF=SSPSTAT.0,"Buffer Full Status flag"

SMP=SSPCON1.7,"Sample bit"
CKE=SSPCON1.6,"SPI Clock Edge Select bit"
D_A=SSPCON1.5,"Data/Address bit"
P=SSPCON1.4,"STOP bit"
S=SSPCON1.3,"START bit"
R_W=SSPCON1.2,"Read/Write bit information"
UA=SSPCON1.1,"Update Address bit"
BF=SSPCON1.0,"Buffer Full Status bit (Receive mode only)"

GCEN=SSPCON2.7,"General Call Enable bit (In I2C slave mode only)"
ACKSTAT=SSPCON2.6,"Acknowledge Status bit (In I2C master mode only)"
ACKDT=SSPCON2.5,"Acknowledge Data bit (In I2C master mode only)"
ACKEN=SSPCON2.4,"Acknowledge Sequence Enable bit (In I2C master mode only)"
RCEN=SSPCON2.3,"Receive Enable bit (In I2C master mode only)"
PEN=SSPCON2.2,"Stop Condition Enable bit (In I2C master mode only)"
RSEN=SSPCON2.1,"Repeated Start Condition Enabled bit (In I2C master mode only)"
SEN=SSPCON2.0,"Start Condition Enabled bit (In I2C master mode only)"

ADRESL="A/D Register low byte" 
ADRESH="A/D Register high byte" 
ADRESLH="A/D Register high byte" 
ADRES="A/D result as a 16 bit value <br> This feature is specific to the PROTON compiler",[0..0]

CHS3=ADCON0.5,"Analog Channel Select bits"
CHS2=ADCON0.4,"Analog Channel Select bits"
CHS1=ADCON0.3,"Analog Channel Select bits"
CHS0=ADCON0.2,"Analog Channel Select bits"
NOT_DONE=ADCON0.1,"A/D Conversion Status flag"
GO_DONE=ADCON0.1,"A/D Conversion Enable"
ADON=ADCON0.0,"A/D ON bit"

VCFG1=ADCON1.5,"Voltage Reference Configuration bits"
VCFG0=ADCON1.4,"Voltage Reference Configuration bits"
PCFG3=ADCON1.3,"A/D Port Configuration Control bits"
PCFG2=ADCON1.2,"A/D Port Configuration Control bits"
PCFG1=ADCON1.1,"A/D Port Configuration Control bits"
PCFG0=ADCON1.0,"A/D Port Configuration Control bits"

ADFM=ADCON2.7,"A/D Result Format Select bit"
ADCS2=ADCON2.2,"A/D Conversion Clock Select bits"
ADCS1=ADCON2.1,"A/D Conversion Clock Select bits"
ADCS0=ADCON2.0,"A/D Conversion Clock Select bits"

CCPR1H="Capture/Compare/PWM register1 (MSB)"
CCPR1L="Capture/Compare/PWM register1 (LSB)"
CCPR1LH="Capture/Compare/PWM register1 (MSB)"

DC1B1=CCP1CON.5,"PWM1 Least Significant bits"
DC1B0=CCP1CON.4,"PWM1 Least Significant bits"
CCP1M3=CCP1CON.3,"CCP1 Mode Select"
CCP1M2=CCP1CON.2,"CCP1 Mode Select"
CCP1M1=CCP1CON.1,"CCP1 Mode Select"
CCP1M0=CCP1CON.0,"CCP1 Mode Select"

CCPR2H="Capture/Compare/PWM register2 (MSB)"
CCPR2L="Capture/Compare/PWM register2 (LSB)"
CCPR2LH="Capture/Compare/PWM register2 (MSB)"

DC2B1=CCP2CON.5,"PWM2 Least Significant bits"
DC2B0=CCP2CON.4,"PWM2 Least Significant bits"
CCP2M3=CCP2CON.3,"CCP2 Mode Select"
CCP2M2=CCP2CON.2,"CCP2 Mode Select"
CCP2M1=CCP2CON.1,"CCP2 Mode Select"
CCP2M0=CCP2CON.0,"CCP2 Mode Select"

CCPR3H="Capture/Compare/PWM register3 (MSB)"
CCPR3L="Capture/Compare/PWM register3 (LSB)"
CCPR3LH="Capture/Compare/PWM register3 (MSB)"

DCCP3X=CCP3CON.5,"PWM3 Least Significant bits"
DCCP3Y=CCP3CON.4,"PWM3 Least Significant bits"
CCP3M3=CCP3CON.3,"CCP3 Mode Select"
CCP3M2=CCP3CON.2,"CCP3 Mode Select"
CCP3M1=CCP3CON.1,"CCP3 Mode Select"
CCP3M0=CCP3CON.0,"CCP3 Mode Select"

CVREN=CVRCON.7,"Comparator Voltage Reference Enable bit"
CVROE=CVRCON.6,"Comparator VREF Output Enable bit"
CVRR=CVRCON.5,"Comparator VREF Range Selection bit"
CVRSS=CVRCON.4,"Comparator VREF Source Selection bit"
CVR3=CVRCON.3,"CVREF value selection"
CVR2=CVRCON.2,"CVREF value selection"
CVR1=CVRCON.1,"CVREF value selection"
CVR0=CVRCON.0,"CVREF value selection"

C2OUT=CMCON.7,"Comparator 1 Output"
C1OUT=CMCON.6,"Comparator 1 Output"
C2INV=CMCON.5,"Comparator 2 Output Inversion"
C1INV=CMCON.4,"Comparator 1 Output Inversion"
CIS=CMCON.3,"Comparator Input Switch"
CM2=CMCON.2,"Comparator Mode bit"
CM1=CMCON.1,"Comparator Mode bit"
CM0=CMCON.0,"Comparator Mode bit"

TMR3H="Timer3 Register High Byte"
TMR3LH="Timer3 Register High Byte"
TMR3l="Timer3 Register Low Byte"

RD16=T3CON.7,"16-bit Read/Write Mode Enable bit"
T3CCP2=T3CON.6,"Timer3 (bit6) and Timer1 (bit3) to CCPx Enable bits"
T3CKPS1=T3CON.5,"Timer3 Input Clock Prescale Select bits" 
T3CKPS0=T3CON.4,"Timer3 Input Clock Prescale Select bits" 
T3CCP1=T3CON.3,"Timer3 (bit6) and Timer1 (bit3) to CCPx Enable bits"
NOT_T3=T3CON.2,"Timer3 External Clock Input Synchronization Control bit"
TMR3CS=T3CON.1,"Timer3 Clock Source Select bit"
TMR3ON=T3CON.0,"Timer3 On enable bit"

IBF=PSPCON.7,"Input Buffer Full Status"
OBF=PSPCON.6,"Output Buffer Full Status bit"
IBOV=PSPCON.5,"Input Buffer Overflow Detect bit"
PSPMODE=PSPCON.4,"Parallel Slave Port Mode Select bit"

SPBRG="USART1 Baud Rate Generator"
RCREG="USART1 Receive Register"
TXREG="USART1 Transmit Register"

CSRC=TXSTA.7,"Clock Source Select bit (Usart 1)"
TX9=TXSTA.6,"9-bit Transmit Enable (Usart 1)"
NOT_TX8=TXSTA.6,"8-bit Transmit Enable (Usart 1)" 
TX8_9=TXSTA.6,"9/8-bit Transmit Enable (Usart 1)" 
TXEN=TXSTA.5,"Transmit Enable (Usart 1)"
SYNC=TXSTA.4,"USART Mode Select bit (Usart 1)"
BRGH=TXSTA.2,"High Baud Rate Select bit (Usart 1)"
TRMT=TXSTA.1,"Transmit Shift Register Status flag (Usart 1)"
TX9D=TXSTA.0,"9th bit of transmit data. Can be parity bit. (Usart 1)"

SPEN=RCSTA.7,"Serial Port Enable (Usart 1)"
RX9=RCSTA.6,"9-bit Receive Enable (Usart 1)"
SREN=RCSTA.5,"Single Receive Enable (Usart 1)"
CREN=RCSTA.4,"Continuous Receive Enable (Usart 1)"
ADDEN=RCSTA.3,"Address Detect Enable (Usart 1)"
FERR=RCSTA.2,"Framing Error (Usart 1)"
OERR=RCSTA.1,"Overrun Error (Usart 1)"
RX9D=RCSTA.0,"9th bit of received data (Can be parity bit) (Usart 1)"

SPBRG1="USART1 Baud Rate Generator"
RCREG1="USART1 Receive Register"
TXREG1="USART1 Transmit Register"

CSRC1=TXSTA1.7,"Clock Source Select bit (Usart 1)"
TX91=TXSTA1.6,"9-bit Transmit Enable (Usart 1)"
NOT_TX1=TXSTA1.6,"8-bit Transmit Enable (Usart 1)" 
TX8_91=TXSTA1.6,"9/8-bit Transmit Enable (Usart 1)" 
TXEN1=TXSTA1.5,"Transmit Enable (Usart 1)"
SYNC1=TXSTA1.4,"USART Mode Select bit (Usart 1)"
BRGH1=TXSTA1.2,"High Baud Rate Select bit (Usart 1)"
TRMT1=TXSTA1.1,"Transmit Shift Register Status flag (Usart 1)"
TX9D1=TXSTA1.0,"9th bit of transmit data. Can be parity bit. (Usart 1)"

SPEN1=RCSTA1.7,"Serial Port Enable (Usart 1)"
RX91=RCSTA1.6,"9-bit Receive Enable (Usart 1)"
SREN1=RCSTA1.5,"Single Receive Enable (Usart 1)"
CREN1=RCSTA1.4,"Continuous Receive Enable (Usart 1)"
ADDEN1=RCSTA1.3,"Address Detect Enable (Usart 1)"
FERR1=RCSTA1.2,"Framing Error (Usart 1)"
OERR1=RCSTA1.1,"Overrun Error (Usart 1)"
RX9D1=RCSTA1.0,"9th bit of received data (Can be parity bit) (Usart 1)" 

EEADRH="EE Adr Register High byte",[0..1]
EEADR="Data EEPROM Address Register"
EEDAT="Data EEPROM Data Register"
EEDATA="Data EEPROM Data Register"
EECON2="EEPROM control register2 (not a physical register)"

EEPGD=EECON1.7,"FLASH Program or Data EEPROM Memory Select bit"
CFGS=EECON1.6,"FLASH Program/Data EEPROM or Configuration Select bit"
FREE=EECON1.4,"FLASH Row Erase Enable bit"
WRERR=EECON1.3,"EEPROM Error Flag"
WREN=EECON1.2,"EEPROM Write/Enable"
WR=EECON1.1,"Write Control"
RD=EECON1.0,"Read Control"

RC2IP=IPR3.5,"USART2 Receive Interrupt Priority bit"
TX2IP=IPR3.4,"USART2 Transmit Interrupt Priority bit"
TMR4IP=IPR3.3,"TMR4 to PR4 Match Interrupt Priority bit"
CCP5IP=IPR3.2,"CCPx Interrupt Priority bit (CCP Modules 3, 4 and 5)"
CCP4IP=IPR3.1,"CCPx Interrupt Priority bit (CCP Modules 3, 4 and 5)"
CCP3IP=IPR3.0,"CCPx Interrupt Priority bit (CCP Modules 3, 4 and 5)"

RC2IF=PIR3.5,"USART2 Receive Interrupt Flag bit"
TX2IF=PIR3.4,"USART2 Transmit Interrupt Flag bit"
TMR4IF=PIR3.3,"TMR3 Overflow Interrupt Flag bit"
CCP5IF=PIR3.2,"CCPx Interrupt Flag bit (CCP Modules 3,4 and 5)"
CCP4IF=PIR3.1,"CCPx Interrupt Flag bit (CCP Modules 3,4 and 5)"
CCP3IF=PIR3.0,"CCPx Interrupt Flag bit (CCP Modules 3,4 and 5)"

RC2IE=PIE3.5,"USART2 Receive Interrupt Enable bit"
TX2IE=PIE3.4,"USART2 Transmit Interrupt Enable bit"
TMR4IE=PIE3.3,"TMR4 to PR4 Match Interrupt Enable bit"
CCP5IE=PIE3.2,"CCPx Interrupt Enable bit (CCP Modules 3, 4 and 5)"
CCP4IE=PIE3.1,"CCPx Interrupt Enable bit (CCP Modules 3, 4 and 5)"
CCP3IE=PIE3.0,"CCPx Interrupt Enable bit (CCP Modules 3, 4 and 5)"

CMIP=IPR2.6,"Comparator Interrupt Priority bit"
EEIP=IPR2.4,"Data EEPROM/FLASH Write Operation Interrupt Priority bit"
BCLIP=IPR2.3,"Bus Collision Interrupt Priority bit"
LVDIP=IPR2.2,"Low Voltage Detect Interrupt Priority bit"
TMR3IP=IPR2.1,"TMR3 Overflow Interrupt Priority bit"
CCP2IP=IPR2.0,"CCP2 Interrupt Priority bit"

CMIF=PIR2.6,"Comparator Interrupt Flag bit"
EEIF=PIR2.4,"Data EEPROM/FLASH Write Operation Interrupt Flag bit"
BCLIF=PIR2.3,"Bus Collision Interrupt Flag bit"
LVDIF=PIR2.2,"Low Voltage Detect Interrupt Flag bit"
TMR3IF=PIR2.1,"TMR3 Overflow Interrupt Flag bit
CCP2IF=PIR2.0,"CCP2 Interrupt Flag bit"
                  
CMIE=PIE2.6,"Comparator Interrupt Enable bit"
EEIE=PIE2.4,"Data EEPROM/FLASH Write Operation Interrupt Enable bit"
BCLIE=PIE2.3,"Bus Collision Interrupt Enable bit"
LVDIE=PIE2.2,"Low Voltage Detect Interrupt Enable bit"
TMR3IE=PIE2.1,"TMR3 Overflow Interrupt Enable bit"
CCP2IE=PIE2.0,"CCP2 Interrupt Enable bit"

PSPIP=IPR1.7,"Parallel Slave Port Read/Write Interrupt Priority bit"
ADIP=IPR1.6,"A/D Converter Interrupt Priority bit"
RC1IP=IPR1.5,"USART1 Receive Interrupt Priority bit"
TX1IP=IPR1.4,"USART1 Transmit Interrupt Priority bit"
SSPIP=IPR1.3,"Master Synchronous Serial Port Interrupt Priority bit"
CCP1IP=IPR1.2,"CCP1 Interrupt Priority bit"
TMR2IP=IPR1.1,"TMR2 to PR2 Match Interrupt Priority bit"
TMR1IP=IPR1.0,"TMR1 Overflow Interrupt Priority bit"

PSPIF=PIR1.7,"Parallel Slave Port Read/Write Interrupt Flag bit"
ADIF=PIR1.6,"A/D Converter Interrupt Flag bit"
RC1IF=PIR1.5,"USART1 Receive Interrupt Flag bit"
TX1IF=PIR1.4,"USART Transmit Interrupt Flag bit"
SSPIF=PIR1.3,"Master Synchronous Serial Port Interrupt Flag bit"
CCP1IF=PIR1.2,"CCP1 Interrupt Flag bit"
TMR2IF=PIR1.1,"TMR2 to PR2 Match Interrupt Flag bit"
TMR1IF=PIR1.0,"TMR1 Overflow Interrupt Flag bit"

PSPIE=PIE1.7,"Parallel Slave Port Read/Write Interrupt Enable bit"
ADIE=PIE1.6,"A/D Converter Interrupt Enable bit"
RC1IE=PIE1.5,"USART1 Receive Interrupt Enable bit"
TX1IE=PIE1.4,"USART1 Transmit Interrupt Enable bit"
SSPIE=PIE1.3,"Master Synchronous Serial Port Interrupt Enable bit"
CCP1IE=PIE1.2,"CCP1 Interrupt Enable bit"
TMR2IE=PIE1.1,"TMR2 to PR2 Match Interrupt Enable bit"
TMR1IE=PIE1.0,"TMR1 Overflow Interrupt Enable bit"

EBDIS=MEMCON.7,"External Bus Disable bit"
WAIT1=MEMCON.5,"Table Reads and Writes Bus Cycle Wait Count bits"
WAIT0=MEMCON.4,"Table Reads and Writes Bus Cycle Wait Count bits"
WM1=MEMCON.1,"TABLWT Operation with 16-bit Bus bits"
WM0=MEMCON.0,"TABLWT Operation with 16-bit Bus bits"

TRISJ="Data Direction Control Register for PORTJ"
TRISH="Data Direction Control Register for PORTH"
TRISG="Data Direction Control Register for PORTG",[0..4]
TRISF="Data Direction Control Register for PORTF"
TRISE="Data Direction Control Register for PORTE"
TRISD="Data Direction Control Register for PORTD"
TRISC="Data Direction Control Register for PORTC"
TRISB="Data Direction Control Register for PORTB"
TRISA="Data Direction Control Register for PORTA",[0..6]

LATJ="Read PORTA Data Latch, Write PORTA Data Latch"
LATH="Read PORTA Data Latch, Write PORTA Data Latch"
LATG="Read PORTA Data Latch, Write PORTA Data Latch",[0..4]
LATF="Read PORTA Data Latch, Write PORTA Data Latch"
LATE="Read PORTA Data Latch, Write PORTA Data Latch"
LATD="Read PORTA Data Latch, Write PORTA Data Latch"
LATC="Read PORTA Data Latch, Write PORTA Data Latch"
LATB="Read PORTA Data Latch, Write PORTA Data Latch"
LATA="Read PORTA Data Latch, Write PORTA Data Latch",[0..6]

RJ7=PORTJ.7,"Input/output port pin"
NOT_UB=PORTJ.7,"Upper Byte Select control for external memory interface"
RJ6=PORTJ.6,"Input/output port pin"
NOT_LB=PORTJ.6,"Lower Byte Select control for external memory interface"
RJ5=PORTJ.5,"Input/output port pin"
RJ4=PORTJ.4,"Input/output port pin"
BA0=PORTJ.4,"Byte Address 0 control for external memory interface"
RJ3=PORTJ.3,"Input/output port pin"
NOT_WRH=PORTJ.3,"Write High Byte control for external memory interface"
RJ2=PORTJ.2,"Input/output port pin"
NOT_WRL=PORTJ.2,"Write Low Byte control for external memory interface"
RJ1=PORTJ.1,"Input/output port pin"
NOT_OE=PORTJ.1,"Output Enable control for external memory interface"
RJ1=PORTJ.0,"Input/output port pin"
ALE=PORTJ.0,"Address Latch Enable control for external memory interface"

RH7=PORTH.7,"Input/output port pin"
AN15=PORTH.7,"analog input channel 15"
RH6=PORTH.6,"Input/output port pin"
AN14=PORTH.6,"analog input channel 14"
RH5=PORTH.5,"Input/output port pin"
AN13=PORTH.5,"analog input channel 13"
RH4=PORTH.4,"Input/output port pin"
AN12=PORTH.4,"analog input channel 12"
RH3=PORTH.3,"Input/output port pin"
A19=PORTH.3,"Address bit 19 for external memory interface"
RH2=PORTH.2,"Input/output port pin"
A18=PORTH.2,"Address bit 18 for external memory interface"
RH1=PORTH.1,"Input/output port pin"
A17=PORTH.1,"Address bit 17 for external memory interface"
RH0=PORTH.0,"Input/output port pin"
A16=PORTH.0,"Address bit 16 for external memory interface"

RG4=PORTG.4,"Input/output port pin"
CCP5=PORTG.4,"Capture5 input/Compare5 output/PWM5 output"
RG3=PORTG.3,"Input/output port pin"
CCP4=PORTG.3,"Capture4 input/Compare4 output/PWM4 output"
RG2=PORTG.2,"Input/output port pin"
RX2=PORTG.2,"Addressable USART2 Asynchronous Receive"
DT2=PORTG.2,"Addressable USART2 Synchronous Data"
RG1=PORTG.1,"Input/output port pin"
TX2=PORTG.1,"Addressable USART2 Asynchronous Transmit"
CK2=PORTG.1,"Addressable USART2 Synchronous Clock"
RG0=PORTG.0,"Input/output port pin"
CCP3=PORTG.0,"Capture3 input/Compare3 output/PWM3 output"

RF7=PORTF.7,"Input/output port pin"
NOT_SS=PORTF.7,"Slave Select pin for Synchronous Serial Port"
RF6=PORTF.6,"Input/output port pin"
AN11=PORTF.6,"Analog input/comparator input"
CVREF=PORTF.6,"Comparator reference output"
RF5=PORTF.5,"Input/output port pin"
AN10=PORTF.5,"Analog input/comparator input"
RF4=PORTF.4,"Input/output port pin"
AN9=PORTF.4,"Analog input/comparator input"
RF3=PORTF.3,"Input/output port pin"
AN8=PORTF.3,"Analog input/comparator input"
RF2=PORTF.2,"Input/output port pin"
AN7=PORTF.2,"Analog input"
C1OUT=PORTF.2,"Comparator 1 output"
RF1=PORTF.1,"Input/output port pin"
AN6=PORTF.1,"Analog input"
C2OUT=PORTF.1,"Comparator 2 output"
RF0=PORTF.0,"Input/output port pin"
AN5=PORTF.0,"Analog input"

RE7=PORTE.7,"Input/output port pin"
AD15=PORTE.7,"Address bit 15 for external memory interface"
CCP2=PORTE.7,"Capture2 input/Compare2 output/PWM output"
RE6=PORTE.6,"Input/output port pin"
AD14=PORTE.6,"Address bit 14 for external memory interface"
RE5=PORTE.5,"Input/output port pin"
AD13=PORTE.5,"Address bit 13 for external memory interface"
RE4=PORTE.4,"Input/output port pin"
AD12=PORTE.4,"Address bit 12 for external memory interface"
RE3=PORTE.3,"Input/output port pin"
AD11=PORTE.3,"Address bit 11 for external memory interface"
RE2=PORTE.2,"Input/output port pin"
AD10=PORTE.2,"Address bit 10 for external memory interface"
NOT_CS=PORTE.2,"Chip Select control for parallel slave port"
RE1=PORTE.1,"Input/output port pin"
AD9=PORTE.1,"Address bit 9 for external memory interface"
NOT_WR=PORTE.1,"Write control for parallel slave port"
RE0=PORTE.0,"Input/output port pin"
AD8=PORTE.0,"Address bit 8 for external memory interface"
NOT_RD=PORTE.0,"Read control for parallel slave port"

RD0=PORTD.0,"Input/output port pin"
PSP0=PORTD.0,"Parallel Slave Port (bit 0)"
RD1=PORTD.1,"Input/output port pin"
PSP1=PORTD.1,"Parallel Slave Port (bit 1)"
RD2=PORTD.2,"Input/output port pin"
PSP2=PORTD.2,"Parallel Slave Port (bit 2)"
RD3=PORTD.3,"Input/output port pin"
PSP3=PORTD.3,"Parallel Slave Port (bit 3)"
RD4=PORTD.4,"Input/output port pin"
PSP4=PORTD.4,"Parallel Slave Port (bit 4)"
RD5=PORTD.5,"Input/output port pin"
PSP5=PORTD.5,"Parallel Slave Port (bit 5)"
RD6=PORTD.6,"Input/output port pin"
PSP6=PORTD.6,"Parallel Slave Port (bit 6)"
RD7=PORTD.7,"Input/output port pin"
PSP7=PORTD.7,"Parallel Slave Port (bit 7)"

RC0=PORTC.0,"Input/output port pin"
T1OSO=PORTC.0,"Timer1 oscillator output"
T13CKI=PORTC.0,"Timer1/Timer3 clock input"
RC1=PORTC.1,"Input/output port pin"
T1OSI=PORTC.1,"Timer1 oscillator input<br>Capture2 input"
CCP2=PORTC.1,"Compare2 output<br>PWM2 output"
RC2=PORTC.2,"Input/output port pin"
CCP1=PORTC.2,"Capture1 input<br>Compare1 output<br>PWM1 output"
RC3=PORTC.3,"Input/output port pin"
SCK=PORTC.3,"Synchronous serial clock (SPI mode)"
SCL=PORTC.3,"Synchronous serial clock (I2C mode)"
RC4=PORTC.4,"Input/output port pin"
SDI=PORTC.4,"Data In (SPI mode)"
SDA=PORTC.4,"Data Input/output (I2C mode)"
RC5=PORTC.5,"Input/output port pin"
SDO=PORTC.5,"Sychronous Serial Port Output"
RC6=PORTC.6,"Input/output port pin"
TX1=PORTC.6,"USART Asynchronous Transmit (USART 1)"
SYN_CK=PORTC.6,"Synchronous Clock (USART 1)"
RC7=PORTC.7,"Input/output port pin"
RX1=PORTC.7,"USART Asynchronous Receive (USART 1)"
SYN_DT=PORTC.7,"Synchronous Data (USART 1)"

RB0=PORTB.0,"Input/output port pin<br>Internal software programmable weak pull-up"
INT0=PORTB.0,"External interrupt input"
RB1=PORTB.1,"Input/output port pin<br>Internal software programmable weak pull-up"
INT1=PORTB.1,"External interrupt input"
RB2=PORTB.2,"Input/output port pin<br>Internal software programmable weak pull-up"
INT2=PORTB.2,"External interrupt input"
RB3=PORTB.3,"Input/output port pin<br>Internal software programmable weak pull-up"
CCP2=PORTB.3,"Capture2 input/Compare2 output/PWM output"
INT3=PORTB.3,"External interrupt input"
RB4=PORTB.4,"Input/output port pin(with interrupt on change)<br>Internal software programmable weak pull-up"
KBI0=PORTB.4
RB5=PORTB.5,"Input/output port pin(with interrupt on change)<br>Internal software programmable weak pull-up"
KBI1=PORTB.5
PGM=PORTB.5,"Programming pin in LVP mode"
RB6=PORTB.6,"Input/output port pin(with interrupt on change)<br>Internal software programmable weak pull-up"
KBI2=PORTB.6
PGC=PORTB.6,"Serial programming clock"
RB7=PORTB.7,"Input/output port pin(with interrupt on change)<br>Internal software programmable weak pull-up"
KBI1=PORTB.7
PGD=PORTB.7,"Serial programming data"

RA0=PORTA.0,"Input/output port pin"
AN0=PORTA.0,"Analog input pin"
RA1=PORTA.1,"Input/output port pin"
AN1=PORTA.1,"Analog input pin"
RA2=PORTA.2,"Input/output port pin"
AN2=PORTA.2,"Analog input pin"
VREF_NEG=PORTA.2,"A/D reference voltage input VREF-"
RA3=PORTA.3,"Input/output port pin"
AN3=PORTA.3,"Analog input pin"
VREF_PLUS=PORTA.3,"A/D reference voltage input VREF+"
RA4=PORTA.4,"Input/output port pin<br>Output is open drain type"
T0CK1=PORTA.4,"External clock input for Timer0"
RA5=PORTA.5,"Input/output port pin"
AN4=PORTA.5,"Analog input pin"
LVDIN=PORTA.5,"low voltage detect input"
RA6=PORTA.6,"Input/output port pin"
OSC2=PORTA.6,"OSC2"
CLKO=PORTA.6,"Clock output"

TMR4="Timer4 Register"
PR4="Timer4 Period Register"

T4OUTPS3=T4CON.6,"Timer4 Output Postscale Select bits"
T4OUTPS2=T4CON.5,"Timer4 Output Postscale Select bits"
T4OUTPS1=T4CON.4,"Timer4 Output Postscale Select bits"
T4OUTPS0=T4CON.3,"Timer4 Output Postscale Select bits"
TMR4ON=T4CON.2,"Timer4 On bit"
T4CKPS1=T4CON.1,"Timer4 Clock Prescale Select bits"
T4CKPS0=T4CON.0,"Timer4 Clock Prescale Select bits"

CCPR4H="Capture/Compare/PWM register4 (MSB)"
CCPR4L="Capture/Compare/PWM register4 (LSB)"
CCPR4LH="Capture/Compare/PWM register4 (MSB)"

DCCP4X=CCP4CON.5,"PWM4 Least Significant bits"
DCCP4Y=CCP4CON.4,"PWM4 Least Significant bits"
CCP4M3=CCP4CON.3,"CCP4 Mode Select"
CCP4M2=CCP4CON.2,"CCP4 Mode Select"
CCP4M1=CCP4CON.1,"CCP4 Mode Select"
CCP4M0=CCP4CON.0,"CCP4 Mode Select"

CCPR5H="Capture/Compare/PWM register5 (MSB)"
CCPR5L="Capture/Compare/PWM register5 (LSB)"
CCPR5LH="Capture/Compare/PWM register5 (MSB)"

DCCP5X=CCP5CON.5,"PWM5 Least Significant bits"
DCCP5Y=CCP5CON.4,"PWM5 Least Significant bits"
CCP5M3=CCP5CON.3,"CCP5 Mode Select"
CCP5M2=CCP5CON.2,"CCP5 Mode Select"
CCP5M1=CCP5CON.1,"CCP5 Mode Select"
CCP5M0=CCP5CON.0,"CCP5 Mode Select"

SPBRG2="USART2 Baud Rate Generator"
RCREG2="USART2 Receive Register"
TXREG2="USART2 Transmit Register"

CSRC2=TXSTA2.7,"Clock Source Select bit (Usart 2)"
TX92=TXSTA2.6,"9-bit Transmit Enable (Usart 2)"
NOT_TX2=TXSTA2.6,"8-bit Transmit Enable (Usart 2)" 
TX8_92=TXSTA2.6,"9/8-bit Transmit Enable (Usart 2)" 
TXEN2=TXSTA2.5,"Transmit Enable (Usart 2)"
SYNC2=TXSTA2.4,"USART Mode Select bit (Usart 2)"
BRGH2=TXSTA2.2,"High Baud Rate Select bit (Usart 2)"
TRMT2=TXSTA2.1,"Transmit Shift Register Status flag (Usart 2)"
TX9D2=TXSTA2.0,"9th bit of transmit data. Can be parity bit. (Usart 1)"

SPEN2=RCSTA2.7,"Serial Port Enable (Usart 2)"
RX92=RCSTA2.6,"9-bit Receive Enable (Usart 2)"
SREN2=RCSTA2.5,"Single Receive Enable (Usart 2)"
CREN2=RCSTA2.4,"Continuous Receive Enable (Usart 2)"
ADDEN2=RCSTA2.3,"Address Detect Enable (Usart 2)"
FERR2=RCSTA2.2,"Framing Error (Usart 2)"
OERR2=RCSTA2.1,"Overrun Error (Usart 2)"
RX9D2=RCSTA2.0,"9th bit of received data Can be parity bit (Usart 2)"




